SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ReqIVLineLotDetailView] AS 
select 
	1 "TrxState", -- WORK 
	IVDOCNBR, 
	SERLTNUM, 
	SERLTQTY, 
	FROMBIN, 
	TOBIN, 
	LNSEQNBR, 
	SLTSQNUM, 
	MFGDATE, 
	EXPNDATE, 
	IVDOCTYP, 
	DATERECD 
from  
	IV10002 join  IV00101 on (IV00101.ITEMNMBR = IV10002.ITEMNMBR and IV00101.ITMTRKOP = 3) 
 
union all 
 
select 
	3 "TrxState", -- HISTORY 
	DOCNUMBR AS IVDOCNBR, 
	SERLTNUM, 
	SERLTQTY, 
	FROMBIN, 
	TOBIN, 
	LNSEQNBR, 
	SLTSQNUM, 
	MFGDATE, 
	EXPNDATE, 
	IVDOCTYP, 
	'' "DATERECD" 
from  
	IV30400 join  IV00101 on (IV00101.ITEMNMBR = IV30400.ITEMNMBR and IV00101.ITMTRKOP = 3) 
GO
GRANT SELECT ON  [dbo].[ReqIVLineLotDetailView] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ReqIVLineLotDetailView] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ReqIVLineLotDetailView] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ReqIVLineLotDetailView] TO [DYNGRP]
GO
