SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
-- PO Header View unioning POP10100 and POP30100 
 
CREATE VIEW [dbo].[ReqPOHeaderView] AS 
select   
	1 "TrxState", -- Set to 1 for Work  
	POTYPE,  
	PONUMBER,  
	VENDORID,  
	VENDNAME,  
	DOCDATE,  
	BUYERID,  
	ALLOWSOCMTS,  
	TRDISAMT,  
	FRTAMNT,  
	MSCCHAMT,  
	TAXAMNT,  
	SUBTOTAL,  
	CUSTNMBR,  
	PRSTADCD,  
	CMPNYNAM,  
	CONTACT,  
	ADDRESS1,  
	ADDRESS2,  
	ADDRESS3,  
	CITY,  
	STATE,  
	ZIPCODE,  
	CCode,  
	COUNTRY,  
	PHONE1,  
	PHONE2,  
	PHONE3,  
	FAX,  
	VADCDPAD,  
	PURCHCMPNYNAM,  
	PURCHCONTACT,  
	PURCHADDRESS1,  
	PURCHADDRESS2,  
	PURCHADDRESS3,  
	PURCHCITY,  
	PURCHSTATE,  
	PURCHZIPCODE,  
	PURCHCCode,  
	PURCHCOUNTRY,  
	PURCHPHONE1,  
	PURCHPHONE2,  
	PURCHPHONE3,  
	PURCHFAX,  
	PRBTADCD,  
	SHIPMTHD,  
	PYMTRMID,  
	DSCPCTAM,  
	DSCDLRAM,  
	DISAMTAV,  
	DUEDATE,  
	DISCDATE,  
	TXRGNNUM,  
	CONFIRM1,  
	POP10100.COMMNTID,  
	HOLD,  
	TAXSCHID,  
	Purchase_Freight_Taxable,  
	Purchase_Misc_Taxable,  
	FRTSCHID,  
	MSCSCHID,  
	FRTTXAMT,  
	MSCTXAMT,  
	BCKTXAMT,  
	BackoutFreightTaxAmt,  
	BackoutMiscTaxAmt, 
	case when POP10100.CURNCYID = '' then (select FUNLCURR from MC40000) else POP10100.CURNCYID end as CURNCYID,   
	XCHGRATE,  
	EXCHDATE,  
	USER2ENT,  
	POSTATUS,  
	POP10150.CMMTTEXT,  
	PRMDATE,  
	PRMSHPDTE,  
	REQDATE,  
	CONTENDDTE,  
	STATGRP,  
	REQTNDT,  
	REMSUBTO,  
	CMPANYID,  
	CANCSUB,  
	OREMSUBT,  
	ORSUBTOT,  
	Originating_Canceled_Sub,  
	ORTDISAM,  
	ORFRTAMT,  
	OMISCAMT,  
	ORTAXAMT,  
	ORDDLRAT,  
	ODISAMTAV,  
	LSTEDTDT,  
	LSTPRTDT,  
	TIMESPRT,  
	CREATDDT,  
	POP10100.DEX_ROW_TS,  
	Revision_Number,  
	ORFRTTAX,  
	ORMSCTAX,  
	OBTAXAMT,  
	OrigBackoutFreightTaxAmt,  
	OrigBackoutMiscTaxAmt,  
	POPCONTNUM,  
	Workflow_Priority WorkflowPriority,  
	Workflow_Approval_Status ApprovalWorkflowStatus,  
	POP10100.DEX_ROW_ID  
from   
	POP10100 left outer join POP10150 on (POP10100.PONUMBER = POP10150.POPNUMBE)  
  
  
  
union all  
  
  
select   
	3 "TrxState", -- Set to 3 for History  
	POTYPE,  
	PONUMBER,  
	VENDORID,  
	VENDNAME,  
	DOCDATE,  
	BUYERID,  
	ALLOWSOCMTS,  
	TRDISAMT,  
	FRTAMNT,  
	MSCCHAMT,  
	TAXAMNT,  
	SUBTOTAL,  
	CUSTNMBR,  
	PRSTADCD,  
	CMPNYNAM,  
	CONTACT,  
	ADDRESS1,  
	ADDRESS2,  
	ADDRESS3,  
	CITY,  
	STATE,  
	ZIPCODE,  
	CCode,  
	COUNTRY,  
	PHONE1,  
	PHONE2,  
	PHONE3,  
	FAX,  
	VADCDPAD,  
	PURCHCMPNYNAM,  
	PURCHCONTACT,  
	PURCHADDRESS1,  
	PURCHADDRESS2,  
	PURCHADDRESS3,  
	PURCHCITY,  
	PURCHSTATE,  
	PURCHZIPCODE,  
	PURCHCCode,  
	PURCHCOUNTRY,  
	PURCHPHONE1,  
	PURCHPHONE2,  
	PURCHPHONE3,  
	PURCHFAX,  
	PRBTADCD,  
	SHIPMTHD,  
	PYMTRMID,  
	DSCPCTAM,  
	DSCDLRAM,  
	DISAMTAV,  
	DUEDATE,  
	DISCDATE,  
	TXRGNNUM,  
	CONFIRM1,  
	POP30100.COMMNTID,  
	0 "HOLD",   
	TAXSCHID,  
	Purchase_Freight_Taxable,  
	Purchase_Misc_Taxable,  
	FRTSCHID,  
	MSCSCHID,  
	FRTTXAMT,  
	MSCTXAMT,  
	BCKTXAMT,  
	BackoutFreightTaxAmt,  
	BackoutMiscTaxAmt,  
	case when POP30100.CURNCYID = '' then (select FUNLCURR from MC40000) else POP30100.CURNCYID end as CURNCYID,  
	XCHGRATE,  
	EXCHDATE,  
	USER2ENT,  
	POSTATUS,  
	POP10150.CMMTTEXT,  
	PRMDATE,  
	PRMSHPDTE,  
	REQDATE,  
	CONTENDDTE,  
	STATGRP,  
	REQTNDT,  
	REMSUBTO,  
	CMPANYID,  
	CANCSUB,  
	OREMSUBT,  
	ORSUBTOT,  
	Originating_Canceled_Sub,  
	ORTDISAM,  
	ORFRTAMT,  
	OMISCAMT,  
	ORTAXAMT,  
	ORDDLRAT,  
	ODISAMTAV,  
	LSTEDTDT,  
	LSTPRTDT,  
	TIMESPRT,  
	CREATDDT,  
	POP30100.DEX_ROW_TS,  
	Revision_Number,  
	ORFRTTAX,  
	ORMSCTAX,  
	OBTAXAMT,  
	OrigBackoutFreightTaxAmt,  
	OrigBackoutMiscTaxAmt,  
	POPCONTNUM,  
	Workflow_Priority,  
	Workflow_Approval_Status,  
	POP30100.DEX_ROW_ID  
from   
	POP30100 left outer join POP10150 on (POP30100.PONUMBER = POP10150.POPNUMBE)  
  
GO
GRANT SELECT ON  [dbo].[ReqPOHeaderView] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ReqPOHeaderView] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ReqPOHeaderView] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ReqPOHeaderView] TO [DYNGRP]
GO
