SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE VIEW [dbo].[ivcHistoryTransactions] as (  select 0 as 'MKTOPROC',  0 as 'InfoValue',  0 as 'CURRNIDX',   GETDATE() AS 'DOCDATE',  0 as 'SOURCE',  0 as 'DOCTYPE',  REPLICATE('X', 21) as 'DOCTYNAM',  REPLICATE('X', 21) as 'DOCNUMBR',  REPLICATE('X', 15) as 'CUSTNMBR',  REPLICATE('X', 65) as 'CUSTNAME',  0 as 'PROSPECT',  0 as 'DCSTATUS',  REPLICATE('X', 31) as 'STSDESCR',  9999999999999.99999 as 'DOCAMNT',  REPLICATE('X', 15) as 'CURNCYID',  REPLICATE('X', 21) as 'CSTPONBR',  REPLICATE('X', 15) as 'PRSTADCD',  REPLICATE('X', 15) as 'SLPRSNID',  REPLICATE('X', 21) as 'SOPNUMBE',  0 as 'SOPSTATUS',  REPLICATE('X', 51) as 'SOPSTSDESCR',  REPLICATE('X', 21) as 'INVCNMBR',  0 as 'VOIDED',  REPLICATE('X', 15) as 'PRCHLDID',  GETDATE() AS 'QUOEXPDA',  GETDATE() AS 'ReqShipDate',  0 as 'ALLOCABY',  REPLICATE('X', 15) as 'DOCID',  0 as 'Password_Valid',  REPLICATE('X', 51) as 'Workflow_Name',  0 as 'Workflow_Approval_Status',  GETDATE() AS 'Workflow_Due_Date',  0 as 'Workflow_Priority',  REPLICATE('X', 238) as 'Workflow_Originator',  REPLICATE('X', 238) as 'Workflow_Approver',  9999999999999.9999 as 'QTYTOPURCH',  0 as 'SHIPCOMPLETE',  0 as 'WF_Step_Type',  REPLICATE('X', 15) as 'BACHNUMB',  REPLICATE('X', 15) as 'BCHSOURC',  0 as 'HOLDNT',  0 as 'Emailed'  where (1 = 0)  union all    select 0 as 'MKTOPROC',   0 as 'InfoValue',  0 as 'CURRNIDX',  ['Invoicing Transaction Hist'].[DOCDATE] as 'DOCDATE',  10 as 'SOURCE',   ['Invoicing Transaction Hist'].[DOCTYPE] as 'DOCTYPE',  DOCTYNAM = dbo.DYN_FUNC_SOP_Type(['Invoicing Transaction Hist'].[DOCTYPE]+2),  rtrim(['Invoicing Transaction Hist'].[INVCNMBR]) as 'DOCNUMBR',  rtrim(['Invoicing Transaction Hist'].[CUSTNMBR]) as 'CUSTNMBR',  rtrim(['Invoicing Transaction Hist'].[CUSTNAME]) as 'CUSTNAME',  0 as 'PROSPECT',  DCSTATUS = 3,  STSDESCR = 'History',  ['Invoicing Transaction Hist'].[DOCAMNT] as 'DOCAMNT',  rtrim(['Invoicing Transaction Hist'].[CURNCYID]) as 'CURNCYID',   rtrim(['Invoicing Transaction Hist'].[CSTPONBR]) as 'CSTPONBR',  rtrim(['Invoicing Transaction Hist'].[PRSTADCD]) as 'PRSTADCD',  rtrim(['Invoicing Transaction Hist'].[SLPRSNID]) as 'SLPRSNID',  '' as 'SOPNUMBE',  0 as 'SOPSTATUS',  '' as 'SOPSTSDESCR',  '' as 'INVCNMBR',  VOIDED = case  when ['Invoicing Transaction Hist'].[VOIDSTTS] = 0 then 0  else 1  end,  '' as 'PRCHLDID',  '01-01-1900' as 'QUOEXPDA',  '01-01-1900' as 'ReqShipDate',  0 as 'ALLOCABY',  '' as 'DOCID',  Password_Valid = 0,  '' as 'Workflow_Name',  0 as 'Workflow_Approval_Status',  '01-01-1900' as 'Workflow_Due_Date',  0 as 'Workflow_Priority',  '' as 'Workflow_Originator',  '' as 'Workflow_Approver',  0 as 'QTYTOPURCH',  0 as 'SHIPCOMPLETE',  0 as 'WF_Step_Type',  rtrim(['Invoicing Transaction Hist'].[BACHNUMB]) as 'BACHNUMB',  rtrim(['Invoicing Transaction Hist'].[BCHSOURC]) as 'BCHSOURC',  HOLDNT = ['Invoicing Transaction Hist'].[HOLDNT],  Emailed = 0   from [IVC30101] as ['Invoicing Transaction Hist'] with (NOLOCK)   where DOCTYPE = 1 or DOCTYPE = 2 )    
GO
GRANT SELECT ON  [dbo].[ivcHistoryTransactions] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ivcHistoryTransactions] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ivcHistoryTransactions] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ivcHistoryTransactions] TO [DYNGRP]
GO
