SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ReqIVLineSerialDetailView] AS 
select 
	1 "TrxState", -- WORK 
	IVDOCNBR, 
	SERLTNUM, 
	FROMBIN, 
	TOBIN, 
	LNSEQNBR, 
	SLTSQNUM, 
	IVDOCTYP 
from 
	IV10002 join  IV00101 on (IV00101.ITEMNMBR = IV10002.ITEMNMBR and IV00101.ITMTRKOP = 2) 
 
union all 
 
select 
	3 "TrxState", -- HISTORY 
	DOCNUMBR AS IVDOCNBR, 
	SERLTNUM, 
	FROMBIN, 
	TOBIN, 
	LNSEQNBR, 
	SLTSQNUM, 
	IVDOCTYP 
from 
	IV30400 join  IV00101 on (IV00101.ITEMNMBR = IV30400.ITEMNMBR and IV00101.ITMTRKOP = 2) 
GO
GRANT SELECT ON  [dbo].[ReqIVLineSerialDetailView] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ReqIVLineSerialDetailView] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ReqIVLineSerialDetailView] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ReqIVLineSerialDetailView] TO [DYNGRP]
GO
