SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE VIEW [dbo].[AAG00401V1] AS SELECT * FROM aagGetCodesForRollDown ()     
GO
GRANT SELECT ON  [dbo].[AAG00401V1] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[AAG00401V1] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[AAG00401V1] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[AAG00401V1] TO [DYNGRP]
GO
