SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
-- RM Customer View on table RM00103.  
 
CREATE VIEW [dbo].[ReqCustomerReceivablesSummary] AS 
select  
	RM00103.CUSTNMBR, 
	AGPERAMT_1, 
	AGPERAMT_2, 
	AGPERAMT_3, 
	AGPERAMT_4, 
	AGPERAMT_5, 
	AGPERAMT_6, 
	AGPERAMT_7, 
	LASTAGED, 
	CUSTBLNC, 
	AVDTPLYR, 
	HIBALLYR, 
	TTLINLYR, 
	TDTKNLYR, 
	TCSHRLYR, 
	TCOSTLYR, 
	TTLFCLYR, 
	TTLRTLYR, 
	TTLSLLYR, 
	TWVFCLYR, 
	TWROFLYR, 
	AVDTPLIF, 
	HIBALLTD, 
	TTLINLTD, 
	TDTKNLTD, 
	TCSHRLTD, 
	TCOSTLTD, 
	TTLFCLTD, 
	TTLRTLTD, 
	TTLSLLTD, 
	TWVFCLTD, 
	TWROFLTD, 
	AVGDTPYR, 
	HIBALYTD, 
	TTLINYTD, 
	TDTKNYTD, 
	TCSHRYTD, 
	TCOSTYTD, 
	TTLFCYTD, 
	TTLRTYTD, 
	TTLSLYTD, 
	TWVFCYTD, 
	TWROFYTD, 
	ONORDAMT, 
	LPYMTAMT, 
	LASTPYDT, 
	LSTSTAMT, 
	LASTSTDT, 
	LSTTRXAM, 
	LSTTRXDT, 
	SLPRSNID, 
	RM00103.DEX_ROW_ID 
from  
	RM00103 inner join RM00101 on RM00103.CUSTNMBR = RM00101.CUSTNMBR 
 
GO
GRANT SELECT ON  [dbo].[ReqCustomerReceivablesSummary] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ReqCustomerReceivablesSummary] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ReqCustomerReceivablesSummary] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ReqCustomerReceivablesSummary] TO [DYNGRP]
GO
