SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ReqPMHeaderTaxView] AS 
select 
	2 "TrxState", -- OPEN 
	VCHRNMBR, 
	TAXDTLID, 
	TAXAMNT, 
	ORTAXAMT, 
	PCTAXAMT, 
	ORPURTAX, 
	FRTTXAMT, 
	ORFRTTAX, 
	MSCTXAMT, 
	ORMSCTAX, 
	TDTTXPUR, 
	ORTXBPUR, 
	TXDTTPUR, 
	ORTOTPUR, 
	(select ACTNUMST from GL00105 where GL00105.ACTINDX = PM10500.ACTINDX) "ACTNUMST", 
	BKOUTTAX, 
	POSTED 
from  
	PM10500 
 
union all 
 
select 
	3 "TrxState", -- HISTORY 
	VCHRNMBR, 
	TAXDTLID, 
	TAXAMNT, 
	ORTAXAMT, 
	PCTAXAMT, 
	ORPURTAX, 
	FRTTXAMT, 
	ORFRTTAX, 
	MSCTXAMT, 
	ORMSCTAX, 
	TDTTXPUR, 
	ORTXBPUR, 
	TXDTTPUR, 
	ORTOTPUR, 
	(select ACTNUMST from GL00105 where GL00105.ACTINDX = PM30700.ACTINDX) "ACTNUMST", 
	BKOUTTAX, 
	NULL -- "POSTED" 
from  
	PM30700 
GO
GRANT SELECT ON  [dbo].[ReqPMHeaderTaxView] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ReqPMHeaderTaxView] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ReqPMHeaderTaxView] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ReqPMHeaderTaxView] TO [DYNGRP]
GO
