CREATE TABLE [dbo].[AHRAP004]
(
[APPLICANTNUMBER_I] [numeric] (19, 5) NOT NULL,
[APPINTTYPECODE_I] [smallint] NOT NULL,
[APPLYDATE_I] [datetime] NOT NULL,
[SEQORDER_I] [smallint] NOT NULL,
[APPINTCATCODE_I] [smallint] NOT NULL,
[CATEGORY_I] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WEIGHTFACTOR_I] [smallint] NOT NULL,
[REVIEWSCORE_I] [smallint] NOT NULL,
[NOTESINDEX_I] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AHRAP004] ADD CONSTRAINT [CK__AHRAP004__APPLYD__7DDAF99F] CHECK ((datepart(hour,[APPLYDATE_I])=(0) AND datepart(minute,[APPLYDATE_I])=(0) AND datepart(second,[APPLYDATE_I])=(0) AND datepart(millisecond,[APPLYDATE_I])=(0)))
GO
ALTER TABLE [dbo].[AHRAP004] ADD CONSTRAINT [PKAHRAP004] PRIMARY KEY CLUSTERED  ([APPLICANTNUMBER_I], [APPINTTYPECODE_I], [APPINTCATCODE_I], [APPLYDATE_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3AHRAP004] ON [dbo].[AHRAP004] ([APPLICANTNUMBER_I], [APPINTTYPECODE_I], [APPLYDATE_I], [APPINTCATCODE_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4AHRAP004] ON [dbo].[AHRAP004] ([APPLICANTNUMBER_I], [APPINTTYPECODE_I], [APPLYDATE_I], [SEQORDER_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1AHRAP004] ON [dbo].[AHRAP004] ([APPLICANTNUMBER_I], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHRAP004].[APPLICANTNUMBER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHRAP004].[APPINTTYPECODE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[AHRAP004].[APPLYDATE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHRAP004].[SEQORDER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHRAP004].[APPINTCATCODE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[AHRAP004].[CATEGORY_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHRAP004].[WEIGHTFACTOR_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHRAP004].[REVIEWSCORE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHRAP004].[NOTESINDEX_I]'
GO
GRANT SELECT ON  [dbo].[AHRAP004] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[AHRAP004] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[AHRAP004] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[AHRAP004] TO [DYNGRP]
GO
