CREATE TABLE [dbo].[SY00800]
(
[WINTYPE] [smallint] NOT NULL,
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CMPNYNAM] [char] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BCHSOURC] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BACHNUMB] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POSTING] [tinyint] NOT NULL,
[TRXSOURC] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY00800] ADD CONSTRAINT [PKSY00800] PRIMARY KEY NONCLUSTERED  ([USERID], [CMPNYNAM], [BACHNUMB], [BCHSOURC], [WINTYPE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SY00800] ON [dbo].[SY00800] ([BCHSOURC], [BACHNUMB], [CMPNYNAM], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3SY00800] ON [dbo].[SY00800] ([BCHSOURC], [POSTING], [CMPNYNAM], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY00800].[WINTYPE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY00800].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY00800].[CMPNYNAM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY00800].[BCHSOURC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY00800].[BACHNUMB]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY00800].[POSTING]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY00800].[TRXSOURC]'
GO
GRANT SELECT ON  [dbo].[SY00800] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY00800] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY00800] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY00800] TO [DYNGRP]
GO
