CREATE TABLE [dbo].[HRAPP002]
(
[APPINTTYPECODE_I] [smallint] NOT NULL,
[APPINTCATCODE_I] [smallint] NOT NULL,
[CATEGORY_I] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WEIGHTFACTOR_I] [smallint] NOT NULL,
[SEQORDER_I] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRAPP002] ADD CONSTRAINT [PKHRAPP002] PRIMARY KEY CLUSTERED  ([CATEGORY_I], [APPINTTYPECODE_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3HRAPP002] ON [dbo].[HRAPP002] ([APPINTCATCODE_I], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4HRAPP002] ON [dbo].[HRAPP002] ([APPINTTYPECODE_I], [APPINTCATCODE_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1HRAPP002] ON [dbo].[HRAPP002] ([APPINTTYPECODE_I], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK5HRAPP002] ON [dbo].[HRAPP002] ([APPINTTYPECODE_I], [SEQORDER_I]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRAPP002].[APPINTTYPECODE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRAPP002].[APPINTCATCODE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[HRAPP002].[CATEGORY_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRAPP002].[WEIGHTFACTOR_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRAPP002].[SEQORDER_I]'
GO
GRANT SELECT ON  [dbo].[HRAPP002] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[HRAPP002] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[HRAPP002] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[HRAPP002] TO [DYNGRP]
GO
