CREATE TABLE [dbo].[AHR2OF01]
(
[APPLICANTNUMBER_I] [numeric] (19, 5) NOT NULL,
[IINDEX_I] [smallint] NOT NULL,
[BENEFIT] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AHR2OF01] ADD CONSTRAINT [PKAHR2OF01] PRIMARY KEY NONCLUSTERED  ([APPLICANTNUMBER_I], [IINDEX_I], [BENEFIT]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2OF01].[APPLICANTNUMBER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHR2OF01].[IINDEX_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[AHR2OF01].[BENEFIT]'
GO
GRANT SELECT ON  [dbo].[AHR2OF01] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[AHR2OF01] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[AHR2OF01] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[AHR2OF01] TO [DYNGRP]
GO
