CREATE TABLE [dbo].[SY10700]
(
[SECURITYTASKID] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DICTID] [smallint] NOT NULL,
[SECURITYID] [int] NOT NULL,
[SECRESTYPE] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY10700] ADD CONSTRAINT [PKSY10700] PRIMARY KEY CLUSTERED  ([SECURITYTASKID], [DICTID], [SECURITYID], [SECRESTYPE]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY10700].[SECURITYTASKID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY10700].[DICTID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY10700].[SECURITYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY10700].[SECRESTYPE]'
GO
GRANT SELECT ON  [dbo].[SY10700] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY10700] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY10700] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY10700] TO [DYNGRP]
GO
