CREATE TABLE [dbo].[SY05100]
(
[HLPFRMID] [smallint] NOT NULL,
[MODULEID] [smallint] NOT NULL,
[INSM] [tinyint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY05100] ADD CONSTRAINT [PKSY05100] PRIMARY KEY NONCLUSTERED  ([HLPFRMID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SY05100] ON [dbo].[SY05100] ([MODULEID], [HLPFRMID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY05100].[HLPFRMID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY05100].[MODULEID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY05100].[INSM]'
GO
GRANT SELECT ON  [dbo].[SY05100] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY05100] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY05100] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY05100] TO [DYNGRP]
GO
