CREATE TABLE [dbo].[SY30000]
(
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CMPANYID] [smallint] NOT NULL,
[SEQNUMBR] [int] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1),
[Offline_Message] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY30000] ADD CONSTRAINT [PKSY30000] PRIMARY KEY CLUSTERED  ([USERID], [CMPANYID], [SEQNUMBR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY30000].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY30000].[CMPANYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SY30000].[SEQNUMBR]'
GO
GRANT SELECT ON  [dbo].[SY30000] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY30000] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY30000] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY30000] TO [DYNGRP]
GO
