CREATE TABLE [dbo].[STN41350]
(
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER2ENT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STN41350] ADD CONSTRAINT [PKSTN41350] PRIMARY KEY NONCLUSTERED  ([USERID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2STN41350] ON [dbo].[STN41350] ([USER2ENT], [USERID], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[STN41350].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[STN41350].[USER2ENT]'
GO
GRANT SELECT ON  [dbo].[STN41350] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[STN41350] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[STN41350] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[STN41350] TO [DYNGRP]
GO
