CREATE TABLE [dbo].[AHR2AP07]
(
[APPLICANTNUMBER_I] [numeric] (19, 5) NOT NULL,
[REQUISITIONNUMBER_I] [int] NOT NULL,
[TRAVELCOSTS_I] [numeric] (19, 5) NOT NULL,
[LODGINGCOSTS_I] [numeric] (19, 5) NOT NULL,
[MOVINGEXPENSES_I] [numeric] (19, 5) NOT NULL,
[OTHERCOSTS_I] [numeric] (19, 5) NOT NULL,
[NOTESINDEX_I] [numeric] (19, 5) NOT NULL,
[TOTALCOSTS_I] [numeric] (19, 5) NOT NULL,
[CHANGEBY_I] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CHANGEDATE_I] [datetime] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AHR2AP07] ADD CONSTRAINT [CK__AHR2AP07__CHANGE__650F4BD5] CHECK ((datepart(hour,[CHANGEDATE_I])=(0) AND datepart(minute,[CHANGEDATE_I])=(0) AND datepart(second,[CHANGEDATE_I])=(0) AND datepart(millisecond,[CHANGEDATE_I])=(0)))
GO
ALTER TABLE [dbo].[AHR2AP07] ADD CONSTRAINT [PKAHR2AP07] PRIMARY KEY CLUSTERED  ([APPLICANTNUMBER_I], [REQUISITIONNUMBER_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2AHR2AP07] ON [dbo].[AHR2AP07] ([REQUISITIONNUMBER_I], [APPLICANTNUMBER_I]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[APPLICANTNUMBER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[AHR2AP07].[REQUISITIONNUMBER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[TRAVELCOSTS_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[LODGINGCOSTS_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[MOVINGEXPENSES_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[OTHERCOSTS_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[NOTESINDEX_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AHR2AP07].[TOTALCOSTS_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[AHR2AP07].[CHANGEBY_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[AHR2AP07].[CHANGEDATE_I]'
GO
GRANT SELECT ON  [dbo].[AHR2AP07] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[AHR2AP07] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[AHR2AP07] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[AHR2AP07] TO [DYNGRP]
GO
