CREATE TABLE [dbo].[ERB90100]
(
[PRODID] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERB90100] ADD CONSTRAINT [PKERB90100] PRIMARY KEY NONCLUSTERED  ([PRODID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[ERB90100].[PRODID]'
GO
GRANT SELECT ON  [dbo].[ERB90100] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ERB90100] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ERB90100] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ERB90100] TO [DYNGRP]
GO
