SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_E1REGSS_1] (@PRODID smallint) AS /* 12.00.0311.000 */ set nocount on SELECT TOP 1  PRODID, REGNKEYS_1, REGNKEYS_2, REGNKEYS_3, REGNKEYS_4, REGNKEYS_5, DEX_ROW_ID FROM .E1REG WHERE PRODID = @PRODID ORDER BY PRODID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_E1REGSS_1] TO [DYNGRP]
GO
