SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_MC40401SS_2] (@ENABLED tinyint) AS  set nocount on SELECT TOP 1  DENOMCURR, DENXRATE, ENABLED, DEX_ROW_ID FROM .MC40401 WHERE ENABLED = @ENABLED ORDER BY ENABLED ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_MC40401SS_2] TO [DYNGRP]
GO
