SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_CARD40SS_1] (@DSCRIPTN char(31)) AS  set nocount on SELECT TOP 1  INTERNALCODIVCB_I, DSCRIPTN, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE_I, WORKPHONE, EXT_I, IFAX_I, EXT2_I, FFIRSTNAME_I, EMAILADDRESS_I, DEX_ROW_ID FROM .CARD40 WHERE DSCRIPTN = @DSCRIPTN ORDER BY DSCRIPTN ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CARD40SS_1] TO [DYNGRP]
GO
