SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY07200SS_1] (@USERID char(15), @DICTID smallint, @FormID smallint) AS  set nocount on SELECT TOP 1  USERID, DICTID, FormID, ListOption, ListDateRestriction, ListOption2, DEX_ROW_ID FROM .SY07200 WHERE USERID = @USERID AND DICTID = @DICTID AND FormID = @FormID ORDER BY USERID ASC, DICTID ASC, FormID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY07200SS_1] TO [DYNGRP]
GO
