SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY61401L_1] (@USERID_RS char(15), @SocialNetworkID_RS smallint, @USERID_RE char(15), @SocialNetworkID_RE smallint) AS  set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  USERID, SocialNetworkID, oAuthToken, DEX_ROW_ID FROM .SY61401 ORDER BY USERID DESC, SocialNetworkID DESC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  USERID, SocialNetworkID, oAuthToken, DEX_ROW_ID FROM .SY61401 WHERE USERID = @USERID_RS AND SocialNetworkID BETWEEN @SocialNetworkID_RS AND @SocialNetworkID_RE ORDER BY USERID DESC, SocialNetworkID DESC END ELSE BEGIN SELECT TOP 25  USERID, SocialNetworkID, oAuthToken, DEX_ROW_ID FROM .SY61401 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE AND SocialNetworkID BETWEEN @SocialNetworkID_RS AND @SocialNetworkID_RE ORDER BY USERID DESC, SocialNetworkID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY61401L_1] TO [DYNGRP]
GO
