SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY05000SI] (@INDEX1 smallint, @PRODNAME char(31), @CMPNYNAM char(65), @USERID char(15), @INQYTYPE smallint, @DATE1 datetime, @TIME1 datetime, @SECDESC char(99), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY05000 (INDEX1, PRODNAME, CMPNYNAM, USERID, INQYTYPE, DATE1, TIME1, SECDESC) VALUES ( @INDEX1, @PRODNAME, @CMPNYNAM, @USERID, @INQYTYPE, @DATE1, @TIME1, @SECDESC) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY05000SI] TO [DYNGRP]
GO
