SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AHR2AP07SS_1] (@APPLICANTNUMBER_I numeric(19,5), @REQUISITIONNUMBER_I int) AS  set nocount on SELECT TOP 1  APPLICANTNUMBER_I, REQUISITIONNUMBER_I, TRAVELCOSTS_I, LODGINGCOSTS_I, MOVINGEXPENSES_I, OTHERCOSTS_I, NOTESINDEX_I, TOTALCOSTS_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .AHR2AP07 WHERE APPLICANTNUMBER_I = @APPLICANTNUMBER_I AND REQUISITIONNUMBER_I = @REQUISITIONNUMBER_I ORDER BY APPLICANTNUMBER_I ASC, REQUISITIONNUMBER_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AHR2AP07SS_1] TO [DYNGRP]
GO
