SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY10500F_2] (@SECURITYROLEID_RS char(25), @USERID_RS char(15), @CMPANYID_RS smallint, @SECURITYROLEID_RE char(25), @USERID_RE char(15), @CMPANYID_RE smallint) AS  set nocount on IF @SECURITYROLEID_RS IS NULL BEGIN SELECT TOP 25  USERID, CMPANYID, SECURITYROLEID, DEX_ROW_ID FROM .SY10500 ORDER BY SECURITYROLEID ASC, USERID ASC, CMPANYID ASC END ELSE IF @SECURITYROLEID_RS = @SECURITYROLEID_RE BEGIN SELECT TOP 25  USERID, CMPANYID, SECURITYROLEID, DEX_ROW_ID FROM .SY10500 WHERE SECURITYROLEID = @SECURITYROLEID_RS AND USERID BETWEEN @USERID_RS AND @USERID_RE AND CMPANYID BETWEEN @CMPANYID_RS AND @CMPANYID_RE ORDER BY SECURITYROLEID ASC, USERID ASC, CMPANYID ASC END ELSE BEGIN SELECT TOP 25  USERID, CMPANYID, SECURITYROLEID, DEX_ROW_ID FROM .SY10500 WHERE SECURITYROLEID BETWEEN @SECURITYROLEID_RS AND @SECURITYROLEID_RE AND USERID BETWEEN @USERID_RS AND @USERID_RE AND CMPANYID BETWEEN @CMPANYID_RS AND @CMPANYID_RE ORDER BY SECURITYROLEID ASC, USERID ASC, CMPANYID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY10500F_2] TO [DYNGRP]
GO
