SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_HRPMPS01SS_3] (@COMPANYCODE_I char(7), @POSITION_I char(31)) AS  set nocount on SELECT TOP 1  COMPANYCODE_I, POSITIONCODE_I, POSITION_I, DEX_ROW_ID FROM .HRPMPS01 WHERE COMPANYCODE_I = @COMPANYCODE_I AND POSITION_I = @POSITION_I ORDER BY COMPANYCODE_I ASC, POSITION_I ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRPMPS01SS_3] TO [DYNGRP]
GO
