SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_STN41200L_1] (@PRNSER_RS smallint, @PRNTASK_RS char(15), @PRNSER_RE smallint, @PRNTASK_RE char(15)) AS  set nocount on IF @PRNSER_RS IS NULL BEGIN SELECT TOP 25  PRNSER, PRNTASK, PRNTTASKDESC, DEX_ROW_ID FROM .STN41200 ORDER BY PRNSER DESC, PRNTASK DESC END ELSE IF @PRNSER_RS = @PRNSER_RE BEGIN SELECT TOP 25  PRNSER, PRNTASK, PRNTTASKDESC, DEX_ROW_ID FROM .STN41200 WHERE PRNSER = @PRNSER_RS AND PRNTASK BETWEEN @PRNTASK_RS AND @PRNTASK_RE ORDER BY PRNSER DESC, PRNTASK DESC END ELSE BEGIN SELECT TOP 25  PRNSER, PRNTASK, PRNTTASKDESC, DEX_ROW_ID FROM .STN41200 WHERE PRNSER BETWEEN @PRNSER_RS AND @PRNSER_RE AND PRNTASK BETWEEN @PRNTASK_RS AND @PRNTASK_RE ORDER BY PRNSER DESC, PRNTASK DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_STN41200L_1] TO [DYNGRP]
GO
