SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY01900SS_1] (@CMPANYID smallint, @USERID char(15), @REPORTID smallint) AS  set nocount on SELECT TOP 1  CMPANYID, USERID, REPORTID, DEX_ROW_ID FROM .SY01900 WHERE CMPANYID = @CMPANYID AND USERID = @USERID AND REPORTID = @REPORTID ORDER BY CMPANYID ASC, USERID ASC, REPORTID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY01900SS_1] TO [DYNGRP]
GO
