SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME240443SS_1] (@CMPANYID smallint) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  CMPANYID, ACTIVE, FilePath, MEPDFPath, DEX_ROW_ID FROM .ME240443 WHERE CMPANYID = @CMPANYID ORDER BY CMPANYID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME240443SS_1] TO [DYNGRP]
GO
