SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROC [dbo].[zDP_EXT90105SS_2] (@PRODID smallint, @RPRTNAME char(31)) AS set nocount on SELECT TOP 1  PRODID, Series_Number, RPRTNAME, DEX_ROW_ID FROM .EXT90105 WHERE PRODID = @PRODID AND RPRTNAME = @RPRTNAME ORDER BY PRODID ASC, RPRTNAME ASC set nocount off   
GO
GRANT EXECUTE ON  [dbo].[zDP_EXT90105SS_2] TO [DYNGRP]
GO
