SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MEP40300SI] (@PRODID smallint, @CMPANYID smallint, @CURVERSION char(15), @MEACTIVATED tinyint, @DEX_ROW_ID int OUT) AS /* 14.00.0084.000 */ set nocount on BEGIN INSERT INTO .MEP40300 (PRODID, CMPANYID, CURVERSION, MEACTIVATED) VALUES ( @PRODID, @CMPANYID, @CURVERSION, @MEACTIVATED) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MEP40300SI] TO [DYNGRP]
GO
