SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_MC00100SS_2] (@CURNCYID char(15), @EXGTBLID char(15)) AS  set nocount on SELECT TOP 1  EXGTBLID, CURNCYID, EXCHDATE, TIME1, XCHGRATE, EXPNDATE, DEX_ROW_ID FROM .MC00100 WHERE CURNCYID = @CURNCYID AND EXGTBLID = @EXGTBLID ORDER BY CURNCYID ASC, EXGTBLID ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_MC00100SS_2] TO [DYNGRP]
GO
