SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_HR2APP13SS_1] (@APPLICANTNUMBER_I numeric(19,5), @ISEQUENCENUMBER_I smallint) AS  set nocount on SELECT TOP 1  APPLICANTNUMBER_I, ISEQUENCENUMBER_I, REFERENCENAME_I, REFRELATIONSHIP_I, COMPANY_I, ADDRESS1, CITY, STATE, ZIPCODE_I, WORKPHONE, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .HR2APP13 WHERE APPLICANTNUMBER_I = @APPLICANTNUMBER_I AND ISEQUENCENUMBER_I = @ISEQUENCENUMBER_I ORDER BY APPLICANTNUMBER_I ASC, ISEQUENCENUMBER_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2APP13SS_1] TO [DYNGRP]
GO
