SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_DT00100SD] (@CMPANYID smallint, @USERID char(15), @TOOLBARBUTTON smallint, @TOOLBARSEQ smallint, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .DT00100 WHERE CMPANYID = @CMPANYID AND USERID = @USERID AND TOOLBARBUTTON = @TOOLBARBUTTON AND TOOLBARSEQ = @TOOLBARSEQ AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .DT00100 WHERE CMPANYID = @CMPANYID AND USERID = @USERID AND TOOLBARBUTTON = @TOOLBARBUTTON AND TOOLBARSEQ = @TOOLBARSEQ SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DT00100SD] TO [DYNGRP]
GO
