SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_EBSKEYSN_1] (@BS int, @EBSPRODUCT char(21), @EBSPRODUCT_RS char(21), @EBSPRODUCT_RE char(21)) AS  set nocount on IF @EBSPRODUCT_RS IS NULL BEGIN SELECT TOP 25  EBSKEYS, EBSPRODUCT, DEX_ROW_ID FROM .EBSKEYS WHERE ( EBSPRODUCT > @EBSPRODUCT ) ORDER BY EBSPRODUCT ASC END ELSE IF @EBSPRODUCT_RS = @EBSPRODUCT_RE BEGIN SELECT TOP 25  EBSKEYS, EBSPRODUCT, DEX_ROW_ID FROM .EBSKEYS WHERE EBSPRODUCT = @EBSPRODUCT_RS AND ( EBSPRODUCT > @EBSPRODUCT ) ORDER BY EBSPRODUCT ASC END ELSE BEGIN SELECT TOP 25  EBSKEYS, EBSPRODUCT, DEX_ROW_ID FROM .EBSKEYS WHERE EBSPRODUCT BETWEEN @EBSPRODUCT_RS AND @EBSPRODUCT_RE AND ( EBSPRODUCT > @EBSPRODUCT ) ORDER BY EBSPRODUCT ASC END set nocount off     
GO
GRANT EXECUTE ON  [dbo].[zDP_EBSKEYSN_1] TO [DYNGRP]
GO
