SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME142704L_1] (@MEMSN_RS smallint, @MEMSN_RE smallint) AS /* 12.00.0311.000 */ set nocount on IF @MEMSN_RS IS NULL BEGIN SELECT TOP 25  MEMSN, MELDP, ME_Virtual_Workstation, ME_Virtual_WS_In_Use, MEREQFPTH, MEANSFPTH, MEWSAB, MEWSA, ME_Virtual_WS_Times_Used, USERID, USERDATE, TIME1, ME_Dummy_File_Conversion, DEX_ROW_ID FROM .ME142704 ORDER BY MEMSN DESC END ELSE IF @MEMSN_RS = @MEMSN_RE BEGIN SELECT TOP 25  MEMSN, MELDP, ME_Virtual_Workstation, ME_Virtual_WS_In_Use, MEREQFPTH, MEANSFPTH, MEWSAB, MEWSA, ME_Virtual_WS_Times_Used, USERID, USERDATE, TIME1, ME_Dummy_File_Conversion, DEX_ROW_ID FROM .ME142704 WHERE MEMSN = @MEMSN_RS ORDER BY MEMSN DESC END ELSE BEGIN SELECT TOP 25  MEMSN, MELDP, ME_Virtual_Workstation, ME_Virtual_WS_In_Use, MEREQFPTH, MEANSFPTH, MEWSAB, MEWSA, ME_Virtual_WS_Times_Used, USERID, USERDATE, TIME1, ME_Dummy_File_Conversion, DEX_ROW_ID FROM .ME142704 WHERE MEMSN BETWEEN @MEMSN_RS AND @MEMSN_RE ORDER BY MEMSN DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME142704L_1] TO [DYNGRP]
GO
