SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY02600N_1] (@BS int, @USERID char(15), @USRNTFLG tinyint, @USERID_RS char(15), @USRNTFLG_RS tinyint, @USERID_RE char(15), @USRNTFLG_RE tinyint) AS  set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  USERID, DATE1, TIME1, USRNTFLG, DEX_ROW_ID, TXTFIELD FROM .SY02600 WHERE ( USERID = @USERID AND USRNTFLG > @USRNTFLG OR USERID > @USERID ) ORDER BY USERID ASC, USRNTFLG ASC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  USERID, DATE1, TIME1, USRNTFLG, DEX_ROW_ID, TXTFIELD FROM .SY02600 WHERE USERID = @USERID_RS AND USRNTFLG BETWEEN @USRNTFLG_RS AND @USRNTFLG_RE AND ( USERID = @USERID AND USRNTFLG > @USRNTFLG OR USERID > @USERID ) ORDER BY USERID ASC, USRNTFLG ASC END ELSE BEGIN SELECT TOP 25  USERID, DATE1, TIME1, USRNTFLG, DEX_ROW_ID, TXTFIELD FROM .SY02600 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE AND USRNTFLG BETWEEN @USRNTFLG_RS AND @USRNTFLG_RE AND ( USERID = @USERID AND USRNTFLG > @USRNTFLG OR USERID > @USERID ) ORDER BY USERID ASC, USRNTFLG ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY02600N_1] TO [DYNGRP]
GO
