SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_WDC51100SS_2] (@WDC_Entity_ID int) AS  set nocount on SELECT TOP 1  WDC_Entity_ID, USRCLASS, CMPANYID, USERID, ACTIVE, DEX_ROW_ID FROM .WDC51100 WHERE WDC_Entity_ID = @WDC_Entity_ID ORDER BY WDC_Entity_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_WDC51100SS_2] TO [DYNGRP]
GO
