SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SYVM1000F_1] (@VERSIONSTRING_I_RS char(13), @USERID_RS char(15), @PRODID_RS smallint, @VERSIONSTRING_I_RE char(13), @USERID_RE char(15), @PRODID_RE smallint) AS  set nocount on IF @VERSIONSTRING_I_RS IS NULL BEGIN SELECT TOP 25  PRODID, VERSIONSTRING_I, USERID, DEX_ROW_ID FROM .SYVM1000 ORDER BY VERSIONSTRING_I ASC, USERID ASC, PRODID ASC END ELSE IF @VERSIONSTRING_I_RS = @VERSIONSTRING_I_RE BEGIN SELECT TOP 25  PRODID, VERSIONSTRING_I, USERID, DEX_ROW_ID FROM .SYVM1000 WHERE VERSIONSTRING_I = @VERSIONSTRING_I_RS AND USERID BETWEEN @USERID_RS AND @USERID_RE AND PRODID BETWEEN @PRODID_RS AND @PRODID_RE ORDER BY VERSIONSTRING_I ASC, USERID ASC, PRODID ASC END ELSE BEGIN SELECT TOP 25  PRODID, VERSIONSTRING_I, USERID, DEX_ROW_ID FROM .SYVM1000 WHERE VERSIONSTRING_I BETWEEN @VERSIONSTRING_I_RS AND @VERSIONSTRING_I_RE AND USERID BETWEEN @USERID_RS AND @USERID_RE AND PRODID BETWEEN @PRODID_RS AND @PRODID_RE ORDER BY VERSIONSTRING_I ASC, USERID ASC, PRODID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SYVM1000F_1] TO [DYNGRP]
GO
