SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY04701SS_1] (@SERVERID char(81)) AS  set nocount on SELECT TOP 1  SERVERID, DEX_ROW_ID FROM .SY04701 WHERE SERVERID = @SERVERID ORDER BY SERVERID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY04701SS_1] TO [DYNGRP]
GO
