SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROC [dbo].[zDP_ERB90500N_1] (@BS int, @CMPANYID smallint, @Data_Connection_ID char(15), @CMPANYID_RS smallint, @Data_Connection_ID_RS char(15), @CMPANYID_RE smallint, @Data_Connection_ID_RE char(15)) AS set nocount on IF @CMPANYID_RS IS NULL BEGIN SELECT TOP 25  CMPANYID, Data_Connection_ID, DEX_ROW_ID FROM .ERB90500 WHERE ( CMPANYID = @CMPANYID AND Data_Connection_ID > @Data_Connection_ID OR CMPANYID > @CMPANYID ) ORDER BY CMPANYID ASC, Data_Connection_ID ASC END ELSE IF @CMPANYID_RS = @CMPANYID_RE BEGIN SELECT TOP 25  CMPANYID, Data_Connection_ID, DEX_ROW_ID FROM .ERB90500 WHERE CMPANYID = @CMPANYID_RS AND Data_Connection_ID BETWEEN @Data_Connection_ID_RS AND @Data_Connection_ID_RE AND ( CMPANYID = @CMPANYID AND Data_Connection_ID > @Data_Connection_ID OR CMPANYID > @CMPANYID ) ORDER BY CMPANYID ASC, Data_Connection_ID ASC END ELSE BEGIN SELECT TOP 25  CMPANYID, Data_Connection_ID, DEX_ROW_ID FROM .ERB90500 WHERE CMPANYID BETWEEN @CMPANYID_RS AND @CMPANYID_RE AND Data_Connection_ID BETWEEN @Data_Connection_ID_RS AND @Data_Connection_ID_RE AND ( CMPANYID = @CMPANYID AND Data_Connection_ID > @Data_Connection_ID OR CMPANYID > @CMPANYID ) ORDER BY CMPANYID ASC, Data_Connection_ID ASC END set nocount off   
GO
GRANT EXECUTE ON  [dbo].[zDP_ERB90500N_1] TO [DYNGRP]
GO
