SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY03600F_1] (@WKSTNTYP_RS char(15), @LOFPTHNM_RS smallint, @WKSTNTYP_RE char(15), @LOFPTHNM_RE smallint) AS  set nocount on IF @WKSTNTYP_RS IS NULL BEGIN SELECT TOP 25  WKSTNTYP, LOFPTHNM, FRMPTHNM, DTAPTHNM, DEX_ROW_ID FROM .SY03600 ORDER BY WKSTNTYP ASC, LOFPTHNM ASC, DEX_ROW_ID ASC END ELSE IF @WKSTNTYP_RS = @WKSTNTYP_RE BEGIN SELECT TOP 25  WKSTNTYP, LOFPTHNM, FRMPTHNM, DTAPTHNM, DEX_ROW_ID FROM .SY03600 WHERE WKSTNTYP = @WKSTNTYP_RS AND LOFPTHNM BETWEEN @LOFPTHNM_RS AND @LOFPTHNM_RE ORDER BY WKSTNTYP ASC, LOFPTHNM ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  WKSTNTYP, LOFPTHNM, FRMPTHNM, DTAPTHNM, DEX_ROW_ID FROM .SY03600 WHERE WKSTNTYP BETWEEN @WKSTNTYP_RS AND @WKSTNTYP_RE AND LOFPTHNM BETWEEN @LOFPTHNM_RS AND @LOFPTHNM_RE ORDER BY WKSTNTYP ASC, LOFPTHNM ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY03600F_1] TO [DYNGRP]
GO
