SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MEP40300F_1] (@PRODID_RS smallint, @CMPANYID_RS smallint, @PRODID_RE smallint, @CMPANYID_RE smallint) AS /* 14.00.0084.000 */ set nocount on IF @PRODID_RS IS NULL BEGIN SELECT TOP 25  PRODID, CMPANYID, CURVERSION, MEACTIVATED, DEX_ROW_ID FROM .MEP40300 ORDER BY PRODID ASC, CMPANYID ASC END ELSE IF @PRODID_RS = @PRODID_RE BEGIN SELECT TOP 25  PRODID, CMPANYID, CURVERSION, MEACTIVATED, DEX_ROW_ID FROM .MEP40300 WHERE PRODID = @PRODID_RS AND CMPANYID BETWEEN @CMPANYID_RS AND @CMPANYID_RE ORDER BY PRODID ASC, CMPANYID ASC END ELSE BEGIN SELECT TOP 25  PRODID, CMPANYID, CURVERSION, MEACTIVATED, DEX_ROW_ID FROM .MEP40300 WHERE PRODID BETWEEN @PRODID_RS AND @PRODID_RE AND CMPANYID BETWEEN @CMPANYID_RS AND @CMPANYID_RE ORDER BY PRODID ASC, CMPANYID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MEP40300F_1] TO [DYNGRP]
GO
