SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY09000SS_1] (@SECURITYTASKID char(25)) AS  set nocount on SELECT TOP 1  SECURITYTASKID, SECURITYTASKNAME, SECURITYTASKDESC, SECURITYTASKCATEGORY, DEFSECTASK, CRUSRID, CREATDDT, MDFUSRID, MODIFDT, DEX_ROW_ID FROM .SY09000 WHERE SECURITYTASKID = @SECURITYTASKID ORDER BY SECURITYTASKID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY09000SS_1] TO [DYNGRP]
GO
