SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SYVM1000SS_1] (@VERSIONSTRING_I char(13), @USERID char(15), @PRODID smallint) AS  set nocount on SELECT TOP 1  PRODID, VERSIONSTRING_I, USERID, DEX_ROW_ID FROM .SYVM1000 WHERE VERSIONSTRING_I = @VERSIONSTRING_I AND USERID = @USERID AND PRODID = @PRODID ORDER BY VERSIONSTRING_I ASC, USERID ASC, PRODID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SYVM1000SS_1] TO [DYNGRP]
GO
