SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY04000SS_1] (@USERID char(15), @CMPNYNAM char(65), @BCHSOURC char(15), @BACHNUMB char(15)) AS  set nocount on SELECT TOP 1  USERID, CMPNYNAM, BCHSOURC, BACHNUMB, PRRPTFAR_1, PRRPTFAR_2, PRRPTFAR_3, PRRPTFAR_4, PRRPTFAR_5, PRRPTFAR_6, PRTSCRAR_1, PRTSCRAR_2, PRTSCRAR_3, PRTSCRAR_4, PRTSCRAR_5, PRTSCRAR_6, PRTPRARR_1, PRTPRARR_2, PRTPRARR_3, PRTPRARR_4, PRTPRARR_5, PRTPRARR_6, EXPTFTAR_1, EXPTFTAR_2, EXPTFTAR_3, EXPTFTAR_4, EXPTFTAR_5, EXPTFTAR_6, FEXPNMAR_1, FEXPNMAR_2, FEXPNMAR_3, FEXPNMAR_4, FEXPNMAR_5, FEXPNMAR_6, DEX_ROW_ID FROM .SY04000 WHERE USERID = @USERID AND CMPNYNAM = @CMPNYNAM AND BCHSOURC = @BCHSOURC AND BACHNUMB = @BACHNUMB ORDER BY USERID ASC, CMPNYNAM ASC, BCHSOURC ASC, BACHNUMB ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY04000SS_1] TO [DYNGRP]
GO
