SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_HR2SKL01SS_2] (@SKILLTITLE_I char(31)) AS  set nocount on SELECT TOP 1  SKILLNUMBER_I, SKILLTITLE_I, COMPENSATIONVALUE_I, COMPENSATIONPERIOD_I, DEX_ROW_ID FROM .HR2SKL01 WHERE SKILLTITLE_I = @SKILLTITLE_I ORDER BY SKILLTITLE_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2SKL01SS_2] TO [DYNGRP]
GO
