SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY04400SS_4] (@DEX_ROW_ID int) AS  set nocount on SELECT TOP 1  SERVERID, USERID, WORDSTID, DPSERIES, PROCNAME, DATE1, TIME1, MESSAGE, CMPNYNAM, DEX_ROW_ID FROM .SY04400 WHERE DEX_ROW_ID = @DEX_ROW_ID ORDER BY DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY04400SS_4] TO [DYNGRP]
GO
