SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY10800SD] (@SECMODALTID char(25), @DICTID smallint, @SECURITYID int, @SECRESTYPE smallint, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .SY10800 WHERE SECMODALTID = @SECMODALTID AND DICTID = @DICTID AND SECURITYID = @SECURITYID AND SECRESTYPE = @SECRESTYPE AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .SY10800 WHERE SECMODALTID = @SECMODALTID AND DICTID = @DICTID AND SECURITYID = @SECURITYID AND SECRESTYPE = @SECRESTYPE SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY10800SD] TO [DYNGRP]
GO
