SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY00302SI] (@SGMTNUMB smallint, @SGMTNAME char(15), @SGMNTLTH smallint, @USDFSGKY smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY00302 (SGMTNUMB, SGMTNAME, SGMNTLTH, USDFSGKY) VALUES ( @SGMTNUMB, @SGMTNAME, @SGMNTLTH, @USDFSGKY) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY00302SI] TO [DYNGRP]
GO
