SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY03700SS_1] (@LSNCOMLD tinyint) AS  set nocount on SELECT TOP 1  LSNCOMLD, DEX_ROW_ID FROM .SY03700 WHERE LSNCOMLD = @LSNCOMLD ORDER BY LSNCOMLD ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY03700SS_1] TO [DYNGRP]
GO
