SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY10997SI] (@DICTID smallint, @Language_ID smallint, @FUNCNAME char(101), @FUNCENUM smallint, @MSGNUM smallint, @Field_ResID smallint, @SQL_MSG char(255), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY10997 (DICTID, Language_ID, FUNCNAME, FUNCENUM, MSGNUM, Field_ResID, SQL_MSG) VALUES ( @DICTID, @Language_ID, @FUNCNAME, @FUNCENUM, @MSGNUM, @Field_ResID, @SQL_MSG) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY10997SI] TO [DYNGRP]
GO
