SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY_SQL_OptionsL_1] (@DATASCNM_RS char(33), @DATASCNM_RE char(33)) AS  set nocount on IF @DATASCNM_RS IS NULL BEGIN SELECT TOP 25  DATASCNM, CTRLLOGN, CTRLUSER, TRUNCLOG, TRUNDATA, SQLSPAR1, SQLSPAR2, SQLSPAR3, DEX_ROW_ID FROM .SY_SQL_Options ORDER BY DATASCNM DESC END ELSE IF @DATASCNM_RS = @DATASCNM_RE BEGIN SELECT TOP 25  DATASCNM, CTRLLOGN, CTRLUSER, TRUNCLOG, TRUNDATA, SQLSPAR1, SQLSPAR2, SQLSPAR3, DEX_ROW_ID FROM .SY_SQL_Options WHERE DATASCNM = @DATASCNM_RS ORDER BY DATASCNM DESC END ELSE BEGIN SELECT TOP 25  DATASCNM, CTRLLOGN, CTRLUSER, TRUNCLOG, TRUNDATA, SQLSPAR1, SQLSPAR2, SQLSPAR3, DEX_ROW_ID FROM .SY_SQL_Options WHERE DATASCNM BETWEEN @DATASCNM_RS AND @DATASCNM_RE ORDER BY DATASCNM DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY_SQL_OptionsL_1] TO [DYNGRP]
GO
