SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY01600UN_2] (@BS int, @CMPNYNAM char(65), @USERID char(15), @CMPNYNAM_RS char(65), @USERID_RS char(15), @CMPNYNAM_RE char(65), @USERID_RE char(15)) AS  set nocount on IF @CMPNYNAM_RS IS NULL BEGIN SELECT TOP 25  USERID, CMPNYNAM, FORMNAME, WINNAME, STICKPIN, DEX_ROW_ID FROM .SY01600 WHERE ( CMPNYNAM = @CMPNYNAM AND USERID > @USERID OR CMPNYNAM > @CMPNYNAM ) ORDER BY CMPNYNAM ASC, USERID ASC, DEX_ROW_ID ASC END ELSE IF @CMPNYNAM_RS = @CMPNYNAM_RE BEGIN SELECT TOP 25  USERID, CMPNYNAM, FORMNAME, WINNAME, STICKPIN, DEX_ROW_ID FROM .SY01600 WHERE CMPNYNAM = @CMPNYNAM_RS AND USERID BETWEEN @USERID_RS AND @USERID_RE AND ( CMPNYNAM = @CMPNYNAM AND USERID > @USERID OR CMPNYNAM > @CMPNYNAM ) ORDER BY CMPNYNAM ASC, USERID ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  USERID, CMPNYNAM, FORMNAME, WINNAME, STICKPIN, DEX_ROW_ID FROM .SY01600 WHERE CMPNYNAM BETWEEN @CMPNYNAM_RS AND @CMPNYNAM_RE AND USERID BETWEEN @USERID_RS AND @USERID_RE AND ( CMPNYNAM = @CMPNYNAM AND USERID > @USERID OR CMPNYNAM > @CMPNYNAM ) ORDER BY CMPNYNAM ASC, USERID ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY01600UN_2] TO [DYNGRP]
GO
