SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SOPMSTRN_1] (@BS int, @SOPCATEGORIES_I char(31), @SOPCATEGORIES_I_RS char(31), @SOPCATEGORIES_I_RE char(31)) AS  set nocount on IF @SOPCATEGORIES_I_RS IS NULL BEGIN SELECT TOP 25  SOPCATEGORIES_I, ISEQUENCENUMBER_I, KEYWORDS_I_1, KEYWORDS_I_2, KEYWORDS_I_3, KEYWORDS_I_4, KEYWORDS_I_5, KEYWORDS_I_6, DEX_ROW_ID, SOPTEXT_I FROM .SOPMSTR WHERE ( SOPCATEGORIES_I > @SOPCATEGORIES_I ) ORDER BY SOPCATEGORIES_I ASC END ELSE IF @SOPCATEGORIES_I_RS = @SOPCATEGORIES_I_RE BEGIN SELECT TOP 25  SOPCATEGORIES_I, ISEQUENCENUMBER_I, KEYWORDS_I_1, KEYWORDS_I_2, KEYWORDS_I_3, KEYWORDS_I_4, KEYWORDS_I_5, KEYWORDS_I_6, DEX_ROW_ID, SOPTEXT_I FROM .SOPMSTR WHERE SOPCATEGORIES_I = @SOPCATEGORIES_I_RS AND ( SOPCATEGORIES_I > @SOPCATEGORIES_I ) ORDER BY SOPCATEGORIES_I ASC END ELSE BEGIN SELECT TOP 25  SOPCATEGORIES_I, ISEQUENCENUMBER_I, KEYWORDS_I_1, KEYWORDS_I_2, KEYWORDS_I_3, KEYWORDS_I_4, KEYWORDS_I_5, KEYWORDS_I_6, DEX_ROW_ID, SOPTEXT_I FROM .SOPMSTR WHERE SOPCATEGORIES_I BETWEEN @SOPCATEGORIES_I_RS AND @SOPCATEGORIES_I_RE AND ( SOPCATEGORIES_I > @SOPCATEGORIES_I ) ORDER BY SOPCATEGORIES_I ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOPMSTRN_1] TO [DYNGRP]
GO
