SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY40502SI] (@BARULEID int, @TBLPHYSNM char(51), @ALIASNAME char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY40502 (BARULEID, TBLPHYSNM, ALIASNAME) VALUES ( @BARULEID, @TBLPHYSNM, @ALIASNAME) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY40502SI] TO [DYNGRP]
GO
