SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_HR2REQ01SS_3] (@COMPANYCODE_I char(7), @DIVISIONCODE_I char(7), @DEPARTMENTCODE_I char(7), @POSITIONCODE_I char(7), @REQUISITIONNUMBER_I int) AS  set nocount on SELECT TOP 1  REQUISITIONNUMBER_I, REQSTATUS_I, COMPANYCODE_I, DIVISIONCODE_I, DEPARTMENTCODE_I, POSITIONCODE_I, MANAGER_I, SUPERVISORCODE_I, STRTDATE, ENDDATE, OPENINGDATE_I, RECRUITER_I, RECRUITMENT_I, ADVERTISINGLIST_I_1, ADVERTISINGLIST_I_2, ADVERTISINGLIST_I_3, ADVERTISINGLIST_I_4, ADVERTISINGLIST_I_5, POSITIONSAVAILABLE_I, POSITIONSFILLED_I, APPLICANTSAPPLIED_I, APPSINTERVIEWED_I, ADVERTISINGCOSTS_I, RECRUITERSFEES_I, TRAVELCOSTS_I, LODGINGCOSTS_I, MOVINGEXPENSES_I, OTHERCOSTS_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .HR2REQ01 WHERE COMPANYCODE_I = @COMPANYCODE_I AND DIVISIONCODE_I = @DIVISIONCODE_I AND DEPARTMENTCODE_I = @DEPARTMENTCODE_I AND POSITIONCODE_I = @POSITIONCODE_I AND REQUISITIONNUMBER_I = @REQUISITIONNUMBER_I ORDER BY COMPANYCODE_I ASC, DIVISIONCODE_I ASC, DEPARTMENTCODE_I ASC, POSITIONCODE_I ASC, REQUISITIONNUMBER_I ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2REQ01SS_3] TO [DYNGRP]
GO
