SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_DO40100SS_1] (@CMPANYID smallint) AS  set nocount on SELECT TOP 1  CMPANYID, WINDLIVEID, WINLIVEPASSWORD, COMMERCEACCTNUM, COMMERCEORG, ECOMMORDID, ECOMMINVID, CUSTNMBR, DOCID, OCSACTIVE, PSACTIVE, PMTSERVCID, CARDNAME, VoidAVSAuthorization, VerifyAVSUsing, DEX_ROW_ID, ONLINECERTIFICATE FROM .DO40100 WHERE CMPANYID = @CMPANYID ORDER BY CMPANYID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DO40100SS_1] TO [DYNGRP]
GO
