SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_SY40505SI] (@BARULEID int, @NOTIFTYPE char(31), @NOTFCTNID char(101), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY40505 (BARULEID, NOTIFTYPE, NOTFCTNID) VALUES ( @BARULEID, @NOTIFTYPE, @NOTFCTNID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY40505SI] TO [DYNGRP]
GO
