SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME240444SS_1] (@CMPANYID smallint, @CHEKBKID char(15)) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  CMPANYID, CHEKBKID, MEEFTOPTIONS, MEEFTREMFRMT, DEX_ROW_ID FROM .ME240444 WHERE CMPANYID = @CMPANYID AND CHEKBKID = @CHEKBKID ORDER BY CMPANYID ASC, CHEKBKID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME240444SS_1] TO [DYNGRP]
GO
