SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_LKACTVTYSD] (@USERID char(15), @FORMNAME char(79), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .LKACTVTY WHERE USERID = @USERID AND FORMNAME = @FORMNAME AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .LKACTVTY WHERE USERID = @USERID AND FORMNAME = @FORMNAME SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_LKACTVTYSD] TO [DYNGRP]
GO
