SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_MC40300L_2] (@EXGTBDSC_RS char(31), @EXGTBLID_RS char(15), @EXGTBDSC_RE char(31), @EXGTBLID_RE char(15)) AS  set nocount on IF @EXGTBDSC_RS IS NULL BEGIN SELECT TOP 25  EXGTBLID, NOTEINDX, EXGTBDSC, CURNCYID, EXTBLSRC, RATEEXPR, DYSTINCR, RATEVARC, TRXDTDEF, RTCLCMTD, PRVDSLMT, DATELMTS, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40300 ORDER BY EXGTBDSC DESC, EXGTBLID DESC, DEX_ROW_ID DESC END ELSE IF @EXGTBDSC_RS = @EXGTBDSC_RE BEGIN SELECT TOP 25  EXGTBLID, NOTEINDX, EXGTBDSC, CURNCYID, EXTBLSRC, RATEEXPR, DYSTINCR, RATEVARC, TRXDTDEF, RTCLCMTD, PRVDSLMT, DATELMTS, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40300 WHERE EXGTBDSC = @EXGTBDSC_RS AND EXGTBLID BETWEEN @EXGTBLID_RS AND @EXGTBLID_RE ORDER BY EXGTBDSC DESC, EXGTBLID DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  EXGTBLID, NOTEINDX, EXGTBDSC, CURNCYID, EXTBLSRC, RATEEXPR, DYSTINCR, RATEVARC, TRXDTDEF, RTCLCMTD, PRVDSLMT, DATELMTS, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40300 WHERE EXGTBDSC BETWEEN @EXGTBDSC_RS AND @EXGTBDSC_RE AND EXGTBLID BETWEEN @EXGTBLID_RS AND @EXGTBLID_RE ORDER BY EXGTBDSC DESC, EXGTBLID DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_MC40300L_2] TO [DYNGRP]
GO
