SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 create view [dbo].[ORG10000] (  RELID,  RELSTRNG,  ENTYLVL,  ENTYNAMES_1,  ENTYNAMES_2,  ENTYNAMES_3,  ENTYNAMES_4,  ENTYDESC,  POSSTRING,  DEX_ROW_ID ) as select   RELID,  RELSTRNG,  ENTYLVL,   ENTYNAMES_1,   ENTYNAMES_2,   ENTYNAMES_3,   ENTYNAMES_4,   ENTYDESC,  CASE ENTYLVL  WHEN 1 THEN rtrim(ENTYNAMES_1)  WHEN 2 THEN rtrim(ENTYNAMES_1) + ' / ' + rtrim(ENTYNAMES_2)  WHEN 3 THEN rtrim(ENTYNAMES_1) + ' / ' + rtrim(ENTYNAMES_2) + ' / ' + rtrim(ENTYNAMES_3)  WHEN 4 THEN rtrim(ENTYNAMES_1) + ' / ' + rtrim(ENTYNAMES_2) + ' / ' + rtrim(ENTYNAMES_3) + ' / ' + rtrim(ENTYNAMES_4)  END,  DEX_ROW_ID from   ORG00101    
GO
GRANT SELECT ON  [dbo].[ORG10000] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ORG10000] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ORG10000] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ORG10000] TO [DYNGRP]
GO
