CREATE TABLE [dbo].[UPR10104]
(
[RPTNGYR] [smallint] NOT NULL,
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPCLCODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPCLBNUM] [smallint] NOT NULL,
[SPCLAMNT] [numeric] (19, 5) NOT NULL,
[W2PRINTD] [tinyint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPR10104] ADD CONSTRAINT [PKUPR10104] PRIMARY KEY NONCLUSTERED  ([RPTNGYR], [EMPLOYID], [SPCLCODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1UPR10104] ON [dbo].[UPR10104] ([RPTNGYR], [EMPLOYID], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10104].[RPTNGYR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10104].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10104].[SPCLCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10104].[SPCLBNUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[UPR10104].[SPCLAMNT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10104].[W2PRINTD]'
GO
GRANT SELECT ON  [dbo].[UPR10104] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[UPR10104] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[UPR10104] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[UPR10104] TO [DYNGRP]
GO
