CREATE TABLE [dbo].[AF10000]
(
[SEQUENCE1] [numeric] (19, 5) NOT NULL,
[PPERADSC] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PPERADAM] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AF10000] ADD CONSTRAINT [PKAF10000] PRIMARY KEY NONCLUSTERED  ([SEQUENCE1]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AF10000].[SEQUENCE1]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[AF10000].[PPERADSC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[AF10000].[PPERADAM]'
GO
GRANT SELECT ON  [dbo].[AF10000] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[AF10000] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[AF10000] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[AF10000] TO [DYNGRP]
GO
