CREATE TABLE [dbo].[MC60400]
(
[DENOMCURR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ENABLED] [tinyint] NOT NULL,
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REALGAIN] [int] NOT NULL,
[REALLOSS] [int] NOT NULL,
[PSTGDATE] [datetime] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MC60400] ADD CONSTRAINT [CK__MC60400__PSTGDAT__62458BBE] CHECK ((datepart(hour,[PSTGDATE])=(0) AND datepart(minute,[PSTGDATE])=(0) AND datepart(second,[PSTGDATE])=(0) AND datepart(millisecond,[PSTGDATE])=(0)))
GO
ALTER TABLE [dbo].[MC60400] ADD CONSTRAINT [PKMC60400] PRIMARY KEY NONCLUSTERED  ([DENOMCURR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2MC60400] ON [dbo].[MC60400] ([ENABLED], [DENOMCURR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC60400].[DENOMCURR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC60400].[ENABLED]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC60400].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC60400].[REALGAIN]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC60400].[REALLOSS]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[MC60400].[PSTGDATE]'
GO
GRANT SELECT ON  [dbo].[MC60400] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[MC60400] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[MC60400] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[MC60400] TO [DYNGRP]
GO
