CREATE TABLE [dbo].[TAIVRec]
(
[ITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCNCODE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TAIVRecReason] [char] (111) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAIVRec] ADD CONSTRAINT [PKTAIVRec] PRIMARY KEY NONCLUSTERED  ([DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1TAIVRec] ON [dbo].[TAIVRec] ([ITEMNMBR], [LOCNCODE], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[TAIVRec].[ITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[TAIVRec].[LOCNCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[TAIVRec].[TAIVRecReason]'
GO
GRANT SELECT ON  [dbo].[TAIVRec] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[TAIVRec] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[TAIVRec] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[TAIVRec] TO [DYNGRP]
GO
