CREATE TABLE [dbo].[DD10300]
(
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INDXLONG] [int] NOT NULL,
[DDArrayIndex] [smallint] NOT NULL,
[DDITEM] [smallint] NOT NULL,
[DDIndex] [int] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DD10300] ADD CONSTRAINT [PKDD10300] PRIMARY KEY NONCLUSTERED  ([INDXLONG], [EMPLOYID], [DDArrayIndex]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2DD10300] ON [dbo].[DD10300] ([EMPLOYID], [INDXLONG], [DDITEM], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD10300].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD10300].[INDXLONG]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD10300].[DDArrayIndex]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD10300].[DDITEM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD10300].[DDIndex]'
GO
GRANT SELECT ON  [dbo].[DD10300] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[DD10300] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[DD10300] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[DD10300] TO [DYNGRP]
GO
