CREATE TABLE [dbo].[MC50200]
(
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURNCYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURRNIDX] [smallint] NOT NULL,
[HSTRCLRT] [numeric] (19, 7) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MC50200] ADD CONSTRAINT [PKMC50200] PRIMARY KEY NONCLUSTERED  ([USERID], [CURNCYID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC50200].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC50200].[CURNCYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC50200].[CURRNIDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[MC50200].[HSTRCLRT]'
GO
GRANT SELECT ON  [dbo].[MC50200] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[MC50200] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[MC50200] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[MC50200] TO [DYNGRP]
GO
