CREATE TABLE [dbo].[DD30101]
(
[INDXLONG] [int] NOT NULL,
[DDITEM] [smallint] NOT NULL,
[CHEKNMBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDTRANS] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDTRANUM] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDACTNUM] [char] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDAMTDLR] [numeric] (19, 5) NOT NULL,
[DDTRACE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DD30101] ADD CONSTRAINT [PKDD30101] PRIMARY KEY NONCLUSTERED  ([INDXLONG], [DDITEM]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3DD30101] ON [dbo].[DD30101] ([DDTRANS], [INDXLONG], [DDITEM]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4DD30101] ON [dbo].[DD30101] ([EMPLOYID], [CHEKNMBR], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2DD30101] ON [dbo].[DD30101] ([EMPLOYID], [INDXLONG], [DDITEM]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD30101].[INDXLONG]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD30101].[DDITEM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[CHEKNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[DDTRANS]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[DDTRANUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[DDACTNUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[DD30101].[DDAMTDLR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD30101].[DDTRACE]'
GO
GRANT SELECT ON  [dbo].[DD30101] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[DD30101] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[DD30101] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[DD30101] TO [DYNGRP]
GO
