CREATE TABLE [dbo].[IV10202]
(
[ITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCTSEQNM] [int] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IV10202] ADD CONSTRAINT [PKIV10202] PRIMARY KEY CLUSTERED  ([ITEMNMBR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV10202].[ITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[IV10202].[RCTSEQNM]'
GO
GRANT SELECT ON  [dbo].[IV10202] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[IV10202] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[IV10202] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[IV10202] TO [DYNGRP]
GO
