CREATE TABLE [dbo].[UPR10105]
(
[RPTNGYR] [smallint] NOT NULL,
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATINTX] [numeric] (19, 5) NOT NULL,
[STATEWGS] [numeric] (19, 5) NOT NULL,
[SEQNUMBR] [int] NOT NULL,
[STATECD] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTIDNBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[W2PRINTD] [tinyint] NOT NULL,
[TXENTYCD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OTHSTDAT] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STCNTRLNUM] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPPDAT1] [char] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPPDAT2] [char] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPR10105] ADD CONSTRAINT [PKUPR10105] PRIMARY KEY NONCLUSTERED  ([RPTNGYR], [EMPLOYID], [SEQNUMBR], [STATECD]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1UPR10105] ON [dbo].[UPR10105] ([RPTNGYR], [EMPLOYID], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3UPR10105] ON [dbo].[UPR10105] ([RPTNGYR], [STATECD], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10105].[RPTNGYR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[UPR10105].[STATINTX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[UPR10105].[STATEWGS]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10105].[SEQNUMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[STATECD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[ESTIDNBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10105].[W2PRINTD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[TXENTYCD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[OTHSTDAT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[STCNTRLNUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[SUPPDAT1]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10105].[SUPPDAT2]'
GO
GRANT SELECT ON  [dbo].[UPR10105] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[UPR10105] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[UPR10105] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[UPR10105] TO [DYNGRP]
GO
