CREATE TABLE [dbo].[SVC8005]
(
[SCHEDID] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SCHEDDESC] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRVTYPE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UOMSCHDL] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVC8005] ADD CONSTRAINT [PKSVC8005] PRIMARY KEY NONCLUSTERED  ([SCHEDID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SVC8005] ON [dbo].[SVC8005] ([SCHEDDESC], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC8005].[SCHEDID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC8005].[SCHEDDESC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC8005].[SRVTYPE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC8005].[UOMSCHDL]'
GO
GRANT SELECT ON  [dbo].[SVC8005] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SVC8005] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SVC8005] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SVC8005] TO [DYNGRP]
GO
