CREATE TABLE [dbo].[UPR10106]
(
[RPTNGYR] [smallint] NOT NULL,
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQNUMBR] [int] NOT NULL,
[LOCLCODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCLWGES] [numeric] (19, 5) NOT NULL,
[LCLINTAX] [numeric] (19, 5) NOT NULL,
[W2PRINTD] [tinyint] NOT NULL,
[TAXTYPE] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPR10106] ADD CONSTRAINT [PKUPR10106] PRIMARY KEY NONCLUSTERED  ([RPTNGYR], [EMPLOYID], [SEQNUMBR], [LOCLCODE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1UPR10106] ON [dbo].[UPR10106] ([RPTNGYR], [EMPLOYID], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3UPR10106] ON [dbo].[UPR10106] ([RPTNGYR], [LOCLCODE], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10106].[RPTNGYR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10106].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10106].[SEQNUMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR10106].[LOCLCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[UPR10106].[LOCLWGES]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[UPR10106].[LCLINTAX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10106].[W2PRINTD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR10106].[TAXTYPE]'
GO
GRANT SELECT ON  [dbo].[UPR10106] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[UPR10106] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[UPR10106] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[UPR10106] TO [DYNGRP]
GO
