CREATE TABLE [dbo].[B4640704]
(
[LOCNCODE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LNITMSEQ] [int] NOT NULL,
[BSSI_DeedRestrictionID] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[B4640704] ADD CONSTRAINT [PKB4640704] PRIMARY KEY NONCLUSTERED  ([LOCNCODE], [LNITMSEQ]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2B4640704] ON [dbo].[B4640704] ([LOCNCODE], [BSSI_DeedRestrictionID], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B4640704].[LOCNCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[B4640704].[LNITMSEQ]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B4640704].[BSSI_DeedRestrictionID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[B4640704].[NOTEINDX]'
GO
GRANT SELECT ON  [dbo].[B4640704] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[B4640704] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[B4640704] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[B4640704] TO [DYNGRP]
GO
