CREATE TABLE [dbo].[B7132100]
(
[CUSTNMBR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RMDTYPAL] [smallint] NOT NULL,
[DOCNUMBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BSSI_RecogScheduleCancel] [tinyint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[B7132100] ADD CONSTRAINT [PKB7132100] PRIMARY KEY NONCLUSTERED  ([CUSTNMBR], [RMDTYPAL], [DOCNUMBR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B7132100].[CUSTNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[B7132100].[RMDTYPAL]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B7132100].[DOCNUMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[B7132100].[BSSI_RecogScheduleCancel]'
GO
GRANT SELECT ON  [dbo].[B7132100] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[B7132100] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[B7132100] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[B7132100] TO [DYNGRP]
GO
