CREATE TABLE [dbo].[B4699202]
(
[BSSI_PortfolioID] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BSSI_WingID] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LNITMSEQ] [int] NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[B4699202] ADD CONSTRAINT [PKB4699202] PRIMARY KEY CLUSTERED  ([BSSI_PortfolioID], [LNITMSEQ]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3B4699202] ON [dbo].[B4699202] ([BSSI_PortfolioID], [BSSI_WingID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2B4699202] ON [dbo].[B4699202] ([BSSI_PortfolioID], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B4699202].[BSSI_PortfolioID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B4699202].[BSSI_WingID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[B4699202].[LNITMSEQ]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[B4699202].[NOTEINDX]'
GO
GRANT SELECT ON  [dbo].[B4699202] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[B4699202] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[B4699202] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[B4699202] TO [DYNGRP]
GO
