CREATE TABLE [dbo].[HRVACA12]
(
[IDATE_I] [datetime] NOT NULL,
[EMPID_I] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STR30DUMMY_I] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRVACA12] ADD CONSTRAINT [CK__HRVACA12__IDATE___0AD3CEF0] CHECK ((datepart(hour,[IDATE_I])=(0) AND datepart(minute,[IDATE_I])=(0) AND datepart(second,[IDATE_I])=(0) AND datepart(millisecond,[IDATE_I])=(0)))
GO
ALTER TABLE [dbo].[HRVACA12] ADD CONSTRAINT [PKHRVACA12] PRIMARY KEY CLUSTERED  ([IDATE_I], [EMPID_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2HRVACA12] ON [dbo].[HRVACA12] ([EMPID_I], [IDATE_I]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[HRVACA12].[IDATE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[HRVACA12].[EMPID_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[HRVACA12].[STR30DUMMY_I]'
GO
GRANT SELECT ON  [dbo].[HRVACA12] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[HRVACA12] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[HRVACA12] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[HRVACA12] TO [DYNGRP]
GO
