CREATE TABLE [dbo].[DD00200]
(
[EMPLOYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INDXLONG] [int] NOT NULL,
[INACTIVE] [tinyint] NOT NULL,
[DEDNMTHD] [smallint] NOT NULL,
[DEDUCTON] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDPRE] [tinyint] NOT NULL,
[DDPRECNT] [smallint] NOT NULL,
[DDPCT] [smallint] NOT NULL,
[DDAMTDLR] [numeric] (19, 5) NOT NULL,
[DDACTNUM] [char] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDTRANUM] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDTRANS] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DD00200] ADD CONSTRAINT [PKDD00200] PRIMARY KEY NONCLUSTERED  ([EMPLOYID], [INDXLONG]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4DD00200] ON [dbo].[DD00200] ([DDPRE], [EMPLOYID], [INDXLONG]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2DD00200] ON [dbo].[DD00200] ([DDTRANS], [EMPLOYID], [INDXLONG]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3DD00200] ON [dbo].[DD00200] ([DEDNMTHD], [EMPLOYID], [INDXLONG]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD00200].[EMPLOYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[INDXLONG]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[INACTIVE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[DEDNMTHD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD00200].[DEDUCTON]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[DDPRE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[DDPRECNT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[DD00200].[DDPCT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[DD00200].[DDAMTDLR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD00200].[DDACTNUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD00200].[DDTRANUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[DD00200].[DDTRANS]'
GO
GRANT SELECT ON  [dbo].[DD00200] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[DD00200] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[DD00200] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[DD00200] TO [DYNGRP]
GO
