CREATE TABLE [dbo].[MC40500]
(
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SERIES] [smallint] NOT NULL,
[TRXSOURC] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VIEWTYPE] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MC40500] ADD CONSTRAINT [PKMC40500] PRIMARY KEY NONCLUSTERED  ([USERID], [SERIES], [TRXSOURC]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC40500].[USERID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC40500].[SERIES]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC40500].[TRXSOURC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC40500].[VIEWTYPE]'
GO
GRANT SELECT ON  [dbo].[MC40500] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[MC40500] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[MC40500] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[MC40500] TO [DYNGRP]
GO
