CREATE TABLE [dbo].[CAM40004]
(
[REFRENCE] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOURCDOC] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAMAccountType] [smallint] NOT NULL,
[BCHCOMNT] [char] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BACHNUMB] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAM40004] ADD CONSTRAINT [PKCAM40004] PRIMARY KEY NONCLUSTERED  ([CAMAccountType]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[CAM40004].[REFRENCE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[CAM40004].[SOURCDOC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[CAM40004].[CAMAccountType]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[CAM40004].[BCHCOMNT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[CAM40004].[BACHNUMB]'
GO
GRANT SELECT ON  [dbo].[CAM40004] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[CAM40004] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[CAM40004] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[CAM40004] TO [DYNGRP]
GO
