CREATE TABLE [dbo].[SOP60300]
(
[ITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTNMBR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTITEMDESC] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTITEMSHORNAME] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTITEMGENERICDESC] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEF1] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEF2] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USRDEF03] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USRDEF04] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USRDEF05] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEFKEY1] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEFKEY2] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEFKEY3] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEFKEY4] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SOP60300] ADD CONSTRAINT [PKSOP60300] PRIMARY KEY NONCLUSTERED  ([ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3SOP60300] ON [dbo].[SOP60300] ([CUSTITEMDESC], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SOP60300] ON [dbo].[SOP60300] ([CUSTITEMNMBR], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK10SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [CUSTITEMDESC], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK9SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [CUSTITEMNMBR], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK8SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK11SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [USERDEFKEY1], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK12SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [USERDEFKEY2], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK13SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [USERDEFKEY3], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK14SOP60300] ON [dbo].[SOP60300] ([CUSTNMBR], [USERDEFKEY4], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4SOP60300] ON [dbo].[SOP60300] ([USERDEFKEY1], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK5SOP60300] ON [dbo].[SOP60300] ([USERDEFKEY2], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK6SOP60300] ON [dbo].[SOP60300] ([USERDEFKEY3], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK7SOP60300] ON [dbo].[SOP60300] ([USERDEFKEY4], [ITEMNMBR], [CUSTNMBR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[ITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[CUSTNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[CUSTITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[CUSTITEMDESC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[CUSTITEMSHORNAME]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[CUSTITEMGENERICDESC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEF1]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEF2]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USRDEF03]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USRDEF04]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USRDEF05]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEFKEY1]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEFKEY2]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEFKEY3]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60300].[USERDEFKEY4]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[SOP60300].[NOTEINDX]'
GO
GRANT SELECT ON  [dbo].[SOP60300] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SOP60300] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SOP60300] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SOP60300] TO [DYNGRP]
GO
GRANT SELECT ON  [dbo].[SOP60300] TO [RAPIDGRP]
GO
GRANT INSERT ON  [dbo].[SOP60300] TO [RAPIDGRP]
GO
GRANT DELETE ON  [dbo].[SOP60300] TO [RAPIDGRP]
GO
GRANT UPDATE ON  [dbo].[SOP60300] TO [RAPIDGRP]
GO
