CREATE TABLE [dbo].[HRSAX022]
(
[TABLE_I] [smallint] NOT NULL,
[DSCRIPTN] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMPENSATIONPERIOD_I] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRSAX022] ADD CONSTRAINT [PKHRSAX022] PRIMARY KEY CLUSTERED  ([TABLE_I]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRSAX022].[TABLE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[HRSAX022].[DSCRIPTN]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[HRSAX022].[COMPENSATIONPERIOD_I]'
GO
GRANT SELECT ON  [dbo].[HRSAX022] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[HRSAX022] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[HRSAX022] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[HRSAX022] TO [DYNGRP]
GO
