CREATE TABLE [dbo].[ORA25230]
(
[EMPID_I] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQORDER_I] [smallint] NOT NULL,
[ORCOMPLETEDCB_I] [tinyint] NOT NULL,
[ORIENTATIONITEM_I] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSONRESPONSIBLE_I] [char] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EVENTSTARTDATE_I] [datetime] NOT NULL,
[EVENTSTARTTIME_I] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EVENTENDDATE_I] [datetime] NOT NULL,
[EVENTENDTIME_I] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORA25230] ADD CONSTRAINT [CK__ORA25230__EVENTE__1DE6A364] CHECK ((datepart(hour,[EVENTENDDATE_I])=(0) AND datepart(minute,[EVENTENDDATE_I])=(0) AND datepart(second,[EVENTENDDATE_I])=(0) AND datepart(millisecond,[EVENTENDDATE_I])=(0)))
GO
ALTER TABLE [dbo].[ORA25230] ADD CONSTRAINT [CK__ORA25230__EVENTS__1EDAC79D] CHECK ((datepart(hour,[EVENTSTARTDATE_I])=(0) AND datepart(minute,[EVENTSTARTDATE_I])=(0) AND datepart(second,[EVENTSTARTDATE_I])=(0) AND datepart(millisecond,[EVENTSTARTDATE_I])=(0)))
GO
ALTER TABLE [dbo].[ORA25230] ADD CONSTRAINT [PKORA25230] PRIMARY KEY CLUSTERED  ([EMPID_I], [SEQORDER_I]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2ORA25230] ON [dbo].[ORA25230] ([EMPID_I], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[ORA25230].[EMPID_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[ORA25230].[SEQORDER_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[ORA25230].[ORCOMPLETEDCB_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[ORA25230].[ORIENTATIONITEM_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[ORA25230].[PERSONRESPONSIBLE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[ORA25230].[EVENTSTARTDATE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[ORA25230].[EVENTSTARTTIME_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[ORA25230].[EVENTENDDATE_I]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[ORA25230].[EVENTENDTIME_I]'
GO
GRANT SELECT ON  [dbo].[ORA25230] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[ORA25230] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[ORA25230] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[ORA25230] TO [DYNGRP]
GO
