CREATE TABLE [dbo].[B7100702]
(
[BSSI_EventID] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LNITMSEQ] [int] NOT NULL,
[BSSI_Description] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[B7100702] ADD CONSTRAINT [PKB7100702] PRIMARY KEY NONCLUSTERED  ([LNITMSEQ]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2B7100702] ON [dbo].[B7100702] ([BSSI_EventID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B7100702].[BSSI_EventID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[B7100702].[LNITMSEQ]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[B7100702].[BSSI_Description]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[B7100702].[NOTEINDX]'
GO
GRANT SELECT ON  [dbo].[B7100702] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[B7100702] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[B7100702] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[B7100702] TO [DYNGRP]
GO
