CREATE TABLE [dbo].[SY05500]
(
[TBLPHYSNM] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOCCODE] [char] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRODTCOD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY05500] ADD CONSTRAINT [PKSY05500] PRIMARY KEY NONCLUSTERED  ([TBLPHYSNM], [PRODTCOD], [USERID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1SY05500] ON [dbo].[SY05500] ([TBLPHYSNM], [DOCCODE], [PRODTCOD], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY05500].[TBLPHYSNM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY05500].[DOCCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY05500].[PRODTCOD]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SY05500].[USERID]'
GO
GRANT SELECT ON  [dbo].[SY05500] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY05500] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY05500] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY05500] TO [DYNGRP]
GO
