CREATE TABLE [dbo].[UPR40105]
(
[TEN95LINE] [smallint] NOT NULL,
[TEN95LINECODE] [smallint] NOT NULL,
[TEN95LINECODETEXT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TEN95LINEDESCRIPTION] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPR40105] ADD CONSTRAINT [PKUPR40105] PRIMARY KEY CLUSTERED  ([TEN95LINE], [TEN95LINECODE]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR40105].[TEN95LINE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[UPR40105].[TEN95LINECODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR40105].[TEN95LINECODETEXT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[UPR40105].[TEN95LINEDESCRIPTION]'
GO
GRANT SELECT ON  [dbo].[UPR40105] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[UPR40105] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[UPR40105] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[UPR40105] TO [DYNGRP]
GO
