CREATE TABLE [dbo].[IV00108]
(
[ITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURNCYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRCLEVEL] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UOFM] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TOQTY] [numeric] (19, 5) NOT NULL,
[FROMQTY] [numeric] (19, 5) NOT NULL,
[UOMPRICE] [numeric] (19, 5) NOT NULL,
[QTYBSUOM] [numeric] (19, 5) NOT NULL,
[DEX_ROW_TS] [datetime] NOT NULL CONSTRAINT [DF__IV00108__DEX_ROW__5B500C1A] DEFAULT (getutcdate()),
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[SC_IV00108_Create_CRM_PRICELIST_CH]
ON  [dbo].[IV00108]
FOR INSERT
AS 
BEGIN
    SET NOCOUNT ON
    
    DECLARE @TableName char(50)
    DECLARE @MapId char(255)
	DECLARE @DEX_ROW_ID int

	SELECT @TableName = 'IV00108'
    SELECT @MapId = 'CRM_PRICELIST_CH'

	DECLARE TRIGGER_CURSOR CURSOR FOR 
	SELECT DEX_ROW_ID FROM INSERTED

	OPEN TRIGGER_CURSOR

	FETCH NEXT FROM TRIGGER_CURSOR 
	INTO @DEX_ROW_ID
    WHILE @@FETCH_STATUS = 0
	    BEGIN
            IF EXISTS(SELECT * FROM SC_IV00108_Track where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0)
            BEGIN
                UPDATE SC_IV00108_Track SET [Action] = 'CR', DateCreated = GetDate() where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0
            END
            ELSE
            BEGIN                              
                INSERT SC_IV00108_Track
			    SELECT @MapId,@DEX_ROW_ID,0,GetDate(),'1900-01-01 00:00:00.000','CR',CURNCYID as Index1,ITEMNMBR as Index2,PRCLEVEL as Index3,TOQTY as Index4,UOFM as Index5,'' as Index6,'' as Index7,'' as Index8,'' as Index9,'' as Index10 FROM INSERTED WHERE DEX_ROW_ID = @DEX_ROW_ID
            END			
                        		                               
		    FETCH NEXT FROM TRIGGER_CURSOR 
		    INTO @DEX_ROW_ID
        END 
	    CLOSE TRIGGER_CURSOR
	    DEALLOCATE TRIGGER_CURSOR
    END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[SC_IV00108_Delete_CRM_PRICELIST_CH]
ON  [dbo].[IV00108]
FOR DELETE
AS 
BEGIN
    SET NOCOUNT ON
    
    DECLARE @TableName char(50)
    DECLARE @MapId char(255)
	DECLARE @DEX_ROW_ID int

	SELECT @TableName = 'IV00108'
    SELECT @MapId = 'CRM_PRICELIST_CH'

	DECLARE TRIGGER_CURSOR CURSOR FOR 
	SELECT DEX_ROW_ID FROM DELETED

	OPEN TRIGGER_CURSOR

	FETCH NEXT FROM TRIGGER_CURSOR 
	INTO @DEX_ROW_ID
    WHILE @@FETCH_STATUS = 0
	    BEGIN
            IF EXISTS(SELECT * FROM SC_IV00108_Track where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0)
            BEGIN
                UPDATE SC_IV00108_Track SET [Action] = 'DL', DateCreated = GetDate() where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0
            END
            ELSE
            BEGIN                              
                INSERT SC_IV00108_Track
			    SELECT @MapId,@DEX_ROW_ID,0,GetDate(),'1900-01-01 00:00:00.000','DL',CURNCYID as Index1,ITEMNMBR as Index2,PRCLEVEL as Index3,TOQTY as Index4,UOFM as Index5,'' as Index6,'' as Index7,'' as Index8,'' as Index9,'' as Index10 FROM DELETED WHERE DEX_ROW_ID = @DEX_ROW_ID
            END			
                        		                               
		    FETCH NEXT FROM TRIGGER_CURSOR 
		    INTO @DEX_ROW_ID
        END 
	    CLOSE TRIGGER_CURSOR
	    DEALLOCATE TRIGGER_CURSOR
    END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[SC_IV00108_Update_CRM_PRICELIST_CH]
ON  [dbo].[IV00108]
FOR UPDATE
AS 
BEGIN
    SET NOCOUNT ON
    
    DECLARE @TableName char(50)
    DECLARE @MapId char(255)
	DECLARE @DEX_ROW_ID int

	SELECT @TableName = 'IV00108'
    SELECT @MapId = 'CRM_PRICELIST_CH'

	DECLARE TRIGGER_CURSOR CURSOR FOR 
	SELECT DEX_ROW_ID FROM INSERTED

	OPEN TRIGGER_CURSOR

	FETCH NEXT FROM TRIGGER_CURSOR 
	INTO @DEX_ROW_ID
    WHILE @@FETCH_STATUS = 0
	    BEGIN
            IF EXISTS(SELECT * FROM SC_IV00108_Track where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0)
            BEGIN
                UPDATE SC_IV00108_Track SET [Action] = 'UP', DateCreated = GetDate() where DEX_ROW_ID = @DEX_ROW_ID and MapId = @MapId and Processed = 0
            END
            ELSE
            BEGIN                              
                INSERT SC_IV00108_Track
			    SELECT @MapId,@DEX_ROW_ID,0,GetDate(),'1900-01-01 00:00:00.000','UP',CURNCYID as Index1,ITEMNMBR as Index2,PRCLEVEL as Index3,TOQTY as Index4,UOFM as Index5,'' as Index6,'' as Index7,'' as Index8,'' as Index9,'' as Index10 FROM INSERTED WHERE DEX_ROW_ID = @DEX_ROW_ID
            END			
                        		                               
		    FETCH NEXT FROM TRIGGER_CURSOR 
		    INTO @DEX_ROW_ID
        END 
	    CLOSE TRIGGER_CURSOR
	    DEALLOCATE TRIGGER_CURSOR
    END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE TRIGGER [dbo].[zDT_IV00108C] ON [dbo].[IV00108] AFTER INSERT AS SET NOCOUNT ON BEGIN   UPDATE [dbo].[IV40800] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV40800], INSERTED WHERE [IV40800].[PRCLEVEL] = [INSERTED].[PRCLEVEL]   UPDATE [dbo].[IV00107] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV00107], INSERTED WHERE [IV00107].[ITEMNMBR] = [INSERTED].[ITEMNMBR] AND [IV00107].[CURNCYID] = [INSERTED].[CURNCYID] AND [IV00107].[PRCLEVEL] = [INSERTED].[PRCLEVEL] AND [IV00107].[UOFM] = [INSERTED].[UOFM] END SET NOCOUNT OFF    
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE TRIGGER [dbo].[zDT_IV00108D] ON [dbo].[IV00108] AFTER DELETE AS SET NOCOUNT ON BEGIN   UPDATE [dbo].[IV40800] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV40800], DELETED WHERE [IV40800].[PRCLEVEL] = [DELETED].[PRCLEVEL]   UPDATE [dbo].[IV00107] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV00107], DELETED WHERE [IV00107].[ITEMNMBR] = [DELETED].[ITEMNMBR] AND [IV00107].[CURNCYID] = [DELETED].[CURNCYID] AND [IV00107].[PRCLEVEL] = [DELETED].[PRCLEVEL] AND [IV00107].[UOFM] = [DELETED].[UOFM] END SET NOCOUNT OFF    
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE TRIGGER [dbo].[zDT_IV00108U] ON [dbo].[IV00108] AFTER UPDATE AS SET NOCOUNT ON BEGIN   UPDATE [dbo].[IV00108] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV00108], INSERTED WHERE [IV00108].[ITEMNMBR] = [INSERTED].[ITEMNMBR] AND [IV00108].[CURNCYID] = [INSERTED].[CURNCYID] AND [IV00108].[PRCLEVEL] = [INSERTED].[PRCLEVEL] AND [IV00108].[UOFM] = [INSERTED].[UOFM] AND [IV00108].[TOQTY] = [INSERTED].[TOQTY]   UPDATE [dbo].[IV00107] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV00107], INSERTED WHERE [IV00107].[ITEMNMBR] = [INSERTED].[ITEMNMBR] AND [IV00107].[CURNCYID] = [INSERTED].[CURNCYID] AND [IV00107].[PRCLEVEL] = [INSERTED].[PRCLEVEL] AND [IV00107].[UOFM] = [INSERTED].[UOFM]  UPDATE [dbo].[IV40800] SET DEX_ROW_TS = GETUTCDATE() FROM [dbo].[IV40800], INSERTED WHERE [IV40800].[PRCLEVEL] = [INSERTED].[PRCLEVEL]   END SET NOCOUNT OFF    
GO
ALTER TABLE [dbo].[IV00108] ADD CONSTRAINT [PKIV00108] PRIMARY KEY NONCLUSTERED  ([ITEMNMBR], [CURNCYID], [PRCLEVEL], [UOFM], [TOQTY]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2IV00108] ON [dbo].[IV00108] ([ITEMNMBR], [CURNCYID], [PRCLEVEL], [QTYBSUOM], [UOFM], [TOQTY]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV00108].[ITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV00108].[CURNCYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV00108].[PRCLEVEL]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV00108].[UOFM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[IV00108].[TOQTY]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[IV00108].[FROMQTY]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[IV00108].[UOMPRICE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[IV00108].[QTYBSUOM]'
GO
GRANT SELECT ON  [dbo].[IV00108] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[IV00108] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[IV00108] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[IV00108] TO [DYNGRP]
GO
GRANT SELECT ON  [dbo].[IV00108] TO [RAPIDGRP]
GO
GRANT INSERT ON  [dbo].[IV00108] TO [RAPIDGRP]
GO
GRANT DELETE ON  [dbo].[IV00108] TO [RAPIDGRP]
GO
GRANT UPDATE ON  [dbo].[IV00108] TO [RAPIDGRP]
GO
