CREATE TABLE [dbo].[GL50505]
(
[TRXDATE] [datetime] NOT NULL,
[JRNENTRY] [int] NOT NULL,
[ORTRXSRC] [char] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORCTRNUM] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTINDX] [int] NOT NULL,
[DEBITAMT] [numeric] (19, 5) NOT NULL,
[CRDTAMNT] [numeric] (19, 5) NOT NULL,
[ACCTAMNT] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GL50505] ADD CONSTRAINT [CK__GL50505__TRXDATE__4EDDB18F] CHECK ((datepart(hour,[TRXDATE])=(0) AND datepart(minute,[TRXDATE])=(0) AND datepart(second,[TRXDATE])=(0) AND datepart(millisecond,[TRXDATE])=(0)))
GO
ALTER TABLE [dbo].[GL50505] ADD CONSTRAINT [PKGL50505] PRIMARY KEY NONCLUSTERED  ([DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [CL1GL50505] ON [dbo].[GL50505] ([TRXDATE], [JRNENTRY], [ACTINDX], [DEBITAMT], [CRDTAMNT]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK1GL50505] ON [dbo].[GL50505] ([TRXDATE], [JRNENTRY], [ACTINDX], [DEBITAMT], [CRDTAMNT], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[GL50505].[TRXDATE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[GL50505].[JRNENTRY]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[GL50505].[ORTRXSRC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[GL50505].[ORCTRNUM]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[GL50505].[ACTINDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[GL50505].[DEBITAMT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[GL50505].[CRDTAMNT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[GL50505].[ACCTAMNT]'
GO
GRANT SELECT ON  [dbo].[GL50505] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[GL50505] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[GL50505] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[GL50505] TO [DYNGRP]
GO
