CREATE TABLE [dbo].[MC00201]
(
[CURNCYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURRNIDX] [smallint] NOT NULL,
[ACTINDX] [int] NOT NULL,
[OPENYEAR] [smallint] NOT NULL,
[PERIODID] [smallint] NOT NULL,
[Ledger_ID] [smallint] NOT NULL,
[FUNCTAMT] [numeric] (19, 5) NOT NULL,
[ORIGAMT] [numeric] (19, 5) NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MC00201] ADD CONSTRAINT [PKMC00201] PRIMARY KEY NONCLUSTERED  ([ACTINDX], [OPENYEAR], [PERIODID], [Ledger_ID], [CURNCYID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2MC00201] ON [dbo].[MC00201] ([ACTINDX], [OPENYEAR], [CURNCYID], [Ledger_ID], [PERIODID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3MC00201] ON [dbo].[MC00201] ([CURNCYID], [ACTINDX], [PERIODID], [Ledger_ID], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4MC00201] ON [dbo].[MC00201] ([OPENYEAR], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[MC00201].[CURNCYID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC00201].[CURRNIDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC00201].[ACTINDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC00201].[OPENYEAR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC00201].[PERIODID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[MC00201].[Ledger_ID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[MC00201].[FUNCTAMT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[MC00201].[ORIGAMT]'
GO
GRANT SELECT ON  [dbo].[MC00201] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[MC00201] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[MC00201] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[MC00201] TO [DYNGRP]
GO
