CREATE TABLE [dbo].[SOP60200]
(
[INSTRUCTIONID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTNMBR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADRSCODE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ITEMNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQNUMBR] [int] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SOP60200] ADD CONSTRAINT [PKSOP60200] PRIMARY KEY NONCLUSTERED  ([INSTRUCTIONID], [CUSTNMBR], [ADRSCODE], [ITEMNMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK5SOP60200] ON [dbo].[SOP60200] ([ADRSCODE], [ITEMNMBR], [CUSTNMBR], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SOP60200] ON [dbo].[SOP60200] ([CUSTNMBR], [ADRSCODE], [ITEMNMBR], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3SOP60200] ON [dbo].[SOP60200] ([INSTRUCTIONID], [SEQNUMBR], [DEX_ROW_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK4SOP60200] ON [dbo].[SOP60200] ([ITEMNMBR], [CUSTNMBR], [ADRSCODE], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60200].[INSTRUCTIONID]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60200].[CUSTNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60200].[ADRSCODE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SOP60200].[ITEMNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[SOP60200].[SEQNUMBR]'
GO
GRANT SELECT ON  [dbo].[SOP60200] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SOP60200] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SOP60200] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SOP60200] TO [DYNGRP]
GO
