CREATE TABLE [dbo].[SY03900]
(
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[DATE1] [datetime] NOT NULL,
[TIME1] [datetime] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1),
[TXTFIELD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SY03900] ADD CONSTRAINT [CK__SY03900__TIME1__524F1B17] CHECK ((datepart(day,[TIME1])=(1) AND datepart(month,[TIME1])=(1) AND datepart(year,[TIME1])=(1900)))
GO
ALTER TABLE [dbo].[SY03900] ADD CONSTRAINT [CK__SY03900__DATE1__515AF6DE] CHECK ((datepart(hour,[DATE1])=(0) AND datepart(minute,[DATE1])=(0) AND datepart(second,[DATE1])=(0) AND datepart(millisecond,[DATE1])=(0)))
GO
ALTER TABLE [dbo].[SY03900] ADD CONSTRAINT [PKSY03900] PRIMARY KEY NONCLUSTERED  ([NOTEINDX]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[SY03900].[NOTEINDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[SY03900].[DATE1]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[SY03900].[TIME1]'
GO
GRANT SELECT ON  [dbo].[SY03900] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SY03900] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SY03900] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SY03900] TO [DYNGRP]
GO
GRANT SELECT ON  [dbo].[SY03900] TO [RAPIDGRP]
GO
GRANT INSERT ON  [dbo].[SY03900] TO [RAPIDGRP]
GO
GRANT DELETE ON  [dbo].[SY03900] TO [RAPIDGRP]
GO
GRANT UPDATE ON  [dbo].[SY03900] TO [RAPIDGRP]
GO
