CREATE TABLE [dbo].[SVC00913]
(
[SRVSTAT] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STSDESCR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SVC00913] ADD CONSTRAINT [PKSVC00913] PRIMARY KEY CLUSTERED  ([SRVSTAT]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2SVC00913] ON [dbo].[SVC00913] ([STSDESCR], [DEX_ROW_ID]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC00913].[SRVSTAT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[SVC00913].[STSDESCR]'
GO
GRANT SELECT ON  [dbo].[SVC00913] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[SVC00913] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[SVC00913] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[SVC00913] TO [DYNGRP]
GO
