CREATE TABLE [dbo].[IV30200]
(
[TRXSORCE] [char] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IVDOCTYP] [smallint] NOT NULL,
[DOCNUMBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOCDATE] [datetime] NOT NULL,
[BCHSOURC] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BACHNUMB] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[GLPOSTDT] [datetime] NOT NULL,
[SRCRFRNCNMBR] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOURCEINDICATOR] [smallint] NOT NULL,
[DEX_ROW_TS] [datetime] NOT NULL CONSTRAINT [DF__IV30200__DEX_ROW__55422D09] DEFAULT (getutcdate()),
[DEX_ROW_ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE TRIGGER [dbo].[zDT_IV30200U] ON [dbo].[IV30200] AFTER UPDATE AS  set nocount on BEGIN UPDATE dbo.IV30200 SET DEX_ROW_TS = GETUTCDATE() FROM dbo.IV30200, inserted WHERE IV30200.TRXSORCE = inserted.TRXSORCE AND IV30200.IVDOCTYP = inserted.IVDOCTYP AND IV30200.DOCNUMBR = inserted.DOCNUMBR END set nocount off    
GO
ALTER TABLE [dbo].[IV30200] ADD CONSTRAINT [CK__IV30200__DOCDATE__6497E884] CHECK ((datepart(hour,[DOCDATE])=(0) AND datepart(minute,[DOCDATE])=(0) AND datepart(second,[DOCDATE])=(0) AND datepart(millisecond,[DOCDATE])=(0)))
GO
ALTER TABLE [dbo].[IV30200] ADD CONSTRAINT [CK__IV30200__GLPOSTD__658C0CBD] CHECK ((datepart(hour,[GLPOSTDT])=(0) AND datepart(minute,[GLPOSTDT])=(0) AND datepart(second,[GLPOSTDT])=(0) AND datepart(millisecond,[GLPOSTDT])=(0)))
GO
ALTER TABLE [dbo].[IV30200] ADD CONSTRAINT [PKIV30200] PRIMARY KEY NONCLUSTERED  ([TRXSORCE], [IVDOCTYP], [DOCNUMBR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK2IV30200] ON [dbo].[IV30200] ([DOCNUMBR], [IVDOCTYP]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [AK3IV30200] ON [dbo].[IV30200] ([IVDOCTYP], [DOCNUMBR]) ON [PRIMARY]
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV30200].[TRXSORCE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[IV30200].[IVDOCTYP]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV30200].[DOCNUMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[IV30200].[DOCDATE]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV30200].[BCHSOURC]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV30200].[BACHNUMB]'
GO
EXEC sp_bindefault N'[dbo].[GPS_MONEY]', N'[dbo].[IV30200].[NOTEINDX]'
GO
EXEC sp_bindefault N'[dbo].[GPS_DATE]', N'[dbo].[IV30200].[GLPOSTDT]'
GO
EXEC sp_bindefault N'[dbo].[GPS_CHAR]', N'[dbo].[IV30200].[SRCRFRNCNMBR]'
GO
EXEC sp_bindefault N'[dbo].[GPS_INT]', N'[dbo].[IV30200].[SOURCEINDICATOR]'
GO
GRANT SELECT ON  [dbo].[IV30200] TO [DYNGRP]
GO
GRANT INSERT ON  [dbo].[IV30200] TO [DYNGRP]
GO
GRANT DELETE ON  [dbo].[IV30200] TO [DYNGRP]
GO
GRANT UPDATE ON  [dbo].[IV30200] TO [DYNGRP]
GO
