SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100810L_1] (@ITMCLSCD_RS char(11), @ITMCLSCD_RE char(11)) AS /* 12.00.0270.000 */ set nocount on IF @ITMCLSCD_RS IS NULL BEGIN SELECT TOP 25  ITMCLSCD, BSSI_Deferrable, BSSI_Offering_Type_ID, BSSI_Default_Order_TypeS, BSSI_Default_Revenue_Sou, BSSI_Recog_TemplateID, BSSI_Default_Order_TypeP, BSSI_Default_Expense_Sou, BSSI_EBTemplateID, BSSI_DefaultDefStartDt1, DEX_ROW_ID FROM .B7100810 ORDER BY ITMCLSCD DESC END ELSE IF @ITMCLSCD_RS = @ITMCLSCD_RE BEGIN SELECT TOP 25  ITMCLSCD, BSSI_Deferrable, BSSI_Offering_Type_ID, BSSI_Default_Order_TypeS, BSSI_Default_Revenue_Sou, BSSI_Recog_TemplateID, BSSI_Default_Order_TypeP, BSSI_Default_Expense_Sou, BSSI_EBTemplateID, BSSI_DefaultDefStartDt1, DEX_ROW_ID FROM .B7100810 WHERE ITMCLSCD = @ITMCLSCD_RS ORDER BY ITMCLSCD DESC END ELSE BEGIN SELECT TOP 25  ITMCLSCD, BSSI_Deferrable, BSSI_Offering_Type_ID, BSSI_Default_Order_TypeS, BSSI_Default_Revenue_Sou, BSSI_Recog_TemplateID, BSSI_Default_Order_TypeP, BSSI_Default_Expense_Sou, BSSI_EBTemplateID, BSSI_DefaultDefStartDt1, DEX_ROW_ID FROM .B7100810 WHERE ITMCLSCD BETWEEN @ITMCLSCD_RS AND @ITMCLSCD_RE ORDER BY ITMCLSCD DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100810L_1] TO [DYNGRP]
GO
