SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_palbrdtyN_1] (@BS int, @DSCRIPTN char(31), @DSCRIPTN_RS char(31), @DSCRIPTN_RE char(31)) AS  set nocount on IF @DSCRIPTN_RS IS NULL BEGIN SELECT TOP 25  IntegerValue, DSCRIPTN, DEX_ROW_ID FROM .palbrdty WHERE ( DSCRIPTN > @DSCRIPTN ) ORDER BY DSCRIPTN ASC END ELSE IF @DSCRIPTN_RS = @DSCRIPTN_RE BEGIN SELECT TOP 25  IntegerValue, DSCRIPTN, DEX_ROW_ID FROM .palbrdty WHERE DSCRIPTN = @DSCRIPTN_RS AND ( DSCRIPTN > @DSCRIPTN ) ORDER BY DSCRIPTN ASC END ELSE BEGIN SELECT TOP 25  IntegerValue, DSCRIPTN, DEX_ROW_ID FROM .palbrdty WHERE DSCRIPTN BETWEEN @DSCRIPTN_RS AND @DSCRIPTN_RE AND ( DSCRIPTN > @DSCRIPTN ) ORDER BY DSCRIPTN ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_palbrdtyN_1] TO [DYNGRP]
GO
