SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HR2BEN13SS_1] (@BENEFIT char(7), @AGERANGE_I smallint) AS  set nocount on SELECT TOP 1  BENEFIT, AGERANGE_I, PREMIUMEMPLOYEE_I, PREMIUMSMOKER_I, PREMIUMSPOUSE_I, PREMSMOKESPOUSE_I, DEX_ROW_ID FROM .HR2BEN13 WHERE BENEFIT = @BENEFIT AND AGERANGE_I = @AGERANGE_I ORDER BY BENEFIT ASC, AGERANGE_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2BEN13SS_1] TO [DYNGRP]
GO
