SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CFMTEMPSS_1] (@CHEKBKID char(15)) AS  set nocount on SELECT TOP 1  CHEKBKID, MKTOPROC, CFM_Exchange_Rate, CFM_Calc_Method, DEX_ROW_ID FROM .CFMTEMP WHERE CHEKBKID = @CHEKBKID ORDER BY CHEKBKID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CFMTEMPSS_1] TO [DYNGRP]
GO
