SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG00317L_1] (@USERID_RS char(15), @aaTrxDimCodeID_RS int, @USERID_RE char(15), @aaTrxDimCodeID_RE int) AS  set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  USERID, aaTrxDimCodeID, DEX_ROW_ID, aaUDFCodeString FROM .AAG00317 ORDER BY USERID DESC, aaTrxDimCodeID DESC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  USERID, aaTrxDimCodeID, DEX_ROW_ID, aaUDFCodeString FROM .AAG00317 WHERE USERID = @USERID_RS AND aaTrxDimCodeID BETWEEN @aaTrxDimCodeID_RS AND @aaTrxDimCodeID_RE ORDER BY USERID DESC, aaTrxDimCodeID DESC END ELSE BEGIN SELECT TOP 25  USERID, aaTrxDimCodeID, DEX_ROW_ID, aaUDFCodeString FROM .AAG00317 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE AND aaTrxDimCodeID BETWEEN @aaTrxDimCodeID_RS AND @aaTrxDimCodeID_RE ORDER BY USERID DESC, aaTrxDimCodeID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG00317L_1] TO [DYNGRP]
GO
