SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MS273532SS_1] (@MSO_Doc_Number char(21), @SEQNUMBR int) AS /* 12.00.0311.000 */ set nocount on SELECT TOP 1  MSO_Doc_Number, SEQNUMBR, MSO_EngineGUID, MSO_Tender, CUSTNMBR, MSO_CardName, MSO_CardNumberPABP, MSO_CardExpDate, MSO_ABA, MSO_ACCT, CRCRDAMT, PRCNTOFTTL, DEX_ROW_ID FROM .MS273532 WHERE MSO_Doc_Number = @MSO_Doc_Number AND SEQNUMBR = @SEQNUMBR ORDER BY MSO_Doc_Number ASC, SEQNUMBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MS273532SS_1] TO [DYNGRP]
GO
