SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_SE000401SS_6] (@ACTNUMBR_1 char(5), @ACTNUMBR_2 char(5), @ACTNUMBR_3 char(3), @ACTNUMBR_4 char(3)) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  USERID, ACTNUMBR_1, ACTNUMBR_2, ACTNUMBR_3, ACTNUMBR_4, PERIODID, SESORNO1, SESORT1, SE_Zero_NM, SE_Zero_PB, NETAMNT, PERDBLNC, OPENYEAR, CURRNIDX, SEBUDDET, ACTINDX, ACTNUMST, DEX_ROW_ID FROM .SE000401 WHERE ACTNUMBR_1 = @ACTNUMBR_1 AND ACTNUMBR_2 = @ACTNUMBR_2 AND ACTNUMBR_3 = @ACTNUMBR_3 AND ACTNUMBR_4 = @ACTNUMBR_4 ORDER BY ACTNUMBR_1 ASC, ACTNUMBR_2 ASC, ACTNUMBR_3 ASC, ACTNUMBR_4 ASC, DEX_ROW_ID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_SE000401SS_6] TO [DYNGRP]
GO
