SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR42301SI] (@ASSIGNMENTCODE char(15), @ASSIGNMENTTYPE smallint, @TIMECARDCODE char(7), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .UPR42301 (ASSIGNMENTCODE, ASSIGNMENTTYPE, TIMECARDCODE) VALUES ( @ASSIGNMENTCODE, @ASSIGNMENTTYPE, @TIMECARDCODE) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR42301SI] TO [DYNGRP]
GO
