SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06115SD] (@USERID char(15), @WORECTYPE smallint, @MKDTOPST tinyint, @WORKORDNUM char(11), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .SVC06115 WHERE USERID = @USERID AND WORECTYPE = @WORECTYPE AND MKDTOPST = @MKDTOPST AND WORKORDNUM = @WORKORDNUM AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .SVC06115 WHERE USERID = @USERID AND WORECTYPE = @WORECTYPE AND MKDTOPST = @MKDTOPST AND WORKORDNUM = @WORKORDNUM SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06115SD] TO [DYNGRP]
GO
