SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DD10500SI] (@INDXLONG int, @DDITEM smallint, @EMPLOYID char(15), @DDTRANS char(3), @DDTRANUM char(9), @DDACTNUM char(17), @DDAMTDLR numeric(19,5), @DDINDID char(15), @DDINDNAM char(23), @DDTRACE char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .DD10500 (INDXLONG, DDITEM, EMPLOYID, DDTRANS, DDTRANUM, DDACTNUM, DDAMTDLR, DDINDID, DDINDNAM, DDTRACE) VALUES ( @INDXLONG, @DDITEM, @EMPLOYID, @DDTRANS, @DDTRANUM, @DDACTNUM, @DDAMTDLR, @DDINDID, @DDINDNAM, @DDTRACE) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DD10500SI] TO [DYNGRP]
GO
