SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV41000SS_1] (@SETUPKEY smallint) AS  set nocount on SELECT TOP 1  SETUPKEY, NUMBERSHIFTS, HRSPRSHFT, STRTTIME, DWNONWKNDS, DEX_ROW_ID FROM .IV41000 WHERE SETUPKEY = @SETUPKEY ORDER BY SETUPKEY ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV41000SS_1] TO [DYNGRP]
GO
