SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRORI022L_1] (@ORSETUPCODE_I_RS char(31), @ORSETUPCODE_I_RE char(31)) AS  set nocount on IF @ORSETUPCODE_I_RS IS NULL BEGIN SELECT TOP 25  ORSETUPCODE_I, ORSETUPNAME_I, DEX_ROW_ID FROM .HRORI022 ORDER BY ORSETUPCODE_I DESC END ELSE IF @ORSETUPCODE_I_RS = @ORSETUPCODE_I_RE BEGIN SELECT TOP 25  ORSETUPCODE_I, ORSETUPNAME_I, DEX_ROW_ID FROM .HRORI022 WHERE ORSETUPCODE_I = @ORSETUPCODE_I_RS ORDER BY ORSETUPCODE_I DESC END ELSE BEGIN SELECT TOP 25  ORSETUPCODE_I, ORSETUPNAME_I, DEX_ROW_ID FROM .HRORI022 WHERE ORSETUPCODE_I BETWEEN @ORSETUPCODE_I_RS AND @ORSETUPCODE_I_RE ORDER BY ORSETUPCODE_I DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRORI022L_1] TO [DYNGRP]
GO
