SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4603200N_1] (@BS int, @BSSI_CPI_Schedule_ID char(25), @BSSI_CPI_Schedule_ID_RS char(25), @BSSI_CPI_Schedule_ID_RE char(25)) AS /* 12.00.0270.000 */ set nocount on IF @BSSI_CPI_Schedule_ID_RS IS NULL BEGIN SELECT TOP 25  BSSI_CPI_Schedule_ID, BSSI_Description, DATE1, TIME1, USERID, NOTEINDX, BSSI_CPIIndexCalculation, BSSI_CPIIndexAmtCalculat, BSSI_EscalateEffective, BSSI_Dummy, DEX_ROW_ID FROM .B4603200 WHERE ( BSSI_CPI_Schedule_ID > @BSSI_CPI_Schedule_ID ) ORDER BY BSSI_CPI_Schedule_ID ASC END ELSE IF @BSSI_CPI_Schedule_ID_RS = @BSSI_CPI_Schedule_ID_RE BEGIN SELECT TOP 25  BSSI_CPI_Schedule_ID, BSSI_Description, DATE1, TIME1, USERID, NOTEINDX, BSSI_CPIIndexCalculation, BSSI_CPIIndexAmtCalculat, BSSI_EscalateEffective, BSSI_Dummy, DEX_ROW_ID FROM .B4603200 WHERE BSSI_CPI_Schedule_ID = @BSSI_CPI_Schedule_ID_RS AND ( BSSI_CPI_Schedule_ID > @BSSI_CPI_Schedule_ID ) ORDER BY BSSI_CPI_Schedule_ID ASC END ELSE BEGIN SELECT TOP 25  BSSI_CPI_Schedule_ID, BSSI_Description, DATE1, TIME1, USERID, NOTEINDX, BSSI_CPIIndexCalculation, BSSI_CPIIndexAmtCalculat, BSSI_EscalateEffective, BSSI_Dummy, DEX_ROW_ID FROM .B4603200 WHERE BSSI_CPI_Schedule_ID BETWEEN @BSSI_CPI_Schedule_ID_RS AND @BSSI_CPI_Schedule_ID_RE AND ( BSSI_CPI_Schedule_ID > @BSSI_CPI_Schedule_ID ) ORDER BY BSSI_CPI_Schedule_ID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4603200N_1] TO [DYNGRP]
GO
