SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CM20500SS_1] (@CHEKBKID char(15), @RECONUM numeric(19,5)) AS  set nocount on SELECT TOP 1  CHEKBKID, RECONUM, Recond, StmntDate, StmntBal, CUTOFFBAL, ClrdPay, ClrdDep, ClrePayAmt, ClrdDepAmt, Cleared_Difference, OUTPAYTOT, OUTDEPTOT, IINADJTOT, DECADJTOT, ASOFBAL, CUTOFDAT, GLPOSTDT, MDFUSRID, MODIFDT, CURNCYID, NOTEINDX, RCRDSTTS, Reconcile_Messages, AUDITTRAIL, DEX_ROW_ID FROM .CM20500 WHERE CHEKBKID = @CHEKBKID AND RECONUM = @RECONUM ORDER BY CHEKBKID ASC, RECONUM ASC set nocount off  
GO
GRANT EXECUTE ON  [dbo].[zDP_CM20500SS_1] TO [DYNGRP]
GO
