SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL10002L_1] (@JRNENTRY_RS int, @SQNCLINE_RS numeric(19,5), @JRNENTRY_RE int, @SQNCLINE_RE numeric(19,5)) AS  set nocount on IF @JRNENTRY_RS IS NULL BEGIN SELECT TOP 25  BACHNUMB, JRNENTRY, ACTINDX, SQNCLINE, OFFINDX, PSTDAMNT, GLLINMSG, DSCRIPTN, GLLINVAL, ACCTTYPE, DECPLACS, OFFACTYP, OFFXVAR, OFFBLCLC, OFFDECPL, DEX_ROW_ID FROM .GL10002 ORDER BY JRNENTRY DESC, SQNCLINE DESC END ELSE IF @JRNENTRY_RS = @JRNENTRY_RE BEGIN SELECT TOP 25  BACHNUMB, JRNENTRY, ACTINDX, SQNCLINE, OFFINDX, PSTDAMNT, GLLINMSG, DSCRIPTN, GLLINVAL, ACCTTYPE, DECPLACS, OFFACTYP, OFFXVAR, OFFBLCLC, OFFDECPL, DEX_ROW_ID FROM .GL10002 WHERE JRNENTRY = @JRNENTRY_RS AND SQNCLINE BETWEEN @SQNCLINE_RS AND @SQNCLINE_RE ORDER BY JRNENTRY DESC, SQNCLINE DESC END ELSE BEGIN SELECT TOP 25  BACHNUMB, JRNENTRY, ACTINDX, SQNCLINE, OFFINDX, PSTDAMNT, GLLINMSG, DSCRIPTN, GLLINVAL, ACCTTYPE, DECPLACS, OFFACTYP, OFFXVAR, OFFBLCLC, OFFDECPL, DEX_ROW_ID FROM .GL10002 WHERE JRNENTRY BETWEEN @JRNENTRY_RS AND @JRNENTRY_RE AND SQNCLINE BETWEEN @SQNCLINE_RS AND @SQNCLINE_RE ORDER BY JRNENTRY DESC, SQNCLINE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL10002L_1] TO [DYNGRP]
GO
