SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00103SS_6] (@VNDITNUM char(31), @ITEMNMBR char(31), @VENDORID char(15)) AS  set nocount on SELECT TOP 1  ITEMNMBR, VENDORID, ITMVNDTY, VNDITNUM, QTYRQSTN, QTYONORD, QTY_Drop_Shipped, LSTORDDT, LSORDQTY, LRCPTQTY, LSRCPTDT, LRCPTCST, AVRGLDTM, NORCTITM, MINORQTY, MAXORDQTY, ECORDQTY, VNDITDSC, Last_Originating_Cost, Last_Currency_ID, FREEONBOARD, PRCHSUOM, CURRNIDX, PLANNINGLEADTIME, ORDERMULTIPLE, MNFCTRITMNMBR, DEX_ROW_ID FROM .IV00103 WHERE VNDITNUM = @VNDITNUM AND ITEMNMBR = @ITEMNMBR AND VENDORID = @VENDORID ORDER BY VNDITNUM ASC, ITEMNMBR ASC, VENDORID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00103SS_6] TO [DYNGRP]
GO
