SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL40200SD] (@SGMTNUMB smallint, @SGMNTID char(67), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .GL40200 WHERE SGMTNUMB = @SGMTNUMB AND SGMNTID = @SGMNTID AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .GL40200 WHERE SGMTNUMB = @SGMTNUMB AND SGMNTID = @SGMNTID SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL40200SD] TO [DYNGRP]
GO
