SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00112N_3] (@BS int, @GPA char(5), @GPABASE char(3), @DEX_ROW_ID int, @GPA_RS char(5), @GPABASE_RS char(3), @GPA_RE char(5), @GPABASE_RE char(3)) AS  set nocount on IF @GPA_RS IS NULL BEGIN SELECT TOP 25  EMPLOYID, SEQNUMBR, UNIVERSITY, DEGREE, MAJOR, GPA, GPABASE, GRADUATIONYEAR, YEARS, NOTEINDX, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .UPR00112 WHERE ( GPA = @GPA AND GPABASE = @GPABASE AND DEX_ROW_ID > @DEX_ROW_ID OR GPA = @GPA AND GPABASE > @GPABASE OR GPA > @GPA ) ORDER BY GPA ASC, GPABASE ASC, DEX_ROW_ID ASC END ELSE IF @GPA_RS = @GPA_RE BEGIN SELECT TOP 25  EMPLOYID, SEQNUMBR, UNIVERSITY, DEGREE, MAJOR, GPA, GPABASE, GRADUATIONYEAR, YEARS, NOTEINDX, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .UPR00112 WHERE GPA = @GPA_RS AND GPABASE BETWEEN @GPABASE_RS AND @GPABASE_RE AND ( GPA = @GPA AND GPABASE = @GPABASE AND DEX_ROW_ID > @DEX_ROW_ID OR GPA = @GPA AND GPABASE > @GPABASE OR GPA > @GPA ) ORDER BY GPA ASC, GPABASE ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  EMPLOYID, SEQNUMBR, UNIVERSITY, DEGREE, MAJOR, GPA, GPABASE, GRADUATIONYEAR, YEARS, NOTEINDX, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .UPR00112 WHERE GPA BETWEEN @GPA_RS AND @GPA_RE AND GPABASE BETWEEN @GPABASE_RS AND @GPABASE_RE AND ( GPA = @GPA AND GPABASE = @GPABASE AND DEX_ROW_ID > @DEX_ROW_ID OR GPA = @GPA AND GPABASE > @GPABASE OR GPA > @GPA ) ORDER BY GPA ASC, GPABASE ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00112N_3] TO [DYNGRP]
GO
