SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL40000F_1] (@UNIQKEY_RS char(1), @UNIQKEY_RE char(1)) AS  set nocount on IF @UNIQKEY_RS IS NULL BEGIN SELECT TOP 25  UNIQKEY, NJRNLENT, RERINDX, LSTCLSDT, TRERCLSG, DIVACTSG, BLNCDSPL, KPGACHST, KPGTRXHS, AHSTPSTG, USRDFPR1, USRDRPR2, USRDRPR3, USRDRPR4, UPDTACCEL, Posting_Number_Type, Delete_Saved_Trx, Void_Sub_Trx, Correct_IC_Trx, Allow_Reporting_Ledgers, UseLedgersForAcctBalance, NXTBUDJRLENT, KPBUDTRXHIST, NextReconciliationNumber, DEX_ROW_TS, DEX_ROW_ID FROM .GL40000 ORDER BY UNIQKEY ASC END ELSE IF @UNIQKEY_RS = @UNIQKEY_RE BEGIN SELECT TOP 25  UNIQKEY, NJRNLENT, RERINDX, LSTCLSDT, TRERCLSG, DIVACTSG, BLNCDSPL, KPGACHST, KPGTRXHS, AHSTPSTG, USRDFPR1, USRDRPR2, USRDRPR3, USRDRPR4, UPDTACCEL, Posting_Number_Type, Delete_Saved_Trx, Void_Sub_Trx, Correct_IC_Trx, Allow_Reporting_Ledgers, UseLedgersForAcctBalance, NXTBUDJRLENT, KPBUDTRXHIST, NextReconciliationNumber, DEX_ROW_TS, DEX_ROW_ID FROM .GL40000 WHERE UNIQKEY = @UNIQKEY_RS ORDER BY UNIQKEY ASC END ELSE BEGIN SELECT TOP 25  UNIQKEY, NJRNLENT, RERINDX, LSTCLSDT, TRERCLSG, DIVACTSG, BLNCDSPL, KPGACHST, KPGTRXHS, AHSTPSTG, USRDFPR1, USRDRPR2, USRDRPR3, USRDRPR4, UPDTACCEL, Posting_Number_Type, Delete_Saved_Trx, Void_Sub_Trx, Correct_IC_Trx, Allow_Reporting_Ledgers, UseLedgersForAcctBalance, NXTBUDJRLENT, KPBUDTRXHIST, NextReconciliationNumber, DEX_ROW_TS, DEX_ROW_ID FROM .GL40000 WHERE UNIQKEY BETWEEN @UNIQKEY_RS AND @UNIQKEY_RE ORDER BY UNIQKEY ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL40000F_1] TO [DYNGRP]
GO
