SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00851SS_1] (@ECO_Number char(15), @RCRDTYPE smallint, @LNITMSEQ int) AS  set nocount on SELECT TOP 1  ECO_Number, LNITMSEQ, RCRDTYPE, ITEMNMBR, QUANTITY, UOFM, UOMSCHDL, UNITCOST, UNITPRCE, EXTDCOST, XTNDPRCE, DEX_ROW_ID FROM .SVC00851 WHERE ECO_Number = @ECO_Number AND RCRDTYPE = @RCRDTYPE AND LNITMSEQ = @LNITMSEQ ORDER BY ECO_Number ASC, RCRDTYPE ASC, LNITMSEQ ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00851SS_1] TO [DYNGRP]
GO
