SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR42000N_1] (@BS int, @STATUSCD char(15), @STATUSCD_RS char(15), @STATUSCD_RE char(15)) AS  set nocount on IF @STATUSCD_RS IS NULL BEGIN SELECT TOP 25  STATUSCD, STSDESCR, STATUSTYPE, INACTIVE, NOTEINDX, DEX_ROW_ID FROM .UPR42000 WHERE ( STATUSCD > @STATUSCD ) ORDER BY STATUSCD ASC END ELSE IF @STATUSCD_RS = @STATUSCD_RE BEGIN SELECT TOP 25  STATUSCD, STSDESCR, STATUSTYPE, INACTIVE, NOTEINDX, DEX_ROW_ID FROM .UPR42000 WHERE STATUSCD = @STATUSCD_RS AND ( STATUSCD > @STATUSCD ) ORDER BY STATUSCD ASC END ELSE BEGIN SELECT TOP 25  STATUSCD, STSDESCR, STATUSTYPE, INACTIVE, NOTEINDX, DEX_ROW_ID FROM .UPR42000 WHERE STATUSCD BETWEEN @STATUSCD_RS AND @STATUSCD_RE AND ( STATUSCD > @STATUSCD ) ORDER BY STATUSCD ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR42000N_1] TO [DYNGRP]
GO
