SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM00202SS_1] (@HISTTYPE smallint, @VENDORID char(15), @YEAR1 smallint, @PERIODID smallint) AS  set nocount on SELECT TOP 1  VENDORID, PERIODID, YEAR1, HISTTYPE, AMBLDLIF, AMTPDLIF, TEN99ALIF, DISAVLIF, DISTKNLF, DISLSTLF, FINCHLIF, WROFSLIF, RTRNSLIF, TRDTKLIF, NFNCHLIF, NOINVLIF, Withholding_LIFE, DEX_ROW_ID FROM .PM00202 WHERE HISTTYPE = @HISTTYPE AND VENDORID = @VENDORID AND YEAR1 = @YEAR1 AND PERIODID = @PERIODID ORDER BY HISTTYPE ASC, VENDORID ASC, YEAR1 ASC, PERIODID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM00202SS_1] TO [DYNGRP]
GO
