SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MS273507L_1] (@MSO_AddressGUID_RS char(51), @MSO_AddressGUID_RE char(51)) AS /* 12.00.0311.000 */ set nocount on IF @MSO_AddressGUID_RS IS NULL BEGIN SELECT TOP 25  MSO_AddressGUID, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, COUNTRY, PHONNAME, EMail, DEX_ROW_ID FROM .MS273507 ORDER BY MSO_AddressGUID DESC END ELSE IF @MSO_AddressGUID_RS = @MSO_AddressGUID_RE BEGIN SELECT TOP 25  MSO_AddressGUID, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, COUNTRY, PHONNAME, EMail, DEX_ROW_ID FROM .MS273507 WHERE MSO_AddressGUID = @MSO_AddressGUID_RS ORDER BY MSO_AddressGUID DESC END ELSE BEGIN SELECT TOP 25  MSO_AddressGUID, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, COUNTRY, PHONNAME, EMail, DEX_ROW_ID FROM .MS273507 WHERE MSO_AddressGUID BETWEEN @MSO_AddressGUID_RS AND @MSO_AddressGUID_RE ORDER BY MSO_AddressGUID DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MS273507L_1] TO [DYNGRP]
GO
