SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_EXT01400L_1] (@DOCNUMBR_RS char(21), @Extender_Record_ID_RS int, @DOCNUMBR_RE char(21), @Extender_Record_ID_RE int) AS /* 12.00.0311.000 */ set nocount on IF @DOCNUMBR_RS IS NULL BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 ORDER BY DOCNUMBR DESC, Extender_Record_ID DESC END ELSE IF @DOCNUMBR_RS = @DOCNUMBR_RE BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 WHERE DOCNUMBR = @DOCNUMBR_RS AND Extender_Record_ID BETWEEN @Extender_Record_ID_RS AND @Extender_Record_ID_RE ORDER BY DOCNUMBR DESC, Extender_Record_ID DESC END ELSE BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 WHERE DOCNUMBR BETWEEN @DOCNUMBR_RS AND @DOCNUMBR_RE AND Extender_Record_ID BETWEEN @Extender_Record_ID_RS AND @Extender_Record_ID_RE ORDER BY DOCNUMBR DESC, Extender_Record_ID DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_EXT01400L_1] TO [DYNGRP]
GO
