SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MS273539SS_1] (@MSO_EngineGUID char(51)) AS /* 12.00.0311.000 */ set nocount on SELECT TOP 1  MSO_EngineGUID, DEX_ROW_ID FROM .MS273539 WHERE MSO_EngineGUID = @MSO_EngineGUID ORDER BY MSO_EngineGUID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MS273539SS_1] TO [DYNGRP]
GO
