SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRSAX012SI] (@TABLE_I smallint, @ROW_I smallint, @COL_I smallint, @SALARYLOW_I numeric(19,5), @SALARYMED_I numeric(19,5), @SALARYHIGH_I numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .HRSAX012 (TABLE_I, ROW_I, COL_I, SALARYLOW_I, SALARYMED_I, SALARYHIGH_I) VALUES ( @TABLE_I, @ROW_I, @COL_I, @SALARYLOW_I, @SALARYMED_I, @SALARYHIGH_I) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRSAX012SI] TO [DYNGRP]
GO
