SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HR30101L_1] (@EMPLOYID_RS char(15), @UNIVERSITY_RS char(31), @SEQNUMBR_RS int, @EMPLOYID_RE char(15), @UNIVERSITY_RE char(31), @SEQNUMBR_RE int) AS  set nocount on IF @EMPLOYID_RS IS NULL BEGIN SELECT TOP 25  EMPLOYID, UNIVERSITY, SEQNUMBR, MAJOR, GRADUATIONYEAR, DEGREE, GPA, GPABASE, DEX_ROW_ID FROM .HR30101 ORDER BY EMPLOYID DESC, UNIVERSITY DESC, SEQNUMBR DESC END ELSE IF @EMPLOYID_RS = @EMPLOYID_RE BEGIN SELECT TOP 25  EMPLOYID, UNIVERSITY, SEQNUMBR, MAJOR, GRADUATIONYEAR, DEGREE, GPA, GPABASE, DEX_ROW_ID FROM .HR30101 WHERE EMPLOYID = @EMPLOYID_RS AND UNIVERSITY BETWEEN @UNIVERSITY_RS AND @UNIVERSITY_RE AND SEQNUMBR BETWEEN @SEQNUMBR_RS AND @SEQNUMBR_RE ORDER BY EMPLOYID DESC, UNIVERSITY DESC, SEQNUMBR DESC END ELSE BEGIN SELECT TOP 25  EMPLOYID, UNIVERSITY, SEQNUMBR, MAJOR, GRADUATIONYEAR, DEGREE, GPA, GPABASE, DEX_ROW_ID FROM .HR30101 WHERE EMPLOYID BETWEEN @EMPLOYID_RS AND @EMPLOYID_RE AND UNIVERSITY BETWEEN @UNIVERSITY_RS AND @UNIVERSITY_RE AND SEQNUMBR BETWEEN @SEQNUMBR_RS AND @SEQNUMBR_RE ORDER BY EMPLOYID DESC, UNIVERSITY DESC, SEQNUMBR DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR30101L_1] TO [DYNGRP]
GO
