SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2900200L_2] (@USERID_RS char(15), @USERID_RE char(15)) AS /* 12.00.0270.000 */ set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  CUSTNMBR, LNITMSEQ, USERID, DOCDATE, SLSAMNT, PAYMENT_AMOUNT, NUM_PAYMENTS, NOFCUPER, SCHEDULE_INT_RATE, DOCNUMBR, SCHEDULE_NUMBER, BSSI_InterestRate, BSSI_LeaseID, PYMNT_FREQUENCY, SCHEDULE_INT_TYPE1, FIRST_INV_DUE_DATE, BSSI_CalculatedDeferralA, BSSI_EnableNegativeAmort, BSSI_LeaseLoanType, BSSI_Facility_ID, DEX_ROW_ID FROM .B2900200 ORDER BY USERID DESC, DEX_ROW_ID DESC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  CUSTNMBR, LNITMSEQ, USERID, DOCDATE, SLSAMNT, PAYMENT_AMOUNT, NUM_PAYMENTS, NOFCUPER, SCHEDULE_INT_RATE, DOCNUMBR, SCHEDULE_NUMBER, BSSI_InterestRate, BSSI_LeaseID, PYMNT_FREQUENCY, SCHEDULE_INT_TYPE1, FIRST_INV_DUE_DATE, BSSI_CalculatedDeferralA, BSSI_EnableNegativeAmort, BSSI_LeaseLoanType, BSSI_Facility_ID, DEX_ROW_ID FROM .B2900200 WHERE USERID = @USERID_RS ORDER BY USERID DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  CUSTNMBR, LNITMSEQ, USERID, DOCDATE, SLSAMNT, PAYMENT_AMOUNT, NUM_PAYMENTS, NOFCUPER, SCHEDULE_INT_RATE, DOCNUMBR, SCHEDULE_NUMBER, BSSI_InterestRate, BSSI_LeaseID, PYMNT_FREQUENCY, SCHEDULE_INT_TYPE1, FIRST_INV_DUE_DATE, BSSI_CalculatedDeferralA, BSSI_EnableNegativeAmort, BSSI_LeaseLoanType, BSSI_Facility_ID, DEX_ROW_ID FROM .B2900200 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE ORDER BY USERID DESC, DEX_ROW_ID DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2900200L_2] TO [DYNGRP]
GO
