SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR40902N_2] (@BS int, @DEDNSQNC smallint, @DEX_ROW_ID int, @DEDNSQNC_RS smallint, @DEDNSQNC_RE smallint) AS  set nocount on IF @DEDNSQNC_RS IS NULL BEGIN SELECT TOP 25  DEDUCTON, DEDNSQNC, DEX_ROW_ID FROM .UPR40902 WHERE ( DEDNSQNC = @DEDNSQNC AND DEX_ROW_ID > @DEX_ROW_ID OR DEDNSQNC > @DEDNSQNC ) ORDER BY DEDNSQNC ASC, DEX_ROW_ID ASC END ELSE IF @DEDNSQNC_RS = @DEDNSQNC_RE BEGIN SELECT TOP 25  DEDUCTON, DEDNSQNC, DEX_ROW_ID FROM .UPR40902 WHERE DEDNSQNC = @DEDNSQNC_RS AND ( DEDNSQNC = @DEDNSQNC AND DEX_ROW_ID > @DEX_ROW_ID OR DEDNSQNC > @DEDNSQNC ) ORDER BY DEDNSQNC ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  DEDUCTON, DEDNSQNC, DEX_ROW_ID FROM .UPR40902 WHERE DEDNSQNC BETWEEN @DEDNSQNC_RS AND @DEDNSQNC_RE AND ( DEDNSQNC = @DEDNSQNC AND DEX_ROW_ID > @DEX_ROW_ID OR DEDNSQNC > @DEDNSQNC ) ORDER BY DEDNSQNC ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR40902N_2] TO [DYNGRP]
GO
