SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA42000F_1] (@TRANSFEREVENT_RS int, @TRANSFEREVENT_RE int) AS  set nocount on IF @TRANSFEREVENT_RS IS NULL BEGIN SELECT TOP 25  TRANSFEREVENT, XFEREVENTDESC, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42000 ORDER BY TRANSFEREVENT ASC END ELSE IF @TRANSFEREVENT_RS = @TRANSFEREVENT_RE BEGIN SELECT TOP 25  TRANSFEREVENT, XFEREVENTDESC, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42000 WHERE TRANSFEREVENT = @TRANSFEREVENT_RS ORDER BY TRANSFEREVENT ASC END ELSE BEGIN SELECT TOP 25  TRANSFEREVENT, XFEREVENTDESC, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42000 WHERE TRANSFEREVENT BETWEEN @TRANSFEREVENT_RS AND @TRANSFEREVENT_RE ORDER BY TRANSFEREVENT ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA42000F_1] TO [DYNGRP]
GO
