SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA40201N_2] (@BS int, @ASSETCLASSID char(15), @ASSETCLASSID_RS char(15), @ASSETCLASSID_RE char(15)) AS  set nocount on IF @ASSETCLASSID_RS IS NULL BEGIN SELECT TOP 25  ASSETCLASSINDX, ASSETCLASSID, ASSETCLASSIDDESC, DEFACCTGRPINDX, DEFINSCLASSINDX, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, ClassNextAssetIDFLG, NXTASSETID, DEX_ROW_ID FROM .FA40201 WHERE ( ASSETCLASSID > @ASSETCLASSID ) ORDER BY ASSETCLASSID ASC END ELSE IF @ASSETCLASSID_RS = @ASSETCLASSID_RE BEGIN SELECT TOP 25  ASSETCLASSINDX, ASSETCLASSID, ASSETCLASSIDDESC, DEFACCTGRPINDX, DEFINSCLASSINDX, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, ClassNextAssetIDFLG, NXTASSETID, DEX_ROW_ID FROM .FA40201 WHERE ASSETCLASSID = @ASSETCLASSID_RS AND ( ASSETCLASSID > @ASSETCLASSID ) ORDER BY ASSETCLASSID ASC END ELSE BEGIN SELECT TOP 25  ASSETCLASSINDX, ASSETCLASSID, ASSETCLASSIDDESC, DEFACCTGRPINDX, DEFINSCLASSINDX, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, ClassNextAssetIDFLG, NXTASSETID, DEX_ROW_ID FROM .FA40201 WHERE ASSETCLASSID BETWEEN @ASSETCLASSID_RS AND @ASSETCLASSID_RE AND ( ASSETCLASSID > @ASSETCLASSID ) ORDER BY ASSETCLASSID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA40201N_2] TO [DYNGRP]
GO
