SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP50100F_4] (@PROCORIG_RS smallint, @USERID_RS char(15), @BACHNUMB_RS char(15), @PROCORIG_RE smallint, @USERID_RE char(15), @BACHNUMB_RE char(15)) AS  set nocount on IF @PROCORIG_RS IS NULL BEGIN SELECT TOP 25  PROCORIG, USERID, MKTOPROC, SOPNUMBE, SOPTYPE, DOCDATE, CUSTNMBR, CUSTNAME, CSTPONBR, BACHNUMB, DOCID, ERROR, DEX_ROW_ID FROM .SOP50100 ORDER BY PROCORIG ASC, USERID ASC, BACHNUMB ASC, DEX_ROW_ID ASC END ELSE IF @PROCORIG_RS = @PROCORIG_RE BEGIN SELECT TOP 25  PROCORIG, USERID, MKTOPROC, SOPNUMBE, SOPTYPE, DOCDATE, CUSTNMBR, CUSTNAME, CSTPONBR, BACHNUMB, DOCID, ERROR, DEX_ROW_ID FROM .SOP50100 WHERE PROCORIG = @PROCORIG_RS AND USERID BETWEEN @USERID_RS AND @USERID_RE AND BACHNUMB BETWEEN @BACHNUMB_RS AND @BACHNUMB_RE ORDER BY PROCORIG ASC, USERID ASC, BACHNUMB ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  PROCORIG, USERID, MKTOPROC, SOPNUMBE, SOPTYPE, DOCDATE, CUSTNMBR, CUSTNAME, CSTPONBR, BACHNUMB, DOCID, ERROR, DEX_ROW_ID FROM .SOP50100 WHERE PROCORIG BETWEEN @PROCORIG_RS AND @PROCORIG_RE AND USERID BETWEEN @USERID_RS AND @USERID_RE AND BACHNUMB BETWEEN @BACHNUMB_RS AND @BACHNUMB_RE ORDER BY PROCORIG ASC, USERID ASC, BACHNUMB ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP50100F_4] TO [DYNGRP]
GO
