SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00940SS_2] (@SRVCCDDSC char(31)) AS  set nocount on SELECT TOP 1  SRVCCD, SRVCCDDSC, DEX_ROW_ID FROM .SVC00940 WHERE SRVCCDDSC = @SRVCCDDSC ORDER BY SRVCCDDSC ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00940SS_2] TO [DYNGRP]
GO
