SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00940N_2] (@BS int, @SRVCCDDSC char(31), @DEX_ROW_ID int, @SRVCCDDSC_RS char(31), @SRVCCDDSC_RE char(31)) AS  set nocount on IF @SRVCCDDSC_RS IS NULL BEGIN SELECT TOP 25  SRVCCD, SRVCCDDSC, DEX_ROW_ID FROM .SVC00940 WHERE ( SRVCCDDSC = @SRVCCDDSC AND DEX_ROW_ID > @DEX_ROW_ID OR SRVCCDDSC > @SRVCCDDSC ) ORDER BY SRVCCDDSC ASC, DEX_ROW_ID ASC END ELSE IF @SRVCCDDSC_RS = @SRVCCDDSC_RE BEGIN SELECT TOP 25  SRVCCD, SRVCCDDSC, DEX_ROW_ID FROM .SVC00940 WHERE SRVCCDDSC = @SRVCCDDSC_RS AND ( SRVCCDDSC = @SRVCCDDSC AND DEX_ROW_ID > @DEX_ROW_ID OR SRVCCDDSC > @SRVCCDDSC ) ORDER BY SRVCCDDSC ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  SRVCCD, SRVCCDDSC, DEX_ROW_ID FROM .SVC00940 WHERE SRVCCDDSC BETWEEN @SRVCCDDSC_RS AND @SRVCCDDSC_RE AND ( SRVCCDDSC = @SRVCCDDSC AND DEX_ROW_ID > @DEX_ROW_ID OR SRVCCDDSC > @SRVCCDDSC ) ORDER BY SRVCCDDSC ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00940N_2] TO [DYNGRP]
GO
