SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC01100N_1] (@BS int, @SPLTTERMS char(11), @SPLTTERMS_RS char(11), @SPLTTERMS_RE char(11)) AS  set nocount on IF @SPLTTERMS_RS IS NULL BEGIN SELECT TOP 25  SPLTTERMS, DSCRIPTN, DEX_ROW_ID FROM .SVC01100 WHERE ( SPLTTERMS > @SPLTTERMS ) ORDER BY SPLTTERMS ASC END ELSE IF @SPLTTERMS_RS = @SPLTTERMS_RE BEGIN SELECT TOP 25  SPLTTERMS, DSCRIPTN, DEX_ROW_ID FROM .SVC01100 WHERE SPLTTERMS = @SPLTTERMS_RS AND ( SPLTTERMS > @SPLTTERMS ) ORDER BY SPLTTERMS ASC END ELSE BEGIN SELECT TOP 25  SPLTTERMS, DSCRIPTN, DEX_ROW_ID FROM .SVC01100 WHERE SPLTTERMS BETWEEN @SPLTTERMS_RS AND @SPLTTERMS_RE AND ( SPLTTERMS > @SPLTTERMS ) ORDER BY SPLTTERMS ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC01100N_1] TO [DYNGRP]
GO
