SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SY04200L_2] (@CMTSRIES_RS smallint, @CMTSRIES_RE smallint) AS  set nocount on IF @CMTSRIES_RS IS NULL BEGIN SELECT TOP 25  CMTSRIES, COMMNTID, NOTEINDX, DEX_ROW_ID, CMMTTEXT FROM .SY04200 ORDER BY CMTSRIES DESC, DEX_ROW_ID DESC END ELSE IF @CMTSRIES_RS = @CMTSRIES_RE BEGIN SELECT TOP 25  CMTSRIES, COMMNTID, NOTEINDX, DEX_ROW_ID, CMMTTEXT FROM .SY04200 WHERE CMTSRIES = @CMTSRIES_RS ORDER BY CMTSRIES DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  CMTSRIES, COMMNTID, NOTEINDX, DEX_ROW_ID, CMMTTEXT FROM .SY04200 WHERE CMTSRIES BETWEEN @CMTSRIES_RS AND @CMTSRIES_RE ORDER BY CMTSRIES DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY04200L_2] TO [DYNGRP]
GO
