SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2920990SS_1] (@DOCNUMBR char(21)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  DOCNUMBR, CUSTNMBR, BSSI_Lease_Loan_Number, Schedule_Payment_Number, BSSI_IsAccountSubs, BSSI_IsIntercompany, BSSI_IsProcessed, DEX_ROW_ID FROM .B2920990 WHERE DOCNUMBR = @DOCNUMBR ORDER BY DOCNUMBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2920990SS_1] TO [DYNGRP]
GO
