SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME27624SS_1] (@PMNTNMBR char(21)) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  PMNTNMBR, ADRSCODE, DEX_ROW_ID FROM .ME27624 WHERE PMNTNMBR = @PMNTNMBR ORDER BY PMNTNMBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME27624SS_1] TO [DYNGRP]
GO
