SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG00200VF_1] (@ACTINDX_RS int, @ACTINDX_RE int) AS  set nocount on IF @ACTINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, ACTNUMST, ACTDESCR, ACCTTYPE, DEX_ROW_ID FROM .AAG00200V ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END ELSE IF @ACTINDX_RS = @ACTINDX_RE BEGIN SELECT TOP 25  ACTINDX, ACTNUMST, ACTDESCR, ACCTTYPE, DEX_ROW_ID FROM .AAG00200V WHERE ACTINDX = @ACTINDX_RS ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  ACTINDX, ACTNUMST, ACTDESCR, ACCTTYPE, DEX_ROW_ID FROM .AAG00200V WHERE ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG00200VF_1] TO [DYNGRP]
GO
