SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP30100L_2] (@TRXSORCE_RS char(13), @TRXSORCE_RE char(13)) AS  set nocount on IF @TRXSORCE_RS IS NULL BEGIN SELECT TOP 25  TRXSORCE, BCHSOURC, BACHNUMB, BCHCOMNT, CHEKBKID, GLPOSTDT, APPROVL, APPRVLDT, APRVLUSERID, BCHTOTAL, CNTRLTOT, NUMOFTRX, CNTRLTRX, REPRNTNT, USERID, NOTEINDX, TRXMISNG, DEX_ROW_ID FROM .SOP30100 ORDER BY TRXSORCE DESC, DEX_ROW_ID DESC END ELSE IF @TRXSORCE_RS = @TRXSORCE_RE BEGIN SELECT TOP 25  TRXSORCE, BCHSOURC, BACHNUMB, BCHCOMNT, CHEKBKID, GLPOSTDT, APPROVL, APPRVLDT, APRVLUSERID, BCHTOTAL, CNTRLTOT, NUMOFTRX, CNTRLTRX, REPRNTNT, USERID, NOTEINDX, TRXMISNG, DEX_ROW_ID FROM .SOP30100 WHERE TRXSORCE = @TRXSORCE_RS ORDER BY TRXSORCE DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  TRXSORCE, BCHSOURC, BACHNUMB, BCHCOMNT, CHEKBKID, GLPOSTDT, APPROVL, APPRVLDT, APRVLUSERID, BCHTOTAL, CNTRLTOT, NUMOFTRX, CNTRLTRX, REPRNTNT, USERID, NOTEINDX, TRXMISNG, DEX_ROW_ID FROM .SOP30100 WHERE TRXSORCE BETWEEN @TRXSORCE_RS AND @TRXSORCE_RE ORDER BY TRXSORCE DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP30100L_2] TO [DYNGRP]
GO
