SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AUSERMSTSI] (@USERID char(15), @USERNAME char(31), @EMPID_I char(15), @ACCESSLEVEL_I smallint, @PostIvIn smallint, @PostPRIn smallint, @PostPurchIn smallint, @PASSWORD binary(16), @USRCLASS char(15), @MDFRDENT smallint, @MODIFDT datetime, @CREATDDT datetime, @LSTUSRED char(15), @PRTOSCRN tinyint, @PRTOPRTR tinyint, @SHRQFLDS tinyint, @DISTPROC smallint, @HSCRLARW tinyint, @CHECK1_I tinyint, @CHECK2_I tinyint, @CHECK3_I tinyint, @CHECK4_I tinyint, @INACTIVE tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .AUSERMST (USERID, USERNAME, EMPID_I, ACCESSLEVEL_I, PostIvIn, PostPRIn, PostPurchIn, PASSWORD, USRCLASS, MDFRDENT, MODIFDT, CREATDDT, LSTUSRED, PRTOSCRN, PRTOPRTR, SHRQFLDS, DISTPROC, HSCRLARW, CHECK1_I, CHECK2_I, CHECK3_I, CHECK4_I, INACTIVE) VALUES ( @USERID, @USERNAME, @EMPID_I, @ACCESSLEVEL_I, @PostIvIn, @PostPRIn, @PostPurchIn, @PASSWORD, @USRCLASS, @MDFRDENT, @MODIFDT, @CREATDDT, @LSTUSRED, @PRTOSCRN, @PRTOPRTR, @SHRQFLDS, @DISTPROC, @HSCRLARW, @CHECK1_I, @CHECK2_I, @CHECK3_I, @CHECK4_I, @INACTIVE) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AUSERMSTSI] TO [DYNGRP]
GO
