SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2910201N_1] (@BS int, @RMDTYPAL smallint, @DOCNUMBR char(21), @RMDTYPAL_RS smallint, @DOCNUMBR_RS char(21), @RMDTYPAL_RE smallint, @DOCNUMBR_RE char(21)) AS /* 12.00.0270.000 */ set nocount on IF @RMDTYPAL_RS IS NULL BEGIN SELECT TOP 25  DOCNUMBR, RMDTYPAL, BS29_Create_Schedule_Dis, DEX_ROW_ID FROM .B2910201 WHERE ( RMDTYPAL = @RMDTYPAL AND DOCNUMBR > @DOCNUMBR OR RMDTYPAL > @RMDTYPAL ) ORDER BY RMDTYPAL ASC, DOCNUMBR ASC END ELSE IF @RMDTYPAL_RS = @RMDTYPAL_RE BEGIN SELECT TOP 25  DOCNUMBR, RMDTYPAL, BS29_Create_Schedule_Dis, DEX_ROW_ID FROM .B2910201 WHERE RMDTYPAL = @RMDTYPAL_RS AND DOCNUMBR BETWEEN @DOCNUMBR_RS AND @DOCNUMBR_RE AND ( RMDTYPAL = @RMDTYPAL AND DOCNUMBR > @DOCNUMBR OR RMDTYPAL > @RMDTYPAL ) ORDER BY RMDTYPAL ASC, DOCNUMBR ASC END ELSE BEGIN SELECT TOP 25  DOCNUMBR, RMDTYPAL, BS29_Create_Schedule_Dis, DEX_ROW_ID FROM .B2910201 WHERE RMDTYPAL BETWEEN @RMDTYPAL_RS AND @RMDTYPAL_RE AND DOCNUMBR BETWEEN @DOCNUMBR_RS AND @DOCNUMBR_RE AND ( RMDTYPAL = @RMDTYPAL AND DOCNUMBR > @DOCNUMBR OR RMDTYPAL > @RMDTYPAL ) ORDER BY RMDTYPAL ASC, DOCNUMBR ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2910201N_1] TO [DYNGRP]
GO
