SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CM20203SS_2] (@CHEKBKID char(15), @SERIES smallint, @EFT_Status smallint, @BCHSOURC char(15), @BACHNUMB char(15)) AS  set nocount on SELECT TOP 1  CHEKBKID, BCHSOURC, BACHNUMB, POSTEDDT, NUMOFTRX, BCHTOTAL, USERID, EFTGenerationTimestamp, EFT_Status, SERIES, DEX_ROW_ID FROM .CM20203 WHERE CHEKBKID = @CHEKBKID AND SERIES = @SERIES AND EFT_Status = @EFT_Status AND BCHSOURC = @BCHSOURC AND BACHNUMB = @BACHNUMB ORDER BY CHEKBKID ASC, SERIES ASC, EFT_Status ASC, BCHSOURC ASC, BACHNUMB ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CM20203SS_2] TO [DYNGRP]
GO
