SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100701SS_2] (@BSSI_EBTemplateID char(25), @BSSI_EventID char(25)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  BSSI_EBTemplateID, LNITMSEQ, BSSI_EventID, BSSI_Description, BSSI_Event_Percent, BSSI_ExpiryPeriod, BSSI_ATExpiryPeriod, DEX_ROW_ID FROM .B7100701 WHERE BSSI_EBTemplateID = @BSSI_EBTemplateID AND BSSI_EventID = @BSSI_EventID ORDER BY BSSI_EBTemplateID ASC, BSSI_EventID ASC, DEX_ROW_ID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100701SS_2] TO [DYNGRP]
GO
