SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_TX00203SD] (@TAXDTLID char(15), @HISTTYPE smallint, @YEAR1 smallint, @PERIODID smallint, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .TX00203 WHERE TAXDTLID = @TAXDTLID AND HISTTYPE = @HISTTYPE AND YEAR1 = @YEAR1 AND PERIODID = @PERIODID AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .TX00203 WHERE TAXDTLID = @TAXDTLID AND HISTTYPE = @HISTTYPE AND YEAR1 = @YEAR1 AND PERIODID = @PERIODID SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_TX00203SD] TO [DYNGRP]
GO
