SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00102L_2] (@ITEMNMBR_RS char(31), @PROBCDE_RS char(11), @ITEMNMBR_RE char(31), @PROBCDE_RE char(11)) AS  set nocount on IF @ITEMNMBR_RS IS NULL BEGIN SELECT TOP 25  TECHID, ITEMNMBR, PROBCDE, CRSENBR, CERTNUM, CERTDTE, EXPNDATE, DEX_ROW_ID FROM .SVC00102 ORDER BY ITEMNMBR DESC, PROBCDE DESC, DEX_ROW_ID DESC END ELSE IF @ITEMNMBR_RS = @ITEMNMBR_RE BEGIN SELECT TOP 25  TECHID, ITEMNMBR, PROBCDE, CRSENBR, CERTNUM, CERTDTE, EXPNDATE, DEX_ROW_ID FROM .SVC00102 WHERE ITEMNMBR = @ITEMNMBR_RS AND PROBCDE BETWEEN @PROBCDE_RS AND @PROBCDE_RE ORDER BY ITEMNMBR DESC, PROBCDE DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  TECHID, ITEMNMBR, PROBCDE, CRSENBR, CERTNUM, CERTDTE, EXPNDATE, DEX_ROW_ID FROM .SVC00102 WHERE ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND PROBCDE BETWEEN @PROBCDE_RS AND @PROBCDE_RE ORDER BY ITEMNMBR DESC, PROBCDE DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00102L_2] TO [DYNGRP]
GO
