SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC05615SI] (@USERID char(15), @RTV_Number char(15), @RTV_Line numeric(19,5), @RTV_Type char(11), @OFFID char(11), @VENDORID char(15), @ADRSCODE char(15), @VENDNAME char(65), @ITEMNMBR char(31), @ITMTRKOP smallint, @QUANTITY numeric(19,5), @LOCCODEB char(11), @VNDITNUM char(31), @SHIPMTHD char(15), @Tracking_Number char(41), @CB_Packing_Slip tinyint, @MKDTOPST tinyint, @POSTED tinyint, @ERMSGNBR smallint, @ERMSGTXT char(255), @ERMSGTX2 char(255), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC05615 (USERID, RTV_Number, RTV_Line, RTV_Type, OFFID, VENDORID, ADRSCODE, VENDNAME, ITEMNMBR, ITMTRKOP, QUANTITY, LOCCODEB, VNDITNUM, SHIPMTHD, Tracking_Number, CB_Packing_Slip, MKDTOPST, POSTED, ERMSGNBR, ERMSGTXT, ERMSGTX2) VALUES ( @USERID, @RTV_Number, @RTV_Line, @RTV_Type, @OFFID, @VENDORID, @ADRSCODE, @VENDNAME, @ITEMNMBR, @ITMTRKOP, @QUANTITY, @LOCCODEB, @VNDITNUM, @SHIPMTHD, @Tracking_Number, @CB_Packing_Slip, @MKDTOPST, @POSTED, @ERMSGNBR, @ERMSGTXT, @ERMSGTX2) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC05615SI] TO [DYNGRP]
GO
