SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DD00200SS_2] (@DDTRANS char(3), @EMPLOYID char(15), @INDXLONG int) AS  set nocount on SELECT TOP 1  EMPLOYID, INDXLONG, INACTIVE, DEDNMTHD, DEDUCTON, DDPRE, DDPRECNT, DDPCT, DDAMTDLR, DDACTNUM, DDTRANUM, DDTRANS, DEX_ROW_ID FROM .DD00200 WHERE DDTRANS = @DDTRANS AND EMPLOYID = @EMPLOYID AND INDXLONG = @INDXLONG ORDER BY DDTRANS ASC, EMPLOYID ASC, INDXLONG ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DD00200SS_2] TO [DYNGRP]
GO
