SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP50200SS_2] (@USERID char(15), @SEQNUMBR int, @DOCTYPE smallint, @CUSTNMBR char(15), @LOCNCODE char(11), @DOCPRINTSEQ int, @SOPTYPE smallint, @SOPNUMBE char(21), @Email_Type smallint) AS  set nocount on SELECT TOP 1  DOCTYPE, SOPTYPE, SOPNUMBE, LOCNCODE, CUSTNMBR, USERID, SEQNUMBR, DOCPRINTSEQ, ShipToName, CNTCPRSN, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, COUNTRY, SHIPMTHD, Reprint, Email_Type, PHONNAME, DEX_ROW_ID FROM .SOP50200 WHERE USERID = @USERID AND SEQNUMBR = @SEQNUMBR AND DOCTYPE = @DOCTYPE AND CUSTNMBR = @CUSTNMBR AND LOCNCODE = @LOCNCODE AND DOCPRINTSEQ = @DOCPRINTSEQ AND SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND Email_Type = @Email_Type ORDER BY USERID ASC, SEQNUMBR ASC, DOCTYPE ASC, CUSTNMBR ASC, LOCNCODE ASC, DOCPRINTSEQ ASC, SOPTYPE ASC, SOPNUMBE ASC, Email_Type ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP50200SS_2] TO [DYNGRP]
GO
