SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP40400SS_1] (@INDEX1 smallint, @DSCRIPTN char(31)) AS  set nocount on SELECT TOP 1  INDEX1, DSCRIPTN, DEX_ROW_ID FROM .POP40400 WHERE INDEX1 = @INDEX1 AND DSCRIPTN = @DSCRIPTN ORDER BY INDEX1 ASC, DSCRIPTN ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP40400SS_1] TO [DYNGRP]
GO
