SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL12000SS_1] (@BCHSOURC char(15), @BACHNUMB char(15), @JRNENTRY int) AS  set nocount on SELECT TOP 1  BCHSOURC, BACHNUMB, JRNENTRY, BUDGETID, REFRENCE, TRXDATE, PSTGSTUS, LASTUSER, LSTDTEDT, USWHPSTD, SOURCDOC, TRXSORCE, ERRSTATE, GLHDRVAL, GLHDRMSG, GLHDRMS2, NOTEINDX, DEX_ROW_TS, DEX_ROW_ID FROM .GL12000 WHERE BCHSOURC = @BCHSOURC AND BACHNUMB = @BACHNUMB AND JRNENTRY = @JRNENTRY ORDER BY BCHSOURC ASC, BACHNUMB ASC, JRNENTRY ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL12000SS_1] TO [DYNGRP]
GO
