SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4640015F_1] (@BSSI_Template_ID_RS char(25), @BSSI_Template_ID_RE char(25)) AS /* 12.00.0311.000 */ set nocount on IF @BSSI_Template_ID_RS IS NULL BEGIN SELECT TOP 25  BSSI_PortfolioID, BSSI_Template_ID, DSCRIPTN, BSSI_MajorStoreSqFt, BSSI_Dummy, DEX_ROW_ID FROM .B4640015 ORDER BY BSSI_Template_ID ASC END ELSE IF @BSSI_Template_ID_RS = @BSSI_Template_ID_RE BEGIN SELECT TOP 25  BSSI_PortfolioID, BSSI_Template_ID, DSCRIPTN, BSSI_MajorStoreSqFt, BSSI_Dummy, DEX_ROW_ID FROM .B4640015 WHERE BSSI_Template_ID = @BSSI_Template_ID_RS ORDER BY BSSI_Template_ID ASC END ELSE BEGIN SELECT TOP 25  BSSI_PortfolioID, BSSI_Template_ID, DSCRIPTN, BSSI_MajorStoreSqFt, BSSI_Dummy, DEX_ROW_ID FROM .B4640015 WHERE BSSI_Template_ID BETWEEN @BSSI_Template_ID_RS AND @BSSI_Template_ID_RE ORDER BY BSSI_Template_ID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4640015F_1] TO [DYNGRP]
GO
