SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM20200SI] (@KEYSOURC char(41), @VCHRNMBR char(21), @DOCTYPE smallint, @DSTSQNUM int, @CRDTAMNT numeric(19,5), @DEBITAMT numeric(19,5), @DSTINDX int, @DISTTYPE smallint, @APTVCHNM char(21), @APTODCTY smallint, @CHANGED tinyint, @USERID char(15), @PSTGSTUS smallint, @GLPOSTDT datetime, @CURNCYID char(15), @CURRNIDX smallint, @ORCRDAMT numeric(19,5), @ORDBTAMT numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .PM20200 (KEYSOURC, VCHRNMBR, DOCTYPE, DSTSQNUM, CRDTAMNT, DEBITAMT, DSTINDX, DISTTYPE, APTVCHNM, APTODCTY, CHANGED, USERID, PSTGSTUS, GLPOSTDT, CURNCYID, CURRNIDX, ORCRDAMT, ORDBTAMT) VALUES ( @KEYSOURC, @VCHRNMBR, @DOCTYPE, @DSTSQNUM, @CRDTAMNT, @DEBITAMT, @DSTINDX, @DISTTYPE, @APTVCHNM, @APTODCTY, @CHANGED, @USERID, @PSTGSTUS, @GLPOSTDT, @CURNCYID, @CURRNIDX, @ORCRDAMT, @ORDBTAMT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM20200SI] TO [DYNGRP]
GO
