SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM40102SS_1] (@DOCTYPE smallint) AS  set nocount on SELECT TOP 1  DOCTYPE, DOCABREV, DOCTYNAM, DEX_ROW_ID FROM .PM40102 WHERE DOCTYPE = @DOCTYPE ORDER BY DOCTYPE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM40102SS_1] TO [DYNGRP]
GO
