SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_ME123503SS_1] (@MEUPLDID char(21)) AS  set nocount on SELECT TOP 1  MEUPLDID, MEUPDT, MEUPTIM, MKLSSTDD, MELDTDT, MENUMUPLDS, PP_Number, ME_Number_of_Checks, ME_Number_of_Voids, ME_Checks_Amount, ME_Voids_Amount, ME_Confirmation_Number, DEX_ROW_ID FROM .ME123503 WHERE MEUPLDID = @MEUPLDID ORDER BY MEUPLDID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_ME123503SS_1] TO [DYNGRP]
GO
