SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B0540100SS_1] (@SLPRSNID char(15), @MJW_Investor_ID char(21), @MJW_Offering_ID char(21), @LNITMSEQ int) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  SLPRSNID, MJW_Investor_ID, MJW_Offering_ID, LNITMSEQ, NAME, SLPRSNFN, SPRSNSLN, PHONE1, FAX, MJW_Offering_Name, MJW_Investor_Name, CHEKAMNT, MJW_Date_Accept, MJW_Distribution_Amount, BSSI_Dist_Status, BSSI_Investment_Amount, CHEKNMBR, DEX_ROW_ID FROM .B0540100 WHERE SLPRSNID = @SLPRSNID AND MJW_Investor_ID = @MJW_Investor_ID AND MJW_Offering_ID = @MJW_Offering_ID AND LNITMSEQ = @LNITMSEQ ORDER BY SLPRSNID ASC, MJW_Investor_ID ASC, MJW_Offering_ID ASC, LNITMSEQ ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B0540100SS_1] TO [DYNGRP]
GO
