SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DD10700L_3] (@DDITEM_RS smallint, @INDXLONG_RS int, @DDITEM_RE smallint, @INDXLONG_RE int) AS  set nocount on IF @DDITEM_RS IS NULL BEGIN SELECT TOP 25  INDXLONG, EMPLOYID, DDTRANUM, DDACTNUM, DDTRANS, DDAMTDLR, AMNTOPST, DDITEM, ERRDESCR, USERID, DEX_ROW_ID FROM .DD10700 ORDER BY DDITEM DESC, INDXLONG DESC END ELSE IF @DDITEM_RS = @DDITEM_RE BEGIN SELECT TOP 25  INDXLONG, EMPLOYID, DDTRANUM, DDACTNUM, DDTRANS, DDAMTDLR, AMNTOPST, DDITEM, ERRDESCR, USERID, DEX_ROW_ID FROM .DD10700 WHERE DDITEM = @DDITEM_RS AND INDXLONG BETWEEN @INDXLONG_RS AND @INDXLONG_RE ORDER BY DDITEM DESC, INDXLONG DESC END ELSE BEGIN SELECT TOP 25  INDXLONG, EMPLOYID, DDTRANUM, DDACTNUM, DDTRANS, DDAMTDLR, AMNTOPST, DDITEM, ERRDESCR, USERID, DEX_ROW_ID FROM .DD10700 WHERE DDITEM BETWEEN @DDITEM_RS AND @DDITEM_RE AND INDXLONG BETWEEN @INDXLONG_RS AND @INDXLONG_RE ORDER BY DDITEM DESC, INDXLONG DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DD10700L_3] TO [DYNGRP]
GO
