SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_ECM10003L_1] (@PO_REQ_NO_RS char(23), @SEQ_ORD_ID_RS int, @PO_REQ_NO_RE char(23), @SEQ_ORD_ID_RE int) AS  set nocount on IF @PO_REQ_NO_RS IS NULL BEGIN SELECT TOP 25  PO_REQ_NO, SEQ_ORD_ID, ITEM_ID, ITEM_DESC, VEND_ITEM_ID, VEND_ITEM_DESC, VEND_ID, VEND_NAME, COMMIT_AMT, PO_OR_REQ, DEX_ROW_ID FROM .ECM10003 ORDER BY PO_REQ_NO DESC, SEQ_ORD_ID DESC END ELSE IF @PO_REQ_NO_RS = @PO_REQ_NO_RE BEGIN SELECT TOP 25  PO_REQ_NO, SEQ_ORD_ID, ITEM_ID, ITEM_DESC, VEND_ITEM_ID, VEND_ITEM_DESC, VEND_ID, VEND_NAME, COMMIT_AMT, PO_OR_REQ, DEX_ROW_ID FROM .ECM10003 WHERE PO_REQ_NO = @PO_REQ_NO_RS AND SEQ_ORD_ID BETWEEN @SEQ_ORD_ID_RS AND @SEQ_ORD_ID_RE ORDER BY PO_REQ_NO DESC, SEQ_ORD_ID DESC END ELSE BEGIN SELECT TOP 25  PO_REQ_NO, SEQ_ORD_ID, ITEM_ID, ITEM_DESC, VEND_ITEM_ID, VEND_ITEM_DESC, VEND_ID, VEND_NAME, COMMIT_AMT, PO_OR_REQ, DEX_ROW_ID FROM .ECM10003 WHERE PO_REQ_NO BETWEEN @PO_REQ_NO_RS AND @PO_REQ_NO_RE AND SEQ_ORD_ID BETWEEN @SEQ_ORD_ID_RS AND @SEQ_ORD_ID_RE ORDER BY PO_REQ_NO DESC, SEQ_ORD_ID DESC END set nocount off     
GO
GRANT EXECUTE ON  [dbo].[zDP_ECM10003L_1] TO [DYNGRP]
GO
