SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AHR2DI05SS_4] (@EMPID_I char(15), @DATEFILED_I datetime) AS  set nocount on SELECT TOP 1  EMPID_I, DATEFILED_I, DSCRIPTN, POINTS_I, CHANGES_I, DEX_ROW_ID FROM .AHR2DI05 WHERE EMPID_I = @EMPID_I AND DATEFILED_I = @DATEFILED_I ORDER BY EMPID_I ASC, DATEFILED_I DESC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AHR2DI05SS_4] TO [DYNGRP]
GO
