SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00105SS_2] (@CURNCYID char(15), @ITEMNMBR char(31)) AS  set nocount on SELECT TOP 1  ITEMNMBR, CURNCYID, CURRNIDX, DECPLCUR, LISTPRCE, DEX_ROW_ID FROM .IV00105 WHERE CURNCYID = @CURNCYID AND ITEMNMBR = @ITEMNMBR ORDER BY CURNCYID ASC, ITEMNMBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00105SS_2] TO [DYNGRP]
GO
