SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME_ErrorSS_1] (@SEQNUMBR int) AS /* 12.00.0311.000 */ set nocount on SELECT TOP 1  SEQNUMBR, ME_Error_Msg, ME_Dummy_File_Conversion, DEX_ROW_ID FROM .ME_Error WHERE SEQNUMBR = @SEQNUMBR ORDER BY SEQNUMBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME_ErrorSS_1] TO [DYNGRP]
GO
