SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRPS0400N_1] (@BS int, @PYSTPTBLID char(15), @PYSTPTBLID_RS char(15), @PYSTPTBLID_RE char(15)) AS  set nocount on IF @PYSTPTBLID_RS IS NULL BEGIN SELECT TOP 25  PYSTPTBLID, Pay_Step_Table_Desc, Pay_Step_Unit_Of_Pay, NOTEINDX, DEX_ROW_ID FROM .HRPS0400 WHERE ( PYSTPTBLID > @PYSTPTBLID ) ORDER BY PYSTPTBLID ASC END ELSE IF @PYSTPTBLID_RS = @PYSTPTBLID_RE BEGIN SELECT TOP 25  PYSTPTBLID, Pay_Step_Table_Desc, Pay_Step_Unit_Of_Pay, NOTEINDX, DEX_ROW_ID FROM .HRPS0400 WHERE PYSTPTBLID = @PYSTPTBLID_RS AND ( PYSTPTBLID > @PYSTPTBLID ) ORDER BY PYSTPTBLID ASC END ELSE BEGIN SELECT TOP 25  PYSTPTBLID, Pay_Step_Table_Desc, Pay_Step_Unit_Of_Pay, NOTEINDX, DEX_ROW_ID FROM .HRPS0400 WHERE PYSTPTBLID BETWEEN @PYSTPTBLID_RS AND @PYSTPTBLID_RE AND ( PYSTPTBLID > @PYSTPTBLID ) ORDER BY PYSTPTBLID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRPS0400N_1] TO [DYNGRP]
GO
