SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06002SI] (@DEPSTATGRP char(11), @STATIONID char(11), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC06002 (DEPSTATGRP, STATIONID) VALUES ( @DEPSTATGRP, @STATIONID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06002SI] TO [DYNGRP]
GO
