SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DTA00300SS_2] (@GROUPID char(15), @ACTINDX int) AS  set nocount on SELECT TOP 1  ACTINDX, GROUPID, DTA_Quantities, ACCTSTAT, DECPLQTY, DEX_ROW_ID FROM .DTA00300 WHERE GROUPID = @GROUPID AND ACTINDX = @ACTINDX ORDER BY GROUPID ASC, ACTINDX ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DTA00300SS_2] TO [DYNGRP]
GO
