SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00951UN_2] (@BS int, @PRDLINE char(21), @ITEMNMBR char(31), @PRDLINE_RS char(21), @ITEMNMBR_RS char(31), @PRDLINE_RE char(21), @ITEMNMBR_RE char(31)) AS  set nocount on IF @PRDLINE_RS IS NULL BEGIN SELECT TOP 25  UOMSCHDL, ITEMNMBR, METERED, RTRNABLE, PRDLINE, WARRCDE, MTBF, MTBI, MTTR, RETCOST, SVC_PM_Allowed, SVC_Contractible, SLRWARR, VENDORID, SVC_Use_CurrentCost, DEX_ROW_ID FROM .SVC00951 WHERE ( PRDLINE = @PRDLINE AND ITEMNMBR > @ITEMNMBR OR PRDLINE > @PRDLINE ) ORDER BY PRDLINE ASC, ITEMNMBR ASC, DEX_ROW_ID ASC END ELSE IF @PRDLINE_RS = @PRDLINE_RE BEGIN SELECT TOP 25  UOMSCHDL, ITEMNMBR, METERED, RTRNABLE, PRDLINE, WARRCDE, MTBF, MTBI, MTTR, RETCOST, SVC_PM_Allowed, SVC_Contractible, SLRWARR, VENDORID, SVC_Use_CurrentCost, DEX_ROW_ID FROM .SVC00951 WHERE PRDLINE = @PRDLINE_RS AND ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND ( PRDLINE = @PRDLINE AND ITEMNMBR > @ITEMNMBR OR PRDLINE > @PRDLINE ) ORDER BY PRDLINE ASC, ITEMNMBR ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  UOMSCHDL, ITEMNMBR, METERED, RTRNABLE, PRDLINE, WARRCDE, MTBF, MTBI, MTTR, RETCOST, SVC_PM_Allowed, SVC_Contractible, SLRWARR, VENDORID, SVC_Use_CurrentCost, DEX_ROW_ID FROM .SVC00951 WHERE PRDLINE BETWEEN @PRDLINE_RS AND @PRDLINE_RE AND ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND ( PRDLINE = @PRDLINE AND ITEMNMBR > @ITEMNMBR OR PRDLINE > @PRDLINE ) ORDER BY PRDLINE ASC, ITEMNMBR ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00951UN_2] TO [DYNGRP]
GO
