SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG40000SS_5] (@YEAR1 smallint, @GLPOSTDT datetime) AS  set nocount on SELECT TOP 1  aaGLHdrID, JRNENTRY, RCTRXSEQ, YEAR1, aaTRXType, aaGLTRXSource, aaTRXSource, GLPOSTDT, Ledger_ID, DEX_ROW_ID FROM .AAG40000 WHERE YEAR1 = @YEAR1 AND GLPOSTDT = @GLPOSTDT ORDER BY YEAR1 ASC, GLPOSTDT ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG40000SS_5] TO [DYNGRP]
GO
