SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IVC40101SS_1] (@DOCTYPE smallint) AS  set nocount on SELECT TOP 1  DOCTYPE, DOCTYABR, DOCTYNAM, INVCNMBR, SETUPKEY, DEX_ROW_ID FROM .IVC40101 WHERE DOCTYPE = @DOCTYPE ORDER BY DOCTYPE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IVC40101SS_1] TO [DYNGRP]
GO
