SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG50000SI] (@USERID char(15), @TRXBTCHSRC char(51), @aaSubLedgerHdrID int, @SERIES smallint, @DOCTYPE smallint, @DOCNUMBR char(21), @PSTGDATE datetime, @aaOrder int, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .AAG50000 (USERID, TRXBTCHSRC, aaSubLedgerHdrID, SERIES, DOCTYPE, DOCNUMBR, PSTGDATE, aaOrder) VALUES ( @USERID, @TRXBTCHSRC, @aaSubLedgerHdrID, @SERIES, @DOCTYPE, @DOCNUMBR, @PSTGDATE, @aaOrder) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG50000SI] TO [DYNGRP]
GO
