SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00307F_1] (@EQUIPID_RS int, @LNITMSEQ_RS int, @EQUIPID_RE int, @LNITMSEQ_RE int) AS  set nocount on IF @EQUIPID_RS IS NULL BEGIN SELECT TOP 25  EQUIPID, LNITMSEQ, TECHID, DEX_ROW_ID FROM .SVC00307 ORDER BY EQUIPID ASC, LNITMSEQ ASC END ELSE IF @EQUIPID_RS = @EQUIPID_RE BEGIN SELECT TOP 25  EQUIPID, LNITMSEQ, TECHID, DEX_ROW_ID FROM .SVC00307 WHERE EQUIPID = @EQUIPID_RS AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY EQUIPID ASC, LNITMSEQ ASC END ELSE BEGIN SELECT TOP 25  EQUIPID, LNITMSEQ, TECHID, DEX_ROW_ID FROM .SVC00307 WHERE EQUIPID BETWEEN @EQUIPID_RS AND @EQUIPID_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY EQUIPID ASC, LNITMSEQ ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00307F_1] TO [DYNGRP]
GO
