SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4690200N_1] (@BS int, @LNSEQNBR numeric(19,5), @LNSEQNBR_RS numeric(19,5), @LNSEQNBR_RE numeric(19,5)) AS /* 12.00.0270.000 */ set nocount on IF @LNSEQNBR_RS IS NULL BEGIN SELECT TOP 25  LNSEQNBR, BSSI_Tenant_Lease_Number, LOCNCODE, BSSI_Ground_Lease_Number, BSSI_Charge_ID, BSSI_Term, BSSI_Billing_Frequency, STRTTIME, ENDTIME, QUANTITY, DEX_ROW_ID FROM .B4690200 WHERE ( LNSEQNBR > @LNSEQNBR ) ORDER BY LNSEQNBR ASC END ELSE IF @LNSEQNBR_RS = @LNSEQNBR_RE BEGIN SELECT TOP 25  LNSEQNBR, BSSI_Tenant_Lease_Number, LOCNCODE, BSSI_Ground_Lease_Number, BSSI_Charge_ID, BSSI_Term, BSSI_Billing_Frequency, STRTTIME, ENDTIME, QUANTITY, DEX_ROW_ID FROM .B4690200 WHERE LNSEQNBR = @LNSEQNBR_RS AND ( LNSEQNBR > @LNSEQNBR ) ORDER BY LNSEQNBR ASC END ELSE BEGIN SELECT TOP 25  LNSEQNBR, BSSI_Tenant_Lease_Number, LOCNCODE, BSSI_Ground_Lease_Number, BSSI_Charge_ID, BSSI_Term, BSSI_Billing_Frequency, STRTTIME, ENDTIME, QUANTITY, DEX_ROW_ID FROM .B4690200 WHERE LNSEQNBR BETWEEN @LNSEQNBR_RS AND @LNSEQNBR_RE AND ( LNSEQNBR > @LNSEQNBR ) ORDER BY LNSEQNBR ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4690200N_1] TO [DYNGRP]
GO
