SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV40201L_1] (@UOMSCHDL_RS char(11), @UOMSCHDL_RE char(11)) AS  set nocount on IF @UOMSCHDL_RS IS NULL BEGIN SELECT TOP 25  UOMSCHDL, UMSCHDSC, NOTEINDX, BASEUOFM, UMDPQTYS, DEX_ROW_TS, DEX_ROW_ID FROM .IV40201 ORDER BY UOMSCHDL DESC END ELSE IF @UOMSCHDL_RS = @UOMSCHDL_RE BEGIN SELECT TOP 25  UOMSCHDL, UMSCHDSC, NOTEINDX, BASEUOFM, UMDPQTYS, DEX_ROW_TS, DEX_ROW_ID FROM .IV40201 WHERE UOMSCHDL = @UOMSCHDL_RS ORDER BY UOMSCHDL DESC END ELSE BEGIN SELECT TOP 25  UOMSCHDL, UMSCHDSC, NOTEINDX, BASEUOFM, UMDPQTYS, DEX_ROW_TS, DEX_ROW_ID FROM .IV40201 WHERE UOMSCHDL BETWEEN @UOMSCHDL_RS AND @UOMSCHDL_RE ORDER BY UOMSCHDL DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV40201L_1] TO [DYNGRP]
GO
