SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM10902L_1] (@VCHRNMBR_RS char(21), @TAXDTLID_RS char(15), @ACTINDX_RS int, @VCHRNMBR_RE char(21), @TAXDTLID_RE char(15), @ACTINDX_RE int) AS  set nocount on IF @VCHRNMBR_RS IS NULL BEGIN SELECT TOP 25  VENDORID, VCHRNMBR, BACHNUMB, TAXDTLID, TAXAMNT, ACTINDX, TRXSORCE, CURNCYID, CURRNIDX, ORTAXAMT, DEX_ROW_ID FROM .PM10902 ORDER BY VCHRNMBR DESC, TAXDTLID DESC, ACTINDX DESC END ELSE IF @VCHRNMBR_RS = @VCHRNMBR_RE BEGIN SELECT TOP 25  VENDORID, VCHRNMBR, BACHNUMB, TAXDTLID, TAXAMNT, ACTINDX, TRXSORCE, CURNCYID, CURRNIDX, ORTAXAMT, DEX_ROW_ID FROM .PM10902 WHERE VCHRNMBR = @VCHRNMBR_RS AND TAXDTLID BETWEEN @TAXDTLID_RS AND @TAXDTLID_RE AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE ORDER BY VCHRNMBR DESC, TAXDTLID DESC, ACTINDX DESC END ELSE BEGIN SELECT TOP 25  VENDORID, VCHRNMBR, BACHNUMB, TAXDTLID, TAXAMNT, ACTINDX, TRXSORCE, CURNCYID, CURRNIDX, ORTAXAMT, DEX_ROW_ID FROM .PM10902 WHERE VCHRNMBR BETWEEN @VCHRNMBR_RS AND @VCHRNMBR_RE AND TAXDTLID BETWEEN @TAXDTLID_RS AND @TAXDTLID_RE AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE ORDER BY VCHRNMBR DESC, TAXDTLID DESC, ACTINDX DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM10902L_1] TO [DYNGRP]
GO
