SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00300SS_8] (@ITEMNMBR char(31), @LOCNCODE char(11), @QTYTYPE smallint, @MFGDATE datetime) AS  set nocount on SELECT TOP 1  ITEMNMBR, LOCNCODE, DATERECD, DTSEQNUM, LOTNUMBR, QTYRECVD, QTYSOLD, ATYALLOC, UNITCOST, RCTSEQNM, VNDRNMBR, LTNUMSLD, QTYTYPE, BIN, MFGDATE, EXPNDATE, DEX_ROW_ID FROM .IV00300 WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND QTYTYPE = @QTYTYPE AND MFGDATE = @MFGDATE ORDER BY ITEMNMBR ASC, LOCNCODE ASC, QTYTYPE ASC, MFGDATE ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00300SS_8] TO [DYNGRP]
GO
