SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR10309SS_1] (@PYRLCTYP smallint, @PYRLCNBR int) AS  set nocount on SELECT TOP 1  PYRLCTYP, PYRLCNBR, USERID, DEX_ROW_ID FROM .UPR10309 WHERE PYRLCTYP = @PYRLCTYP AND PYRLCNBR = @PYRLCNBR ORDER BY PYRLCTYP ASC, PYRLCNBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR10309SS_1] TO [DYNGRP]
GO
