SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00801SS_2] (@Keyword char(21), @LNITMSEQ int, @CALLNBR char(11)) AS  set nocount on SELECT TOP 1  SRVRECTYPE, CALLNBR, LNITMSEQ, Keyword, ENTDTE, USERID, DEX_ROW_ID FROM .SVC00801 WHERE Keyword = @Keyword AND LNITMSEQ = @LNITMSEQ AND CALLNBR = @CALLNBR ORDER BY Keyword ASC, LNITMSEQ ASC, CALLNBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00801SS_2] TO [DYNGRP]
GO
