SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00731SS_3] (@ORDDOCID char(15), @LNITMSEQ int, @POSTED tinyint, @SVC_Distribution_Type smallint) AS  set nocount on SELECT TOP 1  ORDDOCID, LNITMSEQ, SEQNUMBR, SVC_Distribution_Type, DistRef, ACTINDX, DEBITAMT, ORDBTAMT, CRDTAMNT, ORCRDAMT, CURRNIDX, TRXSORCE, POSTED, POSTEDDT, DEX_ROW_ID FROM .SVC00731 WHERE ORDDOCID = @ORDDOCID AND LNITMSEQ = @LNITMSEQ AND POSTED = @POSTED AND SVC_Distribution_Type = @SVC_Distribution_Type ORDER BY ORDDOCID ASC, LNITMSEQ ASC, POSTED ASC, SVC_Distribution_Type ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00731SS_3] TO [DYNGRP]
GO
