SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC40500SS_2] (@BUSALRTID char(15), @DBNAME char(11)) AS  set nocount on SELECT TOP 1  BARULEID, DSCRIPTN, BUSALRTID, EMAILMSG, LSTRWCHKD, INCLDRSLTS, DBNAME, CMPANYID, FREQTYPE, FREQINT, FRQSUBTYP, FRQSUBINT, FRQRELINT, FRQRCINT, STRTTIME, ENDTIME, STRTDATE, ENDDATE, CREATDDT, CRUSRID, MODIFDT, MDFUSRID, ENABLED, KEEPHIST, NMBRTIME, NOTEINDX, SCHEDTXT, DEX_ROW_ID FROM .SVC40500 WHERE BUSALRTID = @BUSALRTID AND DBNAME = @DBNAME ORDER BY BUSALRTID ASC, DBNAME ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC40500SS_2] TO [DYNGRP]
GO
