SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4601100N_1] (@BS int, @BSSI_TenantTypeID char(25), @BSSI_TenantTypeID_RS char(25), @BSSI_TenantTypeID_RE char(25)) AS /* 12.00.0270.000 */ set nocount on IF @BSSI_TenantTypeID_RS IS NULL BEGIN SELECT TOP 25  BSSI_TenantTypeID, BSSI_Description, NOTEINDX, DEX_ROW_ID FROM .B4601100 WHERE ( BSSI_TenantTypeID > @BSSI_TenantTypeID ) ORDER BY BSSI_TenantTypeID ASC END ELSE IF @BSSI_TenantTypeID_RS = @BSSI_TenantTypeID_RE BEGIN SELECT TOP 25  BSSI_TenantTypeID, BSSI_Description, NOTEINDX, DEX_ROW_ID FROM .B4601100 WHERE BSSI_TenantTypeID = @BSSI_TenantTypeID_RS AND ( BSSI_TenantTypeID > @BSSI_TenantTypeID ) ORDER BY BSSI_TenantTypeID ASC END ELSE BEGIN SELECT TOP 25  BSSI_TenantTypeID, BSSI_Description, NOTEINDX, DEX_ROW_ID FROM .B4601100 WHERE BSSI_TenantTypeID BETWEEN @BSSI_TenantTypeID_RS AND @BSSI_TenantTypeID_RE AND ( BSSI_TenantTypeID > @BSSI_TenantTypeID ) ORDER BY BSSI_TenantTypeID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4601100N_1] TO [DYNGRP]
GO
