SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP00100SS_1] (@PRCHLDID char(15)) AS  set nocount on SELECT TOP 1  PRCHLDID, DSCRIPTN, PASSWORD, XFERPHOL, POSTPHOL, FUFIPHOL, PRINPHOL, WORKFLOWHOLD, NOTEINDX, USER2ENT, CREATDDT, MODIFDT, DEX_ROW_ID FROM .SOP00100 WHERE PRCHLDID = @PRCHLDID ORDER BY PRCHLDID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP00100SS_1] TO [DYNGRP]
GO
