SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV10403SI] (@PRCSHID char(15), @EPITMTYP char(1), @ITEMNMBR char(31), @UOFM char(9), @FREEITEM char(31), @FREEUOFM char(9), @MAXQTYFR numeric(19,5), @QTYFROM numeric(19,5), @QTYTO numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .IV10403 (PRCSHID, EPITMTYP, ITEMNMBR, UOFM, FREEITEM, FREEUOFM, MAXQTYFR, QTYFROM, QTYTO) VALUES ( @PRCSHID, @EPITMTYP, @ITEMNMBR, @UOFM, @FREEITEM, @FREEUOFM, @MAXQTYFR, @QTYFROM, @QTYTO) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV10403SI] TO [DYNGRP]
GO
