SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG00401VSS_2] (@DEX_ROW_ID int) AS  set nocount on SELECT TOP 1  aaTrxDimID, aaTrxDimCodeID, aaNode, DEX_ROW_ID FROM .AAG00401V WHERE DEX_ROW_ID = @DEX_ROW_ID ORDER BY DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG00401VSS_2] TO [DYNGRP]
GO
