SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_TAST0432SI] (@YEAR1 smallint, @ANAC tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .TAST0432 (YEAR1, ANAC) VALUES ( @YEAR1, @ANAC) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_TAST0432SI] TO [DYNGRP]
GO
