SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM80950SS_1] (@BCHSOURC char(15), @BACHNUMB char(15), @SEQNUMBR int, @PMNTNMBR char(21), @Email_Type smallint) AS  set nocount on SELECT TOP 1  BACHNUMB, BCHSOURC, PMNTNMBR, SEQNUMBR, DOCDATE, DOCNUMBR, VENDORID, VENDNAME, VNDCHKNM, CURNCYID, VOIDED, DOCTYPE, CHKCOMNT, USERID, SEPRMTNC, ERROR, Email_Type, DOCAMNT, PYMTTYPE, Electronic, DEX_ROW_ID FROM .PM80950 WHERE BCHSOURC = @BCHSOURC AND BACHNUMB = @BACHNUMB AND SEQNUMBR = @SEQNUMBR AND PMNTNMBR = @PMNTNMBR AND Email_Type = @Email_Type ORDER BY BCHSOURC ASC, BACHNUMB ASC, SEQNUMBR ASC, PMNTNMBR ASC, Email_Type ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM80950SS_1] TO [DYNGRP]
GO
