SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRPppc01SI] (@POSITIONCODE_I char(7), @PAYRCORD char(7), @TABLE_I smallint, @ROW_I smallint, @COL_I smallint, @ROWMED_I smallint, @COLMED_I smallint, @ROWHIGH_I smallint, @COLHIGH_I smallint, @COMPENSATIONPERIOD_I smallint, @NOTESINDEX_I numeric(19,5), @CHANGEBY_I char(15), @CHANGEDATE_I datetime, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .HRPppc01 (POSITIONCODE_I, PAYRCORD, TABLE_I, ROW_I, COL_I, ROWMED_I, COLMED_I, ROWHIGH_I, COLHIGH_I, COMPENSATIONPERIOD_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I) VALUES ( @POSITIONCODE_I, @PAYRCORD, @TABLE_I, @ROW_I, @COL_I, @ROWMED_I, @COLMED_I, @ROWHIGH_I, @COLHIGH_I, @COMPENSATIONPERIOD_I, @NOTESINDEX_I, @CHANGEBY_I, @CHANGEDATE_I) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRPppc01SI] TO [DYNGRP]
GO
