SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG60002SI] (@USERID char(15), @TRXBTCHSRC char(51), @aaGLWorkHdrID int, @aaGLWorkDistID int, @aaGLWorkAssignID int, @DEBITAMT numeric(19,5), @SERIES smallint, @CRDTAMNT numeric(19,5), @ORDBTAMT numeric(19,5), @ORCRDAMT numeric(19,5), @DistRef char(31), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .AAG60002 (USERID, TRXBTCHSRC, aaGLWorkHdrID, aaGLWorkDistID, aaGLWorkAssignID, DEBITAMT, SERIES, CRDTAMNT, ORDBTAMT, ORCRDAMT, DistRef) VALUES ( @USERID, @TRXBTCHSRC, @aaGLWorkHdrID, @aaGLWorkDistID, @aaGLWorkAssignID, @DEBITAMT, @SERIES, @CRDTAMNT, @ORDBTAMT, @ORCRDAMT, @DistRef) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG60002SI] TO [DYNGRP]
GO
