SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HR2DIV02L_1] (@DIVISIONCODE_I_RS char(7), @DIVISIONCODE_I_RE char(7)) AS  set nocount on IF @DIVISIONCODE_I_RS IS NULL BEGIN SELECT TOP 25  COMPANYCODE_I, DIVISIONCODE_I, DIVISION_I, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE_I, PHONE10_I, EXT_I, FAXNUMBERI_I, EMAILADDRESS_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .HR2DIV02 ORDER BY DIVISIONCODE_I DESC END ELSE IF @DIVISIONCODE_I_RS = @DIVISIONCODE_I_RE BEGIN SELECT TOP 25  COMPANYCODE_I, DIVISIONCODE_I, DIVISION_I, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE_I, PHONE10_I, EXT_I, FAXNUMBERI_I, EMAILADDRESS_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .HR2DIV02 WHERE DIVISIONCODE_I = @DIVISIONCODE_I_RS ORDER BY DIVISIONCODE_I DESC END ELSE BEGIN SELECT TOP 25  COMPANYCODE_I, DIVISIONCODE_I, DIVISION_I, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE_I, PHONE10_I, EXT_I, FAXNUMBERI_I, EMAILADDRESS_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .HR2DIV02 WHERE DIVISIONCODE_I BETWEEN @DIVISIONCODE_I_RS AND @DIVISIONCODE_I_RE ORDER BY DIVISIONCODE_I DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2DIV02L_1] TO [DYNGRP]
GO
