SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00104SI] (@ITEMNMBR char(31), @SEQNUMBR int, @CMPTITNM char(31), @CMPITUOM char(9), @CMPITQTY numeric(19,5), @CMPSERNM tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .IV00104 (ITEMNMBR, SEQNUMBR, CMPTITNM, CMPITUOM, CMPITQTY, CMPSERNM) VALUES ( @ITEMNMBR, @SEQNUMBR, @CMPTITNM, @CMPITUOM, @CMPITQTY, @CMPSERNM) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00104SI] TO [DYNGRP]
GO
