SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06103SI] (@WORECTYPE smallint, @WORKORDNUM char(11), @STATIONID char(11), @Status smallint, @Route_Sequence numeric(19,5), @TECHID char(11), @STRTDATE datetime, @STRTTIME datetime, @ENDDATE datetime, @ENDTIME datetime, @NOTEINDX numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC06103 (WORECTYPE, WORKORDNUM, STATIONID, Status, Route_Sequence, TECHID, STRTDATE, STRTTIME, ENDDATE, ENDTIME, NOTEINDX) VALUES ( @WORECTYPE, @WORKORDNUM, @STATIONID, @Status, @Route_Sequence, @TECHID, @STRTDATE, @STRTTIME, @ENDDATE, @ENDTIME, @NOTEINDX) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06103SI] TO [DYNGRP]
GO
