SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00800N_1] (@BS int, @EMPLOYID char(15), @LOCALTAX char(7), @EMPLOYID_RS char(15), @LOCALTAX_RS char(7), @EMPLOYID_RE char(15), @LOCALTAX_RE char(7)) AS  set nocount on IF @EMPLOYID_RS IS NULL BEGIN SELECT TOP 25  EMPLOYID, LOCALTAX, LCLFGSTS, AULCLTAX, NUMOFEXM, INACTIVE, NOTEINDX, ADTLLOCWTHDNG, DEX_ROW_ID FROM .UPR00800 WHERE ( EMPLOYID = @EMPLOYID AND LOCALTAX > @LOCALTAX OR EMPLOYID > @EMPLOYID ) ORDER BY EMPLOYID ASC, LOCALTAX ASC END ELSE IF @EMPLOYID_RS = @EMPLOYID_RE BEGIN SELECT TOP 25  EMPLOYID, LOCALTAX, LCLFGSTS, AULCLTAX, NUMOFEXM, INACTIVE, NOTEINDX, ADTLLOCWTHDNG, DEX_ROW_ID FROM .UPR00800 WHERE EMPLOYID = @EMPLOYID_RS AND LOCALTAX BETWEEN @LOCALTAX_RS AND @LOCALTAX_RE AND ( EMPLOYID = @EMPLOYID AND LOCALTAX > @LOCALTAX OR EMPLOYID > @EMPLOYID ) ORDER BY EMPLOYID ASC, LOCALTAX ASC END ELSE BEGIN SELECT TOP 25  EMPLOYID, LOCALTAX, LCLFGSTS, AULCLTAX, NUMOFEXM, INACTIVE, NOTEINDX, ADTLLOCWTHDNG, DEX_ROW_ID FROM .UPR00800 WHERE EMPLOYID BETWEEN @EMPLOYID_RS AND @EMPLOYID_RE AND LOCALTAX BETWEEN @LOCALTAX_RS AND @LOCALTAX_RE AND ( EMPLOYID = @EMPLOYID AND LOCALTAX > @LOCALTAX OR EMPLOYID > @EMPLOYID ) ORDER BY EMPLOYID ASC, LOCALTAX ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00800N_1] TO [DYNGRP]
GO
