SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA01400SS_1] (@ASSETINDEX int, @PURCHLINESEQ int) AS  set nocount on SELECT TOP 1  ASSETINDEX, PURCHLINESEQ, PURCHDESC, Acquisition_Cost, Orig_Acquisition_Cost, VENDORID, DOCNUMBR, DOCDATE, TRXSORCE, ORCTRNUM, FA_AP_Post_Index, PORDNMBR, CURNCYID, CURRNIDX, XCHGRATE, EXCHDATE, TIME1, EXGTBLID, RATETPID, RTCLCMTD, DENXRATE, MCTRXSTT, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA01400 WHERE ASSETINDEX = @ASSETINDEX AND PURCHLINESEQ = @PURCHLINESEQ ORDER BY ASSETINDEX ASC, PURCHLINESEQ ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA01400SS_1] TO [DYNGRP]
GO
