SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM50505SS_2] (@TRX_ID char(19)) AS  set nocount on SELECT TOP 1  POSTEDDT, CUSTNMBR, TRXSORCE, ORTRXSRC, DOCNUMBR, STRVAL, TRX_ID, ACCTAMNT, RMDTYPAL, DEX_ROW_ID FROM .RM50505 WHERE TRX_ID = @TRX_ID ORDER BY TRX_ID ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM50505SS_2] TO [DYNGRP]
GO
