SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2900900SI] (@EMPLOYID char(15), @CUSTNMBR char(15), @VENDORID char(15), @CREATDDT datetime, @CRUSRID char(15), @MODIFDT datetime, @DEX_ROW_ID int OUT) AS /* 12.00.0270.000 */ set nocount on BEGIN INSERT INTO .B2900900 (EMPLOYID, CUSTNMBR, VENDORID, CREATDDT, CRUSRID, MODIFDT) VALUES ( @EMPLOYID, @CUSTNMBR, @VENDORID, @CREATDDT, @CRUSRID, @MODIFDT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2900900SI] TO [DYNGRP]
GO
