SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC05630SS_4] (@RTV_Number char(15), @POSTED tinyint, @SVC_Distribution_Type smallint, @ACTINDX int, @RTV_Line numeric(19,5), @SEQNUMBR int) AS  set nocount on SELECT TOP 1  RTV_Number, RTV_Line, LINITMTYP, SEQNUMBR, SVC_Distribution_Type, DistRef, ACTINDX, DEBITAMT, ORDBTAMT, CRDTAMNT, ORCRDAMT, CURRNIDX, TRXSORCE, POSTED, POSTEDDT, DEX_ROW_ID FROM .SVC05630 WHERE RTV_Number = @RTV_Number AND POSTED = @POSTED AND SVC_Distribution_Type = @SVC_Distribution_Type AND ACTINDX = @ACTINDX AND RTV_Line = @RTV_Line AND SEQNUMBR = @SEQNUMBR ORDER BY RTV_Number ASC, POSTED ASC, SVC_Distribution_Type ASC, ACTINDX ASC, RTV_Line ASC, SEQNUMBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC05630SS_4] TO [DYNGRP]
GO
