SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00211SD] (@EMPLOYID char(15), @ASSIGNMENTCODE char(15), @ASSIGNMENTTYPE smallint, @TIMECARDCODE char(7), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .UPR00211 WHERE EMPLOYID = @EMPLOYID AND ASSIGNMENTCODE = @ASSIGNMENTCODE AND ASSIGNMENTTYPE = @ASSIGNMENTTYPE AND TIMECARDCODE = @TIMECARDCODE AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .UPR00211 WHERE EMPLOYID = @EMPLOYID AND ASSIGNMENTCODE = @ASSIGNMENTCODE AND ASSIGNMENTTYPE = @ASSIGNMENTTYPE AND TIMECARDCODE = @TIMECARDCODE SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00211SD] TO [DYNGRP]
GO
