SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM30301SS_3] (@POSTEDDT datetime) AS  set nocount on SELECT TOP 1  TRXSORCE, POSTEDDT, DOCNUMBR, DISTTYPE, RMDTYPAL, SEQNUMBR, CUSTNMBR, DSTINDX, DEBITAMT, CRDTAMNT, PROJCTID, USERID, CATEGUSD, CURNCYID, CURRNIDX, ORCRDAMT, ORDBTAMT, DistRef, DEX_ROW_ID FROM .RM30301 WHERE POSTEDDT = @POSTEDDT ORDER BY POSTEDDT ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM30301SS_3] TO [DYNGRP]
GO
