SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06011SS_1] (@ROUTEID char(11), @SEQUENCE1 numeric(19,5)) AS  set nocount on SELECT TOP 1  ROUTEID, SEQUENCE1, DSCRIPTN, DEPSTATGRP, STATIONID, TECHID, ETTR, ROUTEPROC, SERVICEBOM, NOTEINDX, DEX_ROW_ID FROM .SVC06011 WHERE ROUTEID = @ROUTEID AND SEQUENCE1 = @SEQUENCE1 ORDER BY ROUTEID ASC, SEQUENCE1 ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06011SS_1] TO [DYNGRP]
GO
