SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00702VSI] (@ORDDOCID char(15), @LNITMSEQ int, @QTYTYPE smallint, @SERLTNUM char(21), @SERLTQTY numeric(19,5), @SLTSQNUM int, @ITEMNMBR char(31), @DATERECD datetime, @POSTED tinyint, @FROMBIN char(15), @TOBIN char(15), @Status smallint, @OVRSERLT smallint, @MFGDATE datetime, @EXPNDATE datetime, @UNITCOST numeric(19,5), @DTSEQNUM numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .IV00702V (ORDDOCID, LNITMSEQ, QTYTYPE, SERLTNUM, SERLTQTY, SLTSQNUM, ITEMNMBR, DATERECD, POSTED, FROMBIN, TOBIN, Status, OVRSERLT, MFGDATE, EXPNDATE, UNITCOST, DTSEQNUM) VALUES ( @ORDDOCID, @LNITMSEQ, @QTYTYPE, @SERLTNUM, @SERLTQTY, @SLTSQNUM, @ITEMNMBR, @DATERECD, @POSTED, @FROMBIN, @TOBIN, @Status, @OVRSERLT, @MFGDATE, @EXPNDATE, @UNITCOST, @DTSEQNUM) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00702VSI] TO [DYNGRP]
GO
