SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2900901F_1] (@EMPLOYID_RS char(15), @EMPLOYID_RE char(15)) AS /* 12.00.0270.000 */ set nocount on IF @EMPLOYID_RS IS NULL BEGIN SELECT TOP 25  EMPLOYID, BSSI_EnableLoanPayrollLi, DEX_ROW_ID FROM .B2900901 ORDER BY EMPLOYID ASC END ELSE IF @EMPLOYID_RS = @EMPLOYID_RE BEGIN SELECT TOP 25  EMPLOYID, BSSI_EnableLoanPayrollLi, DEX_ROW_ID FROM .B2900901 WHERE EMPLOYID = @EMPLOYID_RS ORDER BY EMPLOYID ASC END ELSE BEGIN SELECT TOP 25  EMPLOYID, BSSI_EnableLoanPayrollLi, DEX_ROW_ID FROM .B2900901 WHERE EMPLOYID BETWEEN @EMPLOYID_RS AND @EMPLOYID_RE ORDER BY EMPLOYID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2900901F_1] TO [DYNGRP]
GO
