SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4604001SS_3] (@BSSI_BTA_Rank int) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  BSSI_BTA_Number, BSSI_BTA_Name, BSSI_BTA_Rank, BSSI_BTA_Desc, NOTEINDX, DEX_ROW_ID FROM .B4604001 WHERE BSSI_BTA_Rank = @BSSI_BTA_Rank ORDER BY BSSI_BTA_Rank ASC, DEX_ROW_ID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4604001SS_3] TO [DYNGRP]
GO
