SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV50200SI] (@INCLUDEITEM tinyint, @ITEMNMBR char(31), @LOCNCODE char(11), @BINNMBR char(21), @ITMCLSCD char(11), @ABCCODE smallint, @ITMGEDSC char(11), @ITEMDESC char(101), @LSTCNTDT datetime, @STCKCNTINTRVL smallint, @NXTCNTDT datetime, @NXTCNTTM datetime, @UPDATED tinyint, @ITEMTYPE smallint, @USERID char(15), @IntegerValue smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .IV50200 (INCLUDEITEM, ITEMNMBR, LOCNCODE, BINNMBR, ITMCLSCD, ABCCODE, ITMGEDSC, ITEMDESC, LSTCNTDT, STCKCNTINTRVL, NXTCNTDT, NXTCNTTM, UPDATED, ITEMTYPE, USERID, IntegerValue) VALUES ( @INCLUDEITEM, @ITEMNMBR, @LOCNCODE, @BINNMBR, @ITMCLSCD, @ABCCODE, @ITMGEDSC, @ITEMDESC, @LSTCNTDT, @STCKCNTINTRVL, @NXTCNTDT, @NXTCNTTM, @UPDATED, @ITEMTYPE, @USERID, @IntegerValue) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV50200SI] TO [DYNGRP]
GO
