SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PA50105SS_5] (@DEX_ROW_ID int) AS  set nocount on SELECT TOP 1  USERID, DOCTYPE, DOCNUMBR, VCHRNMBR, MODULEID, DOCDATE, DUEDATE, CustVenID, CURTRXAM, ORCTRXAM, CURNCYID, VOIDSTTS, APPLDAMT, ORAPPAMT, DISTKNAM, ORDISTKN, DISAVTKN, ORDATKN, TAXDTLID, GSTDSAMT, PPSAMDED, DEX_ROW_ID FROM .PA50105 WHERE DEX_ROW_ID = @DEX_ROW_ID ORDER BY DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PA50105SS_5] TO [DYNGRP]
GO
