SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG00200FLUN_1] (@BS int, @ACTINDX int, @ACTINDX_RS int, @ACTINDX_RE int) AS  set nocount on IF @ACTINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, ACTNUMBR_1, ACTNUMBR_2, ACTNUMBR_3, ACTNUMBR_4, ACTNUMBR_5, strAccountNumber, ACTDESCR, ACCTTYPE, ACTIVE, DSCRIPTN, aaAcctClassID, aaAccountClass, aaAcctClassDescr, aaNode, aaDescr, aaTreeMain, PSTNGTYP, DEX_ROW_ID FROM .AAG00200FL WHERE ( ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END ELSE IF @ACTINDX_RS = @ACTINDX_RE BEGIN SELECT TOP 25  ACTINDX, ACTNUMBR_1, ACTNUMBR_2, ACTNUMBR_3, ACTNUMBR_4, ACTNUMBR_5, strAccountNumber, ACTDESCR, ACCTTYPE, ACTIVE, DSCRIPTN, aaAcctClassID, aaAccountClass, aaAcctClassDescr, aaNode, aaDescr, aaTreeMain, PSTNGTYP, DEX_ROW_ID FROM .AAG00200FL WHERE ACTINDX = @ACTINDX_RS AND ( ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  ACTINDX, ACTNUMBR_1, ACTNUMBR_2, ACTNUMBR_3, ACTNUMBR_4, ACTNUMBR_5, strAccountNumber, ACTDESCR, ACCTTYPE, ACTIVE, DSCRIPTN, aaAcctClassID, aaAccountClass, aaAcctClassDescr, aaNode, aaDescr, aaTreeMain, PSTNGTYP, DEX_ROW_ID FROM .AAG00200FL WHERE ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND ( ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG00200FLUN_1] TO [DYNGRP]
GO
