SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP40709SS_2] (@CURNCYID char(15), @PRCGRPID char(31)) AS  set nocount on SELECT TOP 1  PRCGRPID, CURNCYID, DECPLCUR, DEX_ROW_ID FROM .SOP40709 WHERE CURNCYID = @CURNCYID AND PRCGRPID = @PRCGRPID ORDER BY CURNCYID ASC, PRCGRPID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP40709SS_2] TO [DYNGRP]
GO
