SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL11000N_1] (@BS int, @BACHNUMB char(15), @ACTINDX int, @BACHNUMB_RS char(15), @ACTINDX_RS int, @BACHNUMB_RE char(15), @ACTINDX_RE int) AS  set nocount on IF @BACHNUMB_RS IS NULL BEGIN SELECT TOP 25  BACHNUMB, ACTINDX, TRXAMNT, DEX_ROW_ID FROM .GL11000 WHERE ( BACHNUMB = @BACHNUMB AND ACTINDX > @ACTINDX OR BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, ACTINDX ASC END ELSE IF @BACHNUMB_RS = @BACHNUMB_RE BEGIN SELECT TOP 25  BACHNUMB, ACTINDX, TRXAMNT, DEX_ROW_ID FROM .GL11000 WHERE BACHNUMB = @BACHNUMB_RS AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND ( BACHNUMB = @BACHNUMB AND ACTINDX > @ACTINDX OR BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, ACTINDX ASC END ELSE BEGIN SELECT TOP 25  BACHNUMB, ACTINDX, TRXAMNT, DEX_ROW_ID FROM .GL11000 WHERE BACHNUMB BETWEEN @BACHNUMB_RS AND @BACHNUMB_RE AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND ( BACHNUMB = @BACHNUMB AND ACTINDX > @ACTINDX OR BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, ACTINDX ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL11000N_1] TO [DYNGRP]
GO
