SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CAM40004SI] (@REFRENCE char(31), @SOURCDOC char(11), @CAMAccountType smallint, @BCHCOMNT char(61), @BACHNUMB char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .CAM40004 (REFRENCE, SOURCDOC, CAMAccountType, BCHCOMNT, BACHNUMB) VALUES ( @REFRENCE, @SOURCDOC, @CAMAccountType, @BCHCOMNT, @BACHNUMB) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CAM40004SI] TO [DYNGRP]
GO
