SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_TX00102SS_1] (@TAXSCHID char(15), @TAXDTLID char(15)) AS  set nocount on SELECT TOP 1  TAXSCHID, TAXDTLID, TXDTLBSE, TDTAXTAX, Auto_Calculate, DEX_ROW_ID FROM .TX00102 WHERE TAXSCHID = @TAXSCHID AND TAXDTLID = @TAXDTLID ORDER BY TAXSCHID ASC, TAXDTLID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_TX00102SS_1] TO [DYNGRP]
GO
