SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR40700F_2] (@DSCRIPTN_RS char(31), @WRKRCOMP_RS char(7), @DSCRIPTN_RE char(31), @WRKRCOMP_RE char(7)) AS  set nocount on IF @DSCRIPTN_RS IS NULL BEGIN SELECT TOP 25  WRKRCOMP, STATECD, DSCRIPTN, WKCMPMTH, WKCMPAMT, WKCMPUNT, WKCMPCNT, WCMOTMTH, WCWGLIMT, NOTEINDX, DEX_ROW_ID FROM .UPR40700 ORDER BY DSCRIPTN ASC, WRKRCOMP ASC END ELSE IF @DSCRIPTN_RS = @DSCRIPTN_RE BEGIN SELECT TOP 25  WRKRCOMP, STATECD, DSCRIPTN, WKCMPMTH, WKCMPAMT, WKCMPUNT, WKCMPCNT, WCMOTMTH, WCWGLIMT, NOTEINDX, DEX_ROW_ID FROM .UPR40700 WHERE DSCRIPTN = @DSCRIPTN_RS AND WRKRCOMP BETWEEN @WRKRCOMP_RS AND @WRKRCOMP_RE ORDER BY DSCRIPTN ASC, WRKRCOMP ASC END ELSE BEGIN SELECT TOP 25  WRKRCOMP, STATECD, DSCRIPTN, WKCMPMTH, WKCMPAMT, WKCMPUNT, WKCMPCNT, WCMOTMTH, WCWGLIMT, NOTEINDX, DEX_ROW_ID FROM .UPR40700 WHERE DSCRIPTN BETWEEN @DSCRIPTN_RS AND @DSCRIPTN_RE AND WRKRCOMP BETWEEN @WRKRCOMP_RS AND @WRKRCOMP_RE ORDER BY DSCRIPTN ASC, WRKRCOMP ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR40700F_2] TO [DYNGRP]
GO
