SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AF50100SD] (@USERID char(15), @PRCSSQNC smallint, @REPORTID smallint, @TOTRWNUM smallint, @STACCNDX int, @EDACCNDX int, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .AF50100 WHERE USERID = @USERID AND PRCSSQNC = @PRCSSQNC AND REPORTID = @REPORTID AND TOTRWNUM = @TOTRWNUM AND STACCNDX = @STACCNDX AND EDACCNDX = @EDACCNDX AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .AF50100 WHERE USERID = @USERID AND PRCSSQNC = @PRCSSQNC AND REPORTID = @REPORTID AND TOTRWNUM = @TOTRWNUM AND STACCNDX = @STACCNDX AND EDACCNDX = @EDACCNDX SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AF50100SD] TO [DYNGRP]
GO
