SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR10215SS_1] (@USERID char(15), @PYRNTYPE smallint, @EMPLOYID char(15), @PYADNMBR int) AS  set nocount on SELECT TOP 1  USERID, PYRNTYPE, EMPLOYID, PYADNMBR, RSNCHKVD, DEX_ROW_ID FROM .UPR10215 WHERE USERID = @USERID AND PYRNTYPE = @PYRNTYPE AND EMPLOYID = @EMPLOYID AND PYADNMBR = @PYADNMBR ORDER BY USERID ASC, PYRNTYPE ASC, EMPLOYID ASC, PYADNMBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR10215SS_1] TO [DYNGRP]
GO
