SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM00300SS_3] (@VENDORID char(15), @STATE char(29)) AS  set nocount on SELECT TOP 1  VENDORID, ADRSCODE, VNDCNTCT, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, COUNTRY, UPSZONE, PHNUMBR1, PHNUMBR2, PHONE3, FAXNUMBR, SHIPMTHD, TAXSCHID, EmailPOs, POEmailRecipient, EmailPOFormat, FaxPOs, POFaxNumber, FaxPOFormat, CCode, DECLID, DEX_ROW_TS, DEX_ROW_ID FROM .PM00300 WHERE VENDORID = @VENDORID AND STATE = @STATE ORDER BY VENDORID ASC, STATE ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM00300SS_3] TO [DYNGRP]
GO
