SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP00100L_1] (@PRCHLDID_RS char(15), @PRCHLDID_RE char(15)) AS  set nocount on IF @PRCHLDID_RS IS NULL BEGIN SELECT TOP 25  PRCHLDID, DSCRIPTN, PASSWORD, XFERPHOL, POSTPHOL, FUFIPHOL, PRINPHOL, WORKFLOWHOLD, NOTEINDX, USER2ENT, CREATDDT, MODIFDT, DEX_ROW_ID FROM .SOP00100 ORDER BY PRCHLDID DESC END ELSE IF @PRCHLDID_RS = @PRCHLDID_RE BEGIN SELECT TOP 25  PRCHLDID, DSCRIPTN, PASSWORD, XFERPHOL, POSTPHOL, FUFIPHOL, PRINPHOL, WORKFLOWHOLD, NOTEINDX, USER2ENT, CREATDDT, MODIFDT, DEX_ROW_ID FROM .SOP00100 WHERE PRCHLDID = @PRCHLDID_RS ORDER BY PRCHLDID DESC END ELSE BEGIN SELECT TOP 25  PRCHLDID, DSCRIPTN, PASSWORD, XFERPHOL, POSTPHOL, FUFIPHOL, PRINPHOL, WORKFLOWHOLD, NOTEINDX, USER2ENT, CREATDDT, MODIFDT, DEX_ROW_ID FROM .SOP00100 WHERE PRCHLDID BETWEEN @PRCHLDID_RS AND @PRCHLDID_RE ORDER BY PRCHLDID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP00100L_1] TO [DYNGRP]
GO
