SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AHR2DI04SI] (@EMPID_I char(15), @POINTS_I smallint, @BOOLEANFLAG_I tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .AHR2DI04 (EMPID_I, POINTS_I, BOOLEANFLAG_I) VALUES ( @EMPID_I, @POINTS_I, @BOOLEANFLAG_I) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AHR2DI04SI] TO [DYNGRP]
GO
