SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR19900SI] (@ISTIPPAY tinyint, @ACTINDX int, @ACCTAMNT numeric(19,5), @ACCTTYPE smallint, @STATECD char(3), @PAYRCORD char(7), @PAYTYPE smallint, @GROSWAGS_1 numeric(19,5), @GROSWAGS_2 numeric(19,5), @GROSWAGS_3 numeric(19,5), @GROSWAGS_4 numeric(19,5), @GROSWAGS_5 numeric(19,5), @GROSWAGS_6 numeric(19,5), @GROSWAGS_7 numeric(19,5), @GROSWAGS_8 numeric(19,5), @GROSWAGS_9 numeric(19,5), @GROSWAGS_10 numeric(19,5), @GROSWAGS_11 numeric(19,5), @GROSWAGS_12 numeric(19,5), @FFEDTXRT smallint, @FLSTTXRT smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .UPR19900 (ISTIPPAY, ACTINDX, ACCTAMNT, ACCTTYPE, STATECD, PAYRCORD, PAYTYPE, GROSWAGS_1, GROSWAGS_2, GROSWAGS_3, GROSWAGS_4, GROSWAGS_5, GROSWAGS_6, GROSWAGS_7, GROSWAGS_8, GROSWAGS_9, GROSWAGS_10, GROSWAGS_11, GROSWAGS_12, FFEDTXRT, FLSTTXRT) VALUES ( @ISTIPPAY, @ACTINDX, @ACCTAMNT, @ACCTTYPE, @STATECD, @PAYRCORD, @PAYTYPE, @GROSWAGS_1, @GROSWAGS_2, @GROSWAGS_3, @GROSWAGS_4, @GROSWAGS_5, @GROSWAGS_6, @GROSWAGS_7, @GROSWAGS_8, @GROSWAGS_9, @GROSWAGS_10, @GROSWAGS_11, @GROSWAGS_12, @FFEDTXRT, @FLSTTXRT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR19900SI] TO [DYNGRP]
GO
