SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_OR022330SS_1] (@ORSETUPCODE_I char(31), @SEQORDER_I smallint) AS  set nocount on SELECT TOP 1  ORSETUPCODE_I, SEQORDER_I, ORIENTATIONITEM_I, PERSONRESPONSIBLE_I, EVENTSTARTDATE_I, EVENTSTARTTIME_I, EVENTENDDATE_I, EVENTENDTIME_I, DEX_ROW_ID FROM .OR022330 WHERE ORSETUPCODE_I = @ORSETUPCODE_I AND SEQORDER_I = @SEQORDER_I ORDER BY ORSETUPCODE_I ASC, SEQORDER_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_OR022330SS_1] TO [DYNGRP]
GO
