SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_UPR30600SD] (@EMPLOYID char(15), @CREATDDT datetime, @CREATETIME datetime, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS /* 14.00.0084.000 */ set nocount on BEGIN IF @RID > 0 DELETE FROM .UPR30600 WHERE EMPLOYID = @EMPLOYID AND CREATDDT = @CREATDDT AND CREATETIME = @CREATETIME AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .UPR30600 WHERE EMPLOYID = @EMPLOYID AND CREATDDT = @CREATDDT AND CREATETIME = @CREATETIME SELECT @RowsAffected = @@rowcount END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR30600SD] TO [DYNGRP]
GO
