SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CAM40001L_1] (@SGMTNUMB_RS smallint, @SGMTNUMB_RE smallint) AS  set nocount on IF @SGMTNUMB_RS IS NULL BEGIN SELECT TOP 25  SGMTNUMB, CAM_Series, CAMActivated, CAM_Distribution_Created, CAM_Posted, BACHNUMB, BCHCOMNT, REFRENCE, TRXSRCPX, SOURCDOC, NOTEINDX, DEX_ROW_ID FROM .CAM40001 ORDER BY SGMTNUMB DESC END ELSE IF @SGMTNUMB_RS = @SGMTNUMB_RE BEGIN SELECT TOP 25  SGMTNUMB, CAM_Series, CAMActivated, CAM_Distribution_Created, CAM_Posted, BACHNUMB, BCHCOMNT, REFRENCE, TRXSRCPX, SOURCDOC, NOTEINDX, DEX_ROW_ID FROM .CAM40001 WHERE SGMTNUMB = @SGMTNUMB_RS ORDER BY SGMTNUMB DESC END ELSE BEGIN SELECT TOP 25  SGMTNUMB, CAM_Series, CAMActivated, CAM_Distribution_Created, CAM_Posted, BACHNUMB, BCHCOMNT, REFRENCE, TRXSRCPX, SOURCDOC, NOTEINDX, DEX_ROW_ID FROM .CAM40001 WHERE SGMTNUMB BETWEEN @SGMTNUMB_RS AND @SGMTNUMB_RE ORDER BY SGMTNUMB DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CAM40001L_1] TO [DYNGRP]
GO
