SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PT40100SI] (@SETUPKEY smallint, @USRDFPR1 char(15), @USRDRPR2 char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .PT40100 (SETUPKEY, USRDFPR1, USRDRPR2) VALUES ( @SETUPKEY, @USRDFPR1, @USRDRPR2) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PT40100SI] TO [DYNGRP]
GO
