SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RV020121SS_1] (@REVIEWSETUPCODE_I char(31)) AS  set nocount on SELECT TOP 1  REVIEWSETUPCODE_I, REVIEWSETUPNAME_I, REVIEWPREFERENCES_I, REVIEWRANGE_I, POSTTOTODO_I, TOTALWEIGHT_I, REVINTERVALPREFS_I, USEWORDSGB_I, DEX_ROW_ID FROM .RV020121 WHERE REVIEWSETUPCODE_I = @REVIEWSETUPCODE_I ORDER BY REVIEWSETUPCODE_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RV020121SS_1] TO [DYNGRP]
GO
