SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DTA00301N_2] (@BS int, @CODEID char(15), @ACTINDX int, @GROUPID char(15), @CODEID_RS char(15), @ACTINDX_RS int, @GROUPID_RS char(15), @CODEID_RE char(15), @ACTINDX_RE int, @GROUPID_RE char(15)) AS  set nocount on IF @CODEID_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, GROUPID, CODEID, POSTDESC, PERCENTAMOUNT, DEX_ROW_ID FROM .DTA00301 WHERE ( CODEID = @CODEID AND ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR CODEID = @CODEID AND ACTINDX > @ACTINDX OR CODEID > @CODEID ) ORDER BY CODEID ASC, ACTINDX ASC, GROUPID ASC END ELSE IF @CODEID_RS = @CODEID_RE BEGIN SELECT TOP 25  ACTINDX, GROUPID, CODEID, POSTDESC, PERCENTAMOUNT, DEX_ROW_ID FROM .DTA00301 WHERE CODEID = @CODEID_RS AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND GROUPID BETWEEN @GROUPID_RS AND @GROUPID_RE AND ( CODEID = @CODEID AND ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR CODEID = @CODEID AND ACTINDX > @ACTINDX OR CODEID > @CODEID ) ORDER BY CODEID ASC, ACTINDX ASC, GROUPID ASC END ELSE BEGIN SELECT TOP 25  ACTINDX, GROUPID, CODEID, POSTDESC, PERCENTAMOUNT, DEX_ROW_ID FROM .DTA00301 WHERE CODEID BETWEEN @CODEID_RS AND @CODEID_RE AND ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND GROUPID BETWEEN @GROUPID_RS AND @GROUPID_RE AND ( CODEID = @CODEID AND ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR CODEID = @CODEID AND ACTINDX > @ACTINDX OR CODEID > @CODEID ) ORDER BY CODEID ASC, ACTINDX ASC, GROUPID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DTA00301N_2] TO [DYNGRP]
GO
