SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00652SI] (@CONSTS smallint, @CONTNBR char(11), @LNSEQNBR numeric(19,5), @OPTTYPE char(11), @STRTDATE datetime, @ENDDATE datetime, @UNITPRCE numeric(19,5), @UNITCOST numeric(19,5), @ORUNTCST numeric(19,5), @ORUNTPRC numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00652 (CONSTS, CONTNBR, LNSEQNBR, OPTTYPE, STRTDATE, ENDDATE, UNITPRCE, UNITCOST, ORUNTCST, ORUNTPRC) VALUES ( @CONSTS, @CONTNBR, @LNSEQNBR, @OPTTYPE, @STRTDATE, @ENDDATE, @UNITPRCE, @UNITCOST, @ORUNTCST, @ORUNTPRC) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00652SI] TO [DYNGRP]
GO
