SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM00105L_1] (@CPRCSTNM_RS char(15), @CPRCSTNM_RE char(15)) AS  set nocount on IF @CPRCSTNM_RS IS NULL BEGIN SELECT TOP 25  CPRCSTNM, NAALLOWRECEIPTS, NACREDITCHECK, NAFINANCECHARGE, NAHOLDINACTIVE, NADEFPARENTVEN, NOTEINDX, CREATDDT, MODIFDT, DEX_ROW_ID FROM .RM00105 ORDER BY CPRCSTNM DESC END ELSE IF @CPRCSTNM_RS = @CPRCSTNM_RE BEGIN SELECT TOP 25  CPRCSTNM, NAALLOWRECEIPTS, NACREDITCHECK, NAFINANCECHARGE, NAHOLDINACTIVE, NADEFPARENTVEN, NOTEINDX, CREATDDT, MODIFDT, DEX_ROW_ID FROM .RM00105 WHERE CPRCSTNM = @CPRCSTNM_RS ORDER BY CPRCSTNM DESC END ELSE BEGIN SELECT TOP 25  CPRCSTNM, NAALLOWRECEIPTS, NACREDITCHECK, NAFINANCECHARGE, NAHOLDINACTIVE, NADEFPARENTVEN, NOTEINDX, CREATDDT, MODIFDT, DEX_ROW_ID FROM .RM00105 WHERE CPRCSTNM BETWEEN @CPRCSTNM_RS AND @CPRCSTNM_RE ORDER BY CPRCSTNM DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM00105L_1] TO [DYNGRP]
GO
