SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP10204F_1] (@SOPNUMBE_RS char(21), @SOPTYPE_RS smallint, @CMPNTSEQ_RS int, @LNITMSEQ_RS int, @SOPNUMBE_RE char(21), @SOPTYPE_RE smallint, @CMPNTSEQ_RE int, @LNITMSEQ_RE int) AS  set nocount on IF @SOPNUMBE_RS IS NULL BEGIN SELECT TOP 25  SOPNUMBE, SOPTYPE, CMPNTSEQ, LNITMSEQ, ITEMNMBR, PROMOSTS, PROMOTYP, PSITMVAL, FREEITEM, FREEUOFM, PRMCMSEQ, PRMLISEQ, DEX_ROW_ID FROM .SOP10204 ORDER BY SOPNUMBE ASC, SOPTYPE ASC, CMPNTSEQ ASC, LNITMSEQ ASC END ELSE IF @SOPNUMBE_RS = @SOPNUMBE_RE BEGIN SELECT TOP 25  SOPNUMBE, SOPTYPE, CMPNTSEQ, LNITMSEQ, ITEMNMBR, PROMOSTS, PROMOTYP, PSITMVAL, FREEITEM, FREEUOFM, PRMCMSEQ, PRMLISEQ, DEX_ROW_ID FROM .SOP10204 WHERE SOPNUMBE = @SOPNUMBE_RS AND SOPTYPE BETWEEN @SOPTYPE_RS AND @SOPTYPE_RE AND CMPNTSEQ BETWEEN @CMPNTSEQ_RS AND @CMPNTSEQ_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY SOPNUMBE ASC, SOPTYPE ASC, CMPNTSEQ ASC, LNITMSEQ ASC END ELSE BEGIN SELECT TOP 25  SOPNUMBE, SOPTYPE, CMPNTSEQ, LNITMSEQ, ITEMNMBR, PROMOSTS, PROMOTYP, PSITMVAL, FREEITEM, FREEUOFM, PRMCMSEQ, PRMLISEQ, DEX_ROW_ID FROM .SOP10204 WHERE SOPNUMBE BETWEEN @SOPNUMBE_RS AND @SOPNUMBE_RE AND SOPTYPE BETWEEN @SOPTYPE_RS AND @SOPTYPE_RE AND CMPNTSEQ BETWEEN @CMPNTSEQ_RS AND @CMPNTSEQ_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY SOPNUMBE ASC, SOPTYPE ASC, CMPNTSEQ ASC, LNITMSEQ ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP10204F_1] TO [DYNGRP]
GO
