SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00942SI] (@SRVCCD char(11), @TASKCD char(11), @TASKREQ tinyint, @TASKETTC char(7), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00942 (SRVCCD, TASKCD, TASKREQ, TASKETTC) VALUES ( @SRVCCD, @TASKCD, @TASKREQ, @TASKETTC) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00942SI] TO [DYNGRP]
GO
