SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100161SS_1] (@MODULE1 smallint, @VNDCLSID char(11), @DISTTYPE smallint, @BSSI_DistDeferralActIdx int) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  MODULE1, VNDCLSID, DISTTYPE, BSSI_Recog_TemplateID, ACTINDX, BSSI_DistDeferralActIdx, DEX_ROW_ID FROM .B7100161 WHERE MODULE1 = @MODULE1 AND VNDCLSID = @VNDCLSID AND DISTTYPE = @DISTTYPE AND BSSI_DistDeferralActIdx = @BSSI_DistDeferralActIdx ORDER BY MODULE1 ASC, VNDCLSID ASC, DISTTYPE ASC, BSSI_DistDeferralActIdx ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100161SS_1] TO [DYNGRP]
GO
