SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR10103SS_1] (@RPTNGYR smallint, @EMPLOYID char(15)) AS  set nocount on SELECT TOP 1  RPTNGYR, LASTNAME, FRSTNAME, MIDLNAME, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, EMPLOYID, SOCSCNUM, DEPRTMNT, GROSDIST, TXBAMNDT, TAMD1099, TOTDSTCB, CAPTLGAIN, FEDITXWH, EMPLECTR, NTREALAP, DSTCODE1, DSTCODE2, DSTCODE3, IRASEPCB, OTAM1099, OTPC1099, TTLTDSTPC, STATWGS1, STATWGS2, STAINTX1, STAINTX2, STATECD1, STATECD2, ESTIDNR1, ESTIDBR2, LCLWGES1, LCLWGS2, LCLINTX1, LCLINTX2, LCLCODE1, LCLCODE2, Y1099RFC, EMPLSUFF, DEX_ROW_ID FROM .UPR10103 WHERE RPTNGYR = @RPTNGYR AND EMPLOYID = @EMPLOYID ORDER BY RPTNGYR ASC, EMPLOYID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR10103SS_1] TO [DYNGRP]
GO
