SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06301SS_1] (@DATE1 datetime, @TIME1 datetime) AS  set nocount on SELECT TOP 1  DATE1, TIME1, Status, STRTDATE, STRTTIME, ENDDATE, ENDTIME, DEX_ROW_ID FROM .SVC06301 WHERE DATE1 = @DATE1 AND TIME1 = @TIME1 ORDER BY DATE1 ASC, TIME1 ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06301SS_1] TO [DYNGRP]
GO
