SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AHRTA230SS_1] (@EMPID_I char(15), @TIMECODE_I char(7), @YEAR1 smallint) AS  set nocount on SELECT TOP 1  EMPID_I, TIMECODE_I, YEAR1, HOURSAVAILABLE_I, DEX_ROW_ID FROM .AHRTA230 WHERE EMPID_I = @EMPID_I AND TIMECODE_I = @TIMECODE_I AND YEAR1 = @YEAR1 ORDER BY EMPID_I ASC, TIMECODE_I ASC, YEAR1 ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AHRTA230SS_1] TO [DYNGRP]
GO
