SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM40401F_2] (@SETUPKEY_RS smallint, @SETUPKEY_RE smallint) AS  set nocount on IF @SETUPKEY_RS IS NULL BEGIN SELECT TOP 25  RMDTYPAL, DOCDESCR, DOCABREV, DOCNUMBR, SETUPKEY, DEX_ROW_ID FROM .RM40401 ORDER BY SETUPKEY ASC, DEX_ROW_ID ASC END ELSE IF @SETUPKEY_RS = @SETUPKEY_RE BEGIN SELECT TOP 25  RMDTYPAL, DOCDESCR, DOCABREV, DOCNUMBR, SETUPKEY, DEX_ROW_ID FROM .RM40401 WHERE SETUPKEY = @SETUPKEY_RS ORDER BY SETUPKEY ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  RMDTYPAL, DOCDESCR, DOCABREV, DOCNUMBR, SETUPKEY, DEX_ROW_ID FROM .RM40401 WHERE SETUPKEY BETWEEN @SETUPKEY_RS AND @SETUPKEY_RE ORDER BY SETUPKEY ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM40401F_2] TO [DYNGRP]
GO
