SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM00204SS_2] (@YEAR1 smallint, @PERIODID smallint, @VENDORID char(15), @TEN99TYPE smallint, @TEN99BOXNUMBER smallint) AS  set nocount on SELECT TOP 1  VENDORID, TEN99TYPE, YEAR1, PERIODID, TEN99BOXNUMBER, TEN99AMNT, TEN99FRNORUSDTL, TEN99STATECD, TEN99STATIDNUM, TEN99TAXEXMTCUSIPNUM, TEN99DIRSALECB, TEN99STATNMBR, DEX_ROW_ID FROM .PM00204 WHERE YEAR1 = @YEAR1 AND PERIODID = @PERIODID AND VENDORID = @VENDORID AND TEN99TYPE = @TEN99TYPE AND TEN99BOXNUMBER = @TEN99BOXNUMBER ORDER BY YEAR1 ASC, PERIODID ASC, VENDORID ASC, TEN99TYPE ASC, TEN99BOXNUMBER ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM00204SS_2] TO [DYNGRP]
GO
