SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AF40109SS_1] (@FLDPRNAM char(81)) AS  set nocount on SELECT TOP 1  FLDPRNAM, DEX_ROW_ID, FLDPCTUR FROM .AF40109 WHERE FLDPRNAM = @FLDPRNAM ORDER BY FLDPRNAM ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AF40109SS_1] TO [DYNGRP]
GO
