SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06004L_1] (@ANALCODE_RS char(11), @ANALCODE_RE char(11)) AS  set nocount on IF @ANALCODE_RS IS NULL BEGIN SELECT TOP 25  ANALCODE, DSCRIPTN, ROUTEID, DEX_ROW_ID FROM .SVC06004 ORDER BY ANALCODE DESC END ELSE IF @ANALCODE_RS = @ANALCODE_RE BEGIN SELECT TOP 25  ANALCODE, DSCRIPTN, ROUTEID, DEX_ROW_ID FROM .SVC06004 WHERE ANALCODE = @ANALCODE_RS ORDER BY ANALCODE DESC END ELSE BEGIN SELECT TOP 25  ANALCODE, DSCRIPTN, ROUTEID, DEX_ROW_ID FROM .SVC06004 WHERE ANALCODE BETWEEN @ANALCODE_RS AND @ANALCODE_RE ORDER BY ANALCODE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06004L_1] TO [DYNGRP]
GO
