SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100910SS_2] (@SEQNUMBR int) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  SEQNUMBR, BSSI_User_Def_Field, DEX_ROW_ID FROM .B7100910 WHERE SEQNUMBR = @SEQNUMBR ORDER BY SEQNUMBR ASC, DEX_ROW_ID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100910SS_2] TO [DYNGRP]
GO
