SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_RM30502UN_4] (@BS int, @BACHNUMB char(15), @BACHNUMB_RS char(15), @BACHNUMB_RE char(15)) AS /* 14.00.0084.000 */ set nocount on IF @BACHNUMB_RS IS NULL BEGIN SELECT TOP 25  NOTEINDX, GLPOSTDT, TRXSORCE, BCHSOURC, BACHNUMB, REPRNTNT, TRXMISNG, CHEKBKID, NUMOFTRX, BACHFREQ, BCHCOMNT, USERID, APPROVL, APPRVLDT, APRVLUSERID, CNTRLTOT, CNTRLTRX, BCHTOTAL, Workflow_Approval_Status, Workflow_Priority, Workflow_Status, CREATDDT, TIME1, DEX_ROW_ID FROM .RM30502 WHERE ( BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, DEX_ROW_ID ASC END ELSE IF @BACHNUMB_RS = @BACHNUMB_RE BEGIN SELECT TOP 25  NOTEINDX, GLPOSTDT, TRXSORCE, BCHSOURC, BACHNUMB, REPRNTNT, TRXMISNG, CHEKBKID, NUMOFTRX, BACHFREQ, BCHCOMNT, USERID, APPROVL, APPRVLDT, APRVLUSERID, CNTRLTOT, CNTRLTRX, BCHTOTAL, Workflow_Approval_Status, Workflow_Priority, Workflow_Status, CREATDDT, TIME1, DEX_ROW_ID FROM .RM30502 WHERE BACHNUMB = @BACHNUMB_RS AND ( BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  NOTEINDX, GLPOSTDT, TRXSORCE, BCHSOURC, BACHNUMB, REPRNTNT, TRXMISNG, CHEKBKID, NUMOFTRX, BACHFREQ, BCHCOMNT, USERID, APPROVL, APPRVLDT, APRVLUSERID, CNTRLTOT, CNTRLTRX, BCHTOTAL, Workflow_Approval_Status, Workflow_Priority, Workflow_Status, CREATDDT, TIME1, DEX_ROW_ID FROM .RM30502 WHERE BACHNUMB BETWEEN @BACHNUMB_RS AND @BACHNUMB_RE AND ( BACHNUMB > @BACHNUMB ) ORDER BY BACHNUMB ASC, DEX_ROW_ID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_RM30502UN_4] TO [DYNGRP]
GO
