SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP00101F_1] (@BUYERID_RS char(15), @BUYERID_RE char(15)) AS  set nocount on IF @BUYERID_RS IS NULL BEGIN SELECT TOP 25  BUYERID, DSCRIPTN, NOTEINDX, DEX_ROW_ID FROM .POP00101 ORDER BY BUYERID ASC END ELSE IF @BUYERID_RS = @BUYERID_RE BEGIN SELECT TOP 25  BUYERID, DSCRIPTN, NOTEINDX, DEX_ROW_ID FROM .POP00101 WHERE BUYERID = @BUYERID_RS ORDER BY BUYERID ASC END ELSE BEGIN SELECT TOP 25  BUYERID, DSCRIPTN, NOTEINDX, DEX_ROW_ID FROM .POP00101 WHERE BUYERID BETWEEN @BUYERID_RS AND @BUYERID_RE ORDER BY BUYERID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP00101F_1] TO [DYNGRP]
GO
