SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B9000999SS_1] (@SCHEDULE_NUMBER char(21), @Schedule_Payment_Number smallint, @DOCNUMBR char(21), @USERID char(15)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  SCHEDULE_NUMBER, Schedule_Payment_Number, LNITMSEQ, DOCNUMBR, USERID, BSSI_RecalculateInterest, BSSI_Billing_Start_Date, BSSI_Billing_End_Date, PRINCIPAL_BALANCE, CHRGAMNT, DEX_ROW_ID FROM .B9000999 WHERE SCHEDULE_NUMBER = @SCHEDULE_NUMBER AND Schedule_Payment_Number = @Schedule_Payment_Number AND DOCNUMBR = @DOCNUMBR AND USERID = @USERID ORDER BY SCHEDULE_NUMBER ASC, Schedule_Payment_Number ASC, DOCNUMBR ASC, USERID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B9000999SS_1] TO [DYNGRP]
GO
