SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL50500SS_1] (@USERID char(15), @ORD int, @SGMNTID char(67), @Ledger_ID smallint, @CURNCYID char(15), @TranslationCurrencyID char(15)) AS  set nocount on SELECT TOP 1  USERID, ORD, SGMNTID, Ledger_ID, CURNCYID, TranslationCurrencyID, CURRNIDX, DECPLCUR, RATETPID, EXGTBLID, XCHGRATE, RTCLCMTD, DENXRATE, MCTRXSTT, CurrencyTranslationType, REARNAMT, ORIGAMT, Translation_Amount, RERINDX, DEX_ROW_ID FROM .GL50500 WHERE USERID = @USERID AND ORD = @ORD AND SGMNTID = @SGMNTID AND Ledger_ID = @Ledger_ID AND CURNCYID = @CURNCYID AND TranslationCurrencyID = @TranslationCurrencyID ORDER BY USERID ASC, ORD ASC, SGMNTID ASC, Ledger_ID ASC, CURNCYID ASC, TranslationCurrencyID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL50500SS_1] TO [DYNGRP]
GO
