SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL00104L_3] (@BDNINDX_RS int, @BDNINDX_RE int) AS  set nocount on IF @BDNINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, SEPRATR1, DSTINDX, SEPRATR2, BDNINDX, DEX_ROW_ID FROM .GL00104 ORDER BY BDNINDX DESC, DEX_ROW_ID DESC END ELSE IF @BDNINDX_RS = @BDNINDX_RE BEGIN SELECT TOP 25  ACTINDX, SEPRATR1, DSTINDX, SEPRATR2, BDNINDX, DEX_ROW_ID FROM .GL00104 WHERE BDNINDX = @BDNINDX_RS ORDER BY BDNINDX DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  ACTINDX, SEPRATR1, DSTINDX, SEPRATR2, BDNINDX, DEX_ROW_ID FROM .GL00104 WHERE BDNINDX BETWEEN @BDNINDX_RS AND @BDNINDX_RE ORDER BY BDNINDX DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL00104L_3] TO [DYNGRP]
GO
