SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MS273534L_1] (@BACHNUMB_RS char(15), @BCHSOURC_RS char(15), @BACHNUMB_RE char(15), @BCHSOURC_RE char(15)) AS /* 12.00.0311.000 */ set nocount on IF @BACHNUMB_RS IS NULL BEGIN SELECT TOP 25  BACHNUMB, BCHSOURC, DEX_ROW_ID FROM .MS273534 ORDER BY BACHNUMB DESC, BCHSOURC DESC END ELSE IF @BACHNUMB_RS = @BACHNUMB_RE BEGIN SELECT TOP 25  BACHNUMB, BCHSOURC, DEX_ROW_ID FROM .MS273534 WHERE BACHNUMB = @BACHNUMB_RS AND BCHSOURC BETWEEN @BCHSOURC_RS AND @BCHSOURC_RE ORDER BY BACHNUMB DESC, BCHSOURC DESC END ELSE BEGIN SELECT TOP 25  BACHNUMB, BCHSOURC, DEX_ROW_ID FROM .MS273534 WHERE BACHNUMB BETWEEN @BACHNUMB_RS AND @BACHNUMB_RE AND BCHSOURC BETWEEN @BCHSOURC_RS AND @BCHSOURC_RE ORDER BY BACHNUMB DESC, BCHSOURC DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MS273534L_1] TO [DYNGRP]
GO
