SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_EXT20502F_1] (@Extender_View_ID_RS char(15), @LNITMSEQ_RS int, @Field_ID_RS int, @Extender_View_ID_RE char(15), @LNITMSEQ_RE int, @Field_ID_RE int) AS /* 12.00.0311.000 */ set nocount on IF @Extender_View_ID_RS IS NULL BEGIN SELECT TOP 25  Extender_View_ID, LNITMSEQ, Field_ID, FIELDNAM, DEX_ROW_ID FROM .EXT20502 ORDER BY Extender_View_ID ASC, LNITMSEQ ASC, Field_ID ASC END ELSE IF @Extender_View_ID_RS = @Extender_View_ID_RE BEGIN SELECT TOP 25  Extender_View_ID, LNITMSEQ, Field_ID, FIELDNAM, DEX_ROW_ID FROM .EXT20502 WHERE Extender_View_ID = @Extender_View_ID_RS AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE AND Field_ID BETWEEN @Field_ID_RS AND @Field_ID_RE ORDER BY Extender_View_ID ASC, LNITMSEQ ASC, Field_ID ASC END ELSE BEGIN SELECT TOP 25  Extender_View_ID, LNITMSEQ, Field_ID, FIELDNAM, DEX_ROW_ID FROM .EXT20502 WHERE Extender_View_ID BETWEEN @Extender_View_ID_RS AND @Extender_View_ID_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE AND Field_ID BETWEEN @Field_ID_RS AND @Field_ID_RE ORDER BY Extender_View_ID ASC, LNITMSEQ ASC, Field_ID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_EXT20502F_1] TO [DYNGRP]
GO
