SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4699706SS_1] (@SOPNUMBE char(21), @SOPTYPE smallint, @CMPNTSEQ int, @LNITMSEQ int, @LNSEQNBR numeric(19,5)) AS /* 12.00.0311.000 */ set nocount on SELECT TOP 1  SOPTYPE, SOPNUMBE, CMPNTSEQ, LNITMSEQ, LNSEQNBR, BSSI_PortfolioID, BSSI_Tenant_Lease_Number, BSSI_LeaseTypeID, LOCNCODE, BSSI_Charge_ID, BSSI_Sales_Amount, STRTDATE, ENDDATE, BSSI_Dummy, DEX_ROW_ID FROM .B4699706 WHERE SOPNUMBE = @SOPNUMBE AND SOPTYPE = @SOPTYPE AND CMPNTSEQ = @CMPNTSEQ AND LNITMSEQ = @LNITMSEQ AND LNSEQNBR = @LNSEQNBR ORDER BY SOPNUMBE ASC, SOPTYPE ASC, CMPNTSEQ ASC, LNITMSEQ ASC, LNSEQNBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4699706SS_1] TO [DYNGRP]
GO
