SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00210L_1] (@EMPLOYID_RS char(15), @ASSIGNMENTCODE_RS char(15), @EMPLOYID_RE char(15), @ASSIGNMENTCODE_RE char(15)) AS  set nocount on IF @EMPLOYID_RS IS NULL BEGIN SELECT TOP 25  EMPLOYID, ASSIGNMENTCODE, INACTIVE, DEX_ROW_ID FROM .UPR00210 ORDER BY EMPLOYID DESC, ASSIGNMENTCODE DESC END ELSE IF @EMPLOYID_RS = @EMPLOYID_RE BEGIN SELECT TOP 25  EMPLOYID, ASSIGNMENTCODE, INACTIVE, DEX_ROW_ID FROM .UPR00210 WHERE EMPLOYID = @EMPLOYID_RS AND ASSIGNMENTCODE BETWEEN @ASSIGNMENTCODE_RS AND @ASSIGNMENTCODE_RE ORDER BY EMPLOYID DESC, ASSIGNMENTCODE DESC END ELSE BEGIN SELECT TOP 25  EMPLOYID, ASSIGNMENTCODE, INACTIVE, DEX_ROW_ID FROM .UPR00210 WHERE EMPLOYID BETWEEN @EMPLOYID_RS AND @EMPLOYID_RE AND ASSIGNMENTCODE BETWEEN @ASSIGNMENTCODE_RS AND @ASSIGNMENTCODE_RE ORDER BY EMPLOYID DESC, ASSIGNMENTCODE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00210L_1] TO [DYNGRP]
GO
