SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC40500L_1] (@BARULEID_RS int, @BARULEID_RE int) AS  set nocount on IF @BARULEID_RS IS NULL BEGIN SELECT TOP 25  BARULEID, DSCRIPTN, BUSALRTID, EMAILMSG, LSTRWCHKD, INCLDRSLTS, DBNAME, CMPANYID, FREQTYPE, FREQINT, FRQSUBTYP, FRQSUBINT, FRQRELINT, FRQRCINT, STRTTIME, ENDTIME, STRTDATE, ENDDATE, CREATDDT, CRUSRID, MODIFDT, MDFUSRID, ENABLED, KEEPHIST, NMBRTIME, NOTEINDX, SCHEDTXT, DEX_ROW_ID FROM .SVC40500 ORDER BY BARULEID DESC END ELSE IF @BARULEID_RS = @BARULEID_RE BEGIN SELECT TOP 25  BARULEID, DSCRIPTN, BUSALRTID, EMAILMSG, LSTRWCHKD, INCLDRSLTS, DBNAME, CMPANYID, FREQTYPE, FREQINT, FRQSUBTYP, FRQSUBINT, FRQRELINT, FRQRCINT, STRTTIME, ENDTIME, STRTDATE, ENDDATE, CREATDDT, CRUSRID, MODIFDT, MDFUSRID, ENABLED, KEEPHIST, NMBRTIME, NOTEINDX, SCHEDTXT, DEX_ROW_ID FROM .SVC40500 WHERE BARULEID = @BARULEID_RS ORDER BY BARULEID DESC END ELSE BEGIN SELECT TOP 25  BARULEID, DSCRIPTN, BUSALRTID, EMAILMSG, LSTRWCHKD, INCLDRSLTS, DBNAME, CMPANYID, FREQTYPE, FREQINT, FRQSUBTYP, FRQSUBINT, FRQRELINT, FRQRCINT, STRTTIME, ENDTIME, STRTDATE, ENDDATE, CREATDDT, CRUSRID, MODIFDT, MDFUSRID, ENABLED, KEEPHIST, NMBRTIME, NOTEINDX, SCHEDTXT, DEX_ROW_ID FROM .SVC40500 WHERE BARULEID BETWEEN @BARULEID_RS AND @BARULEID_RE ORDER BY BARULEID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC40500L_1] TO [DYNGRP]
GO
