SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP10109SS_1] (@PRCBKID char(15)) AS  set nocount on SELECT TOP 1  PRCBKID, DESCEXPR, ISBASE, NOTEINDX, DEX_ROW_ID FROM .SOP10109 WHERE PRCBKID = @PRCBKID ORDER BY PRCBKID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP10109SS_1] TO [DYNGRP]
GO
