SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP40703SI] (@USERID char(15), @CUSTNMBR char(15), @ITEMNMBR char(31), @UOFM char(9), @QTYFROM numeric(19,5), @QTYTO numeric(19,5), @UNITPRCE numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SOP40703 (USERID, CUSTNMBR, ITEMNMBR, UOFM, QTYFROM, QTYTO, UNITPRCE) VALUES ( @USERID, @CUSTNMBR, @ITEMNMBR, @UOFM, @QTYFROM, @QTYTO, @UNITPRCE) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP40703SI] TO [DYNGRP]
GO
