SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM30700SS_1] (@VCHRNMBR char(21), @TAXDTLID char(15), @ACTINDX int) AS  set nocount on SELECT TOP 1  VENDORID, VCHRNMBR, DOCTYPE, BACHNUMB, TAXDTLID, BKOUTTAX, TAXAMNT, ORTAXAMT, PCTAXAMT, ORPURTAX, FRTTXAMT, ORFRTTAX, MSCTXAMT, ORMSCTAX, ACTINDX, TRXSORCE, TDTTXPUR, ORTXBPUR, TXDTTPUR, ORTOTPUR, CURRNIDX, DEX_ROW_ID FROM .PM30700 WHERE VCHRNMBR = @VCHRNMBR AND TAXDTLID = @TAXDTLID AND ACTINDX = @ACTINDX ORDER BY VCHRNMBR ASC, TAXDTLID ASC, ACTINDX ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM30700SS_1] TO [DYNGRP]
GO
