SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CPO10114SS_1] (@ACTINDX int, @YEAR1 smallint, @PERIODID smallint) AS  set nocount on SELECT TOP 1  YEAR1, PERIODID, ACTINDX, DEBITAMT, CRDTAMNT, DEX_ROW_ID FROM .CPO10114 WHERE ACTINDX = @ACTINDX AND YEAR1 = @YEAR1 AND PERIODID = @PERIODID ORDER BY ACTINDX ASC, YEAR1 ASC, PERIODID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CPO10114SS_1] TO [DYNGRP]
GO
