SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PC40306SS_2] (@PLANCODE char(15), @JOBTITLE char(7), @STRTDATE datetime) AS  set nocount on SELECT TOP 1  PLANCODE, JOBTITLE, SEQNUMBR, DSCRIPTN, STRTDATE, ENDDATE, BUDGETPLANAMT, DEX_ROW_ID FROM .PC40306 WHERE PLANCODE = @PLANCODE AND JOBTITLE = @JOBTITLE AND STRTDATE = @STRTDATE ORDER BY PLANCODE ASC, JOBTITLE ASC, STRTDATE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PC40306SS_2] TO [DYNGRP]
GO
