SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_RM30502SS_2] (@TRXSORCE char(13)) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  NOTEINDX, GLPOSTDT, TRXSORCE, BCHSOURC, BACHNUMB, REPRNTNT, TRXMISNG, CHEKBKID, NUMOFTRX, BACHFREQ, BCHCOMNT, USERID, APPROVL, APPRVLDT, APRVLUSERID, CNTRLTOT, CNTRLTRX, BCHTOTAL, Workflow_Approval_Status, Workflow_Priority, Workflow_Status, CREATDDT, TIME1, DEX_ROW_ID FROM .RM30502 WHERE TRXSORCE = @TRXSORCE ORDER BY TRXSORCE ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_RM30502SS_2] TO [DYNGRP]
GO
