SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA10200SS_3] (@USERID char(15), @GROUPNAME char(15), @ASSETDESC char(41), @ASSETID char(15), @ASSETIDSUF smallint) AS  set nocount on SELECT TOP 1  USERID, GROUPNAME, ASSETINDEX, ASSETID, ASSETIDSUF, ASSETDESC, ASSETCLASSID, LOCATNID, STRUCTUREID, ASSETSTATUS, Asset_Label, Physical_Location_ID, DEX_ROW_ID FROM .FA10200 WHERE USERID = @USERID AND GROUPNAME = @GROUPNAME AND ASSETDESC = @ASSETDESC AND ASSETID = @ASSETID AND ASSETIDSUF = @ASSETIDSUF ORDER BY USERID ASC, GROUPNAME ASC, ASSETDESC ASC, ASSETID ASC, ASSETIDSUF ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA10200SS_3] TO [DYNGRP]
GO
