SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CFM10301L_1] (@DUEDATE_RS datetime, @DUEDATE_RE datetime) AS  set nocount on IF @DUEDATE_RS IS NULL BEGIN SELECT TOP 25  CUSTNMBR, DOCNUMBR, RMDTYPAL, DUEDATE, DOCDATE, DOCAMNT, ACCTAMNT, TRXDSCRN, DEX_ROW_ID FROM .CFM10301 ORDER BY DUEDATE DESC, DEX_ROW_ID DESC END ELSE IF @DUEDATE_RS = @DUEDATE_RE BEGIN SELECT TOP 25  CUSTNMBR, DOCNUMBR, RMDTYPAL, DUEDATE, DOCDATE, DOCAMNT, ACCTAMNT, TRXDSCRN, DEX_ROW_ID FROM .CFM10301 WHERE DUEDATE = @DUEDATE_RS ORDER BY DUEDATE DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  CUSTNMBR, DOCNUMBR, RMDTYPAL, DUEDATE, DOCDATE, DOCAMNT, ACCTAMNT, TRXDSCRN, DEX_ROW_ID FROM .CFM10301 WHERE DUEDATE BETWEEN @DUEDATE_RS AND @DUEDATE_RE ORDER BY DUEDATE DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CFM10301L_1] TO [DYNGRP]
GO
