SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM10504SI] (@RMDTYPAL smallint, @DOCNUMBR char(21), @SALSTERR char(15), @SLPRSNID char(15), @CUSTNMBR char(15), @COMDLRAM numeric(19,5), @NCOMAMNT numeric(19,5), @COMPRCNT smallint, @PRCTOSAL smallint, @SLSAMNT numeric(19,5), @COMTRSRC char(13), @ORCOMAMT numeric(19,5), @ORNCMAMT numeric(19,5), @ORSLSAMT numeric(19,5), @CURRNIDX smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .RM10504 (RMDTYPAL, DOCNUMBR, SALSTERR, SLPRSNID, CUSTNMBR, COMDLRAM, NCOMAMNT, COMPRCNT, PRCTOSAL, SLSAMNT, COMTRSRC, ORCOMAMT, ORNCMAMT, ORSLSAMT, CURRNIDX) VALUES ( @RMDTYPAL, @DOCNUMBR, @SALSTERR, @SLPRSNID, @CUSTNMBR, @COMDLRAM, @NCOMAMNT, @COMPRCNT, @PRCTOSAL, @SLSAMNT, @COMTRSRC, @ORCOMAMT, @ORNCMAMT, @ORSLSAMT, @CURRNIDX) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM10504SI] TO [DYNGRP]
GO
