SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG00603F_3] (@USERID_RS char(15), @aaLevel_RS int, @aaOrder_RS int, @USERID_RE char(15), @aaLevel_RE int, @aaOrder_RE int) AS  set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  USERID, aaNodeID, aaNode, aaLevel, aaParentNodeID, aaOrder, NOTEINDX, Status, DEX_ROW_ID FROM .AAG00603 ORDER BY USERID ASC, aaLevel ASC, aaOrder ASC, DEX_ROW_ID ASC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  USERID, aaNodeID, aaNode, aaLevel, aaParentNodeID, aaOrder, NOTEINDX, Status, DEX_ROW_ID FROM .AAG00603 WHERE USERID = @USERID_RS AND aaLevel BETWEEN @aaLevel_RS AND @aaLevel_RE AND aaOrder BETWEEN @aaOrder_RS AND @aaOrder_RE ORDER BY USERID ASC, aaLevel ASC, aaOrder ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  USERID, aaNodeID, aaNode, aaLevel, aaParentNodeID, aaOrder, NOTEINDX, Status, DEX_ROW_ID FROM .AAG00603 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE AND aaLevel BETWEEN @aaLevel_RS AND @aaLevel_RE AND aaOrder BETWEEN @aaOrder_RS AND @aaOrder_RE ORDER BY USERID ASC, aaLevel ASC, aaOrder ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG00603F_3] TO [DYNGRP]
GO
