SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP30330SS_2] (@ITEMNMBR char(31), @SERLTNUM char(21)) AS  set nocount on SELECT TOP 1  POPRCTNM, RCPTLNNM, SLTSQNUM, SERLTNUM, SERLTQTY, DATERECD, DTSEQNUM, UNITCOST, TRXSORCE, ITEMNMBR, QTYTYPE, BIN, MFGDATE, EXPNDATE, DEX_ROW_ID FROM .POP30330 WHERE ITEMNMBR = @ITEMNMBR AND SERLTNUM = @SERLTNUM ORDER BY ITEMNMBR ASC, SERLTNUM ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP30330SS_2] TO [DYNGRP]
GO
