SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV10201F_3] (@ITEMNMBR_RS char(31), @RCTSEQNM_RS int, @PCHSRCTY_RS smallint, @ITEMNMBR_RE char(31), @RCTSEQNM_RE int, @PCHSRCTY_RE smallint) AS  set nocount on IF @ITEMNMBR_RS IS NULL BEGIN SELECT TOP 25  ITEMNMBR, TRXLOCTN, QTYTYPE, DOCDATE, RCTSEQNM, ORIGINDOCTYPE, ORIGINDOCID, LNSEQNBR, CMPNTSEQ, QTYSOLD, UNITCOST, IVIVINDX, IVIVOFIX, SRCRCTSEQNM, TRXREFERENCE, PCHSRCTY, DEX_ROW_ID FROM .IV10201 ORDER BY ITEMNMBR ASC, RCTSEQNM ASC, PCHSRCTY ASC END ELSE IF @ITEMNMBR_RS = @ITEMNMBR_RE BEGIN SELECT TOP 25  ITEMNMBR, TRXLOCTN, QTYTYPE, DOCDATE, RCTSEQNM, ORIGINDOCTYPE, ORIGINDOCID, LNSEQNBR, CMPNTSEQ, QTYSOLD, UNITCOST, IVIVINDX, IVIVOFIX, SRCRCTSEQNM, TRXREFERENCE, PCHSRCTY, DEX_ROW_ID FROM .IV10201 WHERE ITEMNMBR = @ITEMNMBR_RS AND RCTSEQNM BETWEEN @RCTSEQNM_RS AND @RCTSEQNM_RE AND PCHSRCTY BETWEEN @PCHSRCTY_RS AND @PCHSRCTY_RE ORDER BY ITEMNMBR ASC, RCTSEQNM ASC, PCHSRCTY ASC END ELSE BEGIN SELECT TOP 25  ITEMNMBR, TRXLOCTN, QTYTYPE, DOCDATE, RCTSEQNM, ORIGINDOCTYPE, ORIGINDOCID, LNSEQNBR, CMPNTSEQ, QTYSOLD, UNITCOST, IVIVINDX, IVIVOFIX, SRCRCTSEQNM, TRXREFERENCE, PCHSRCTY, DEX_ROW_ID FROM .IV10201 WHERE ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND RCTSEQNM BETWEEN @RCTSEQNM_RS AND @RCTSEQNM_RE AND PCHSRCTY BETWEEN @PCHSRCTY_RS AND @PCHSRCTY_RE ORDER BY ITEMNMBR ASC, RCTSEQNM ASC, PCHSRCTY ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV10201F_3] TO [DYNGRP]
GO
