SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP10800F_2] (@PONUMBER_RS char(17), @POPRCTNM_RS char(17), @PONUMBER_RE char(17), @POPRCTNM_RE char(17)) AS  set nocount on IF @PONUMBER_RS IS NULL BEGIN SELECT TOP 25  POPRCTNM, PONUMBER, PMNTNMBR, APPLDAMT, ORAPPAMT, DISTKNAM, ORDISTKN, PrepaymentAccountIndex, PrepaymentAmount, OriginatingPrepaymentAmt, PSTGSTUS, BACHNUMB, BCHSOURC, TRXSORCE, GLPOSTDT, VOIDED, DEX_ROW_ID FROM .POP10800 ORDER BY PONUMBER ASC, POPRCTNM ASC END ELSE IF @PONUMBER_RS = @PONUMBER_RE BEGIN SELECT TOP 25  POPRCTNM, PONUMBER, PMNTNMBR, APPLDAMT, ORAPPAMT, DISTKNAM, ORDISTKN, PrepaymentAccountIndex, PrepaymentAmount, OriginatingPrepaymentAmt, PSTGSTUS, BACHNUMB, BCHSOURC, TRXSORCE, GLPOSTDT, VOIDED, DEX_ROW_ID FROM .POP10800 WHERE PONUMBER = @PONUMBER_RS AND POPRCTNM BETWEEN @POPRCTNM_RS AND @POPRCTNM_RE ORDER BY PONUMBER ASC, POPRCTNM ASC END ELSE BEGIN SELECT TOP 25  POPRCTNM, PONUMBER, PMNTNMBR, APPLDAMT, ORAPPAMT, DISTKNAM, ORDISTKN, PrepaymentAccountIndex, PrepaymentAmount, OriginatingPrepaymentAmt, PSTGSTUS, BACHNUMB, BCHSOURC, TRXSORCE, GLPOSTDT, VOIDED, DEX_ROW_ID FROM .POP10800 WHERE PONUMBER BETWEEN @PONUMBER_RS AND @PONUMBER_RE AND POPRCTNM BETWEEN @POPRCTNM_RS AND @POPRCTNM_RE ORDER BY PONUMBER ASC, POPRCTNM ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP10800F_2] TO [DYNGRP]
GO
