SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR10209SS_1] (@USERID char(15), @PYRNTYPE smallint, @EMPLOYID char(15), @TRXNUMBER int, @ACTINDX int, @SEQNUMBR int) AS  set nocount on SELECT TOP 1  USERID, EMPLOYID, PYRNTYPE, PYRLRTYP, TRXNUMBER, SEQNUMBR, ACTINDX, AMNTOPST, CHEKNMBR, POSTEDDT, DEPRTMNT, JOBTITLE, PAYROLCD, UPRACTYP, PYADNMBR, DEX_ROW_ID FROM .UPR10209 WHERE USERID = @USERID AND PYRNTYPE = @PYRNTYPE AND EMPLOYID = @EMPLOYID AND TRXNUMBER = @TRXNUMBER AND ACTINDX = @ACTINDX AND SEQNUMBR = @SEQNUMBR ORDER BY USERID ASC, PYRNTYPE ASC, EMPLOYID ASC, TRXNUMBER ASC, ACTINDX ASC, SEQNUMBR ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR10209SS_1] TO [DYNGRP]
GO
