SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00942SS_1] (@SRVCCD char(11), @TASKCD char(11)) AS  set nocount on SELECT TOP 1  SRVCCD, TASKCD, TASKREQ, TASKETTC, DEX_ROW_ID FROM .SVC00942 WHERE SRVCCD = @SRVCCD AND TASKCD = @TASKCD ORDER BY SRVCCD ASC, TASKCD ASC set nocount off  
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00942SS_1] TO [DYNGRP]
GO
