SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_MN010000SS_1] (@NOTEINDX numeric(19,5)) AS  set nocount on SELECT TOP 1  NOTEINDX, DATE1, TIME1, USERID, DEX_ROW_ID, NOTETEXT_I FROM .MN010000 WHERE NOTEINDX = @NOTEINDX ORDER BY NOTEINDX ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_MN010000SS_1] TO [DYNGRP]
GO
