SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00995SS_1] (@OFFID char(11)) AS  set nocount on SELECT TOP 1  OFFID, ENTDTE, ENTTME, ESCSTATUS, TRXQTY, WAITTME, DEX_ROW_ID FROM .SVC00995 WHERE OFFID = @OFFID ORDER BY OFFID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00995SS_1] TO [DYNGRP]
GO
