SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRREV032SI] (@REVIEWSETUPCODE_I char(31), @REVINTLTITLES_I char(31), @REVINTSEQUENCE_I smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .HRREV032 (REVIEWSETUPCODE_I, REVINTLTITLES_I, REVINTSEQUENCE_I) VALUES ( @REVIEWSETUPCODE_I, @REVINTLTITLES_I, @REVINTSEQUENCE_I) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRREV032SI] TO [DYNGRP]
GO
