SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE PROCEDURE [dbo].[SVC_Move_Service_Calls]  @SRVRECTYPE smallint,  @OLDTECHID char(11),  @TECHID char(11) AS  UPDATE SVC00200  SET TECHID = @TECHID  WHERE  SVC00200.SRVRECTYPE = @SRVRECTYPE  AND SVC00200.TECHID = @OLDTECHID    
GO
GRANT EXECUTE ON  [dbo].[SVC_Move_Service_Calls] TO [DYNGRP]
GO
