SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM30202SS_1] (@APTODCTY smallint, @APTODCNM char(21)) AS  set nocount on SELECT TOP 1  CUSTNMBR, APTODCNM, APTODCTY, APPTOAMT, APFRDCNM, APFRDCTY, APFRDCDT, TRXSORCE, DISTKNAM, WROFAMNT, DATE1, GLPOSTDT, POSTED, GSTDSAMT, PPSAMDED, TAXDTLID, ORAPTOAM, ORDISTKN, ORDATKN, ORWROFAM, RLGANLOS, DEX_ROW_ID FROM .RM30202 WHERE APTODCTY = @APTODCTY AND APTODCNM = @APTODCNM ORDER BY APTODCTY ASC, APTODCNM ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM30202SS_1] TO [DYNGRP]
GO
