SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4640048F_1] (@LOCNCODE_RS char(11), @BSSI_Meter_Number_RS char(25), @LOCNCODE_RE char(11), @BSSI_Meter_Number_RE char(25)) AS /* 12.00.0270.000 */ set nocount on IF @LOCNCODE_RS IS NULL BEGIN SELECT TOP 25  LOCNCODE, BSSI_Meter_Number, DEX_ROW_ID FROM .B4640048 ORDER BY LOCNCODE ASC, BSSI_Meter_Number ASC END ELSE IF @LOCNCODE_RS = @LOCNCODE_RE BEGIN SELECT TOP 25  LOCNCODE, BSSI_Meter_Number, DEX_ROW_ID FROM .B4640048 WHERE LOCNCODE = @LOCNCODE_RS AND BSSI_Meter_Number BETWEEN @BSSI_Meter_Number_RS AND @BSSI_Meter_Number_RE ORDER BY LOCNCODE ASC, BSSI_Meter_Number ASC END ELSE BEGIN SELECT TOP 25  LOCNCODE, BSSI_Meter_Number, DEX_ROW_ID FROM .B4640048 WHERE LOCNCODE BETWEEN @LOCNCODE_RS AND @LOCNCODE_RE AND BSSI_Meter_Number BETWEEN @BSSI_Meter_Number_RS AND @BSSI_Meter_Number_RE ORDER BY LOCNCODE ASC, BSSI_Meter_Number ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4640048F_1] TO [DYNGRP]
GO
