SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SK020230SI] (@Query_Index smallint, @SKILLNUMBER_I smallint, @POINTS_I smallint, @GB_I smallint, @SKILLTITLE_I char(31), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SK020230 (Query_Index, SKILLNUMBER_I, POINTS_I, GB_I, SKILLTITLE_I) VALUES ( @Query_Index, @SKILLNUMBER_I, @POINTS_I, @GB_I, @SKILLTITLE_I) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SK020230SI] TO [DYNGRP]
GO
