SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CFM00101N_1] (@BS int, @EBS_Forecast_ID char(15), @CHEKBKID char(15), @EBS_Forecast_ID_RS char(15), @CHEKBKID_RS char(15), @EBS_Forecast_ID_RE char(15), @CHEKBKID_RE char(15)) AS  set nocount on IF @EBS_Forecast_ID_RS IS NULL BEGIN SELECT TOP 25  EBS_Forecast_ID, CHEKBKID, CFM_Exchange_Rate, CFM_Calc_Method, DEX_ROW_ID FROM .CFM00101 WHERE ( EBS_Forecast_ID = @EBS_Forecast_ID AND CHEKBKID > @CHEKBKID OR EBS_Forecast_ID > @EBS_Forecast_ID ) ORDER BY EBS_Forecast_ID ASC, CHEKBKID ASC END ELSE IF @EBS_Forecast_ID_RS = @EBS_Forecast_ID_RE BEGIN SELECT TOP 25  EBS_Forecast_ID, CHEKBKID, CFM_Exchange_Rate, CFM_Calc_Method, DEX_ROW_ID FROM .CFM00101 WHERE EBS_Forecast_ID = @EBS_Forecast_ID_RS AND CHEKBKID BETWEEN @CHEKBKID_RS AND @CHEKBKID_RE AND ( EBS_Forecast_ID = @EBS_Forecast_ID AND CHEKBKID > @CHEKBKID OR EBS_Forecast_ID > @EBS_Forecast_ID ) ORDER BY EBS_Forecast_ID ASC, CHEKBKID ASC END ELSE BEGIN SELECT TOP 25  EBS_Forecast_ID, CHEKBKID, CFM_Exchange_Rate, CFM_Calc_Method, DEX_ROW_ID FROM .CFM00101 WHERE EBS_Forecast_ID BETWEEN @EBS_Forecast_ID_RS AND @EBS_Forecast_ID_RE AND CHEKBKID BETWEEN @CHEKBKID_RS AND @CHEKBKID_RE AND ( EBS_Forecast_ID = @EBS_Forecast_ID AND CHEKBKID > @CHEKBKID OR EBS_Forecast_ID > @EBS_Forecast_ID ) ORDER BY EBS_Forecast_ID ASC, CHEKBKID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CFM00101N_1] TO [DYNGRP]
GO
