SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00115L_3] (@ITEMNMBR_RS char(31), @MANUFACTURER_RS char(31), @MNFCTRITMNMBR_RS char(31), @ITEMNMBR_RE char(31), @MANUFACTURER_RE char(31), @MNFCTRITMNMBR_RE char(31)) AS  set nocount on IF @ITEMNMBR_RS IS NULL BEGIN SELECT TOP 25  ITEMNMBR, MANUFACTURER, MNFCTRITMNMBR, ITEMDESC, PRIMARYITEM, DEX_ROW_ID FROM .IV00115 ORDER BY ITEMNMBR DESC, MANUFACTURER DESC, MNFCTRITMNMBR DESC, DEX_ROW_ID DESC END ELSE IF @ITEMNMBR_RS = @ITEMNMBR_RE BEGIN SELECT TOP 25  ITEMNMBR, MANUFACTURER, MNFCTRITMNMBR, ITEMDESC, PRIMARYITEM, DEX_ROW_ID FROM .IV00115 WHERE ITEMNMBR = @ITEMNMBR_RS AND MANUFACTURER BETWEEN @MANUFACTURER_RS AND @MANUFACTURER_RE AND MNFCTRITMNMBR BETWEEN @MNFCTRITMNMBR_RS AND @MNFCTRITMNMBR_RE ORDER BY ITEMNMBR DESC, MANUFACTURER DESC, MNFCTRITMNMBR DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  ITEMNMBR, MANUFACTURER, MNFCTRITMNMBR, ITEMDESC, PRIMARYITEM, DEX_ROW_ID FROM .IV00115 WHERE ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND MANUFACTURER BETWEEN @MANUFACTURER_RS AND @MANUFACTURER_RE AND MNFCTRITMNMBR BETWEEN @MNFCTRITMNMBR_RS AND @MNFCTRITMNMBR_RE ORDER BY ITEMNMBR DESC, MANUFACTURER DESC, MNFCTRITMNMBR DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00115L_3] TO [DYNGRP]
GO
