SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DTA00300N_1] (@BS int, @ACTINDX int, @GROUPID char(15), @ACTINDX_RS int, @GROUPID_RS char(15), @ACTINDX_RE int, @GROUPID_RE char(15)) AS  set nocount on IF @ACTINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, GROUPID, DTA_Quantities, ACCTSTAT, DECPLQTY, DEX_ROW_ID FROM .DTA00300 WHERE ( ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, GROUPID ASC END ELSE IF @ACTINDX_RS = @ACTINDX_RE BEGIN SELECT TOP 25  ACTINDX, GROUPID, DTA_Quantities, ACCTSTAT, DECPLQTY, DEX_ROW_ID FROM .DTA00300 WHERE ACTINDX = @ACTINDX_RS AND GROUPID BETWEEN @GROUPID_RS AND @GROUPID_RE AND ( ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, GROUPID ASC END ELSE BEGIN SELECT TOP 25  ACTINDX, GROUPID, DTA_Quantities, ACCTSTAT, DECPLQTY, DEX_ROW_ID FROM .DTA00300 WHERE ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE AND GROUPID BETWEEN @GROUPID_RS AND @GROUPID_RE AND ( ACTINDX = @ACTINDX AND GROUPID > @GROUPID OR ACTINDX > @ACTINDX ) ORDER BY ACTINDX ASC, GROUPID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DTA00300N_1] TO [DYNGRP]
GO
