SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA42200L_1] (@ACTINDX_RS int, @ACTINDX_RE int) AS  set nocount on IF @ACTINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, ASSETCLASSID, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42200 ORDER BY ACTINDX DESC END ELSE IF @ACTINDX_RS = @ACTINDX_RE BEGIN SELECT TOP 25  ACTINDX, ASSETCLASSID, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42200 WHERE ACTINDX = @ACTINDX_RS ORDER BY ACTINDX DESC END ELSE BEGIN SELECT TOP 25  ACTINDX, ASSETCLASSID, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA42200 WHERE ACTINDX BETWEEN @ACTINDX_RS AND @ACTINDX_RE ORDER BY ACTINDX DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA42200L_1] TO [DYNGRP]
GO
