SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV40500SS_1] (@LOTTYPE char(11)) AS  set nocount on SELECT TOP 1  LOTTYPE, LTATRDSC_1, LTATRDSC_2, LTATRDSC_3, LTATRDSC_4, LTATRDSC_5, NOTEINDX, DEX_ROW_ID FROM .IV40500 WHERE LOTTYPE = @LOTTYPE ORDER BY LOTTYPE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV40500SS_1] TO [DYNGRP]
GO
