SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4601700SS_1] (@BSSI_Site_Class_ID char(15)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  BSSI_Site_Class_ID, BSSI_Description, NOTEINDX, DEX_ROW_ID FROM .B4601700 WHERE BSSI_Site_Class_ID = @BSSI_Site_Class_ID ORDER BY BSSI_Site_Class_ID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4601700SS_1] TO [DYNGRP]
GO
