SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00501N_1] (@BS int, @MODIFDT datetime, @ITEMNMBR char(31), @MODIFDT_RS datetime, @ITEMNMBR_RS char(31), @MODIFDT_RE datetime, @ITEMNMBR_RE char(31)) AS  set nocount on IF @MODIFDT_RS IS NULL BEGIN SELECT TOP 25  ITEMNMBR, ITEMTYPE, ITEMDESC, ITMSHNAM, ITMTRKOP, LISTPRCE, RTRNABLE, METERED, SVC_Delta_Type, MODIFDT, DEX_ROW_ID FROM .SVC00501 WHERE ( MODIFDT = @MODIFDT AND ITEMNMBR > @ITEMNMBR OR MODIFDT > @MODIFDT ) ORDER BY MODIFDT ASC, ITEMNMBR ASC END ELSE IF @MODIFDT_RS = @MODIFDT_RE BEGIN SELECT TOP 25  ITEMNMBR, ITEMTYPE, ITEMDESC, ITMSHNAM, ITMTRKOP, LISTPRCE, RTRNABLE, METERED, SVC_Delta_Type, MODIFDT, DEX_ROW_ID FROM .SVC00501 WHERE MODIFDT = @MODIFDT_RS AND ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND ( MODIFDT = @MODIFDT AND ITEMNMBR > @ITEMNMBR OR MODIFDT > @MODIFDT ) ORDER BY MODIFDT ASC, ITEMNMBR ASC END ELSE BEGIN SELECT TOP 25  ITEMNMBR, ITEMTYPE, ITEMDESC, ITMSHNAM, ITMTRKOP, LISTPRCE, RTRNABLE, METERED, SVC_Delta_Type, MODIFDT, DEX_ROW_ID FROM .SVC00501 WHERE MODIFDT BETWEEN @MODIFDT_RS AND @MODIFDT_RE AND ITEMNMBR BETWEEN @ITEMNMBR_RS AND @ITEMNMBR_RE AND ( MODIFDT = @MODIFDT AND ITEMNMBR > @ITEMNMBR OR MODIFDT > @MODIFDT ) ORDER BY MODIFDT ASC, ITEMNMBR ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00501N_1] TO [DYNGRP]
GO
