SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP50200SD] (@USERID char(15), @SEQNUMBR int, @DOCTYPE smallint, @LOCNCODE char(11), @DOCPRINTSEQ int, @SOPTYPE smallint, @SOPNUMBE char(21), @Email_Type smallint, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .SOP50200 WHERE USERID = @USERID AND SEQNUMBR = @SEQNUMBR AND DOCTYPE = @DOCTYPE AND LOCNCODE = @LOCNCODE AND DOCPRINTSEQ = @DOCPRINTSEQ AND SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND Email_Type = @Email_Type AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .SOP50200 WHERE USERID = @USERID AND SEQNUMBR = @SEQNUMBR AND DOCTYPE = @DOCTYPE AND LOCNCODE = @LOCNCODE AND DOCPRINTSEQ = @DOCPRINTSEQ AND SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND Email_Type = @Email_Type SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP50200SD] TO [DYNGRP]
GO
