SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00202SS_4] (@EQUIPID int, @SRVRECTYPE smallint) AS  set nocount on SELECT TOP 1  SRVRECTYPE, CALLNBR, EQPLINE, EQUIPID, ITEMNMBR, METER1, METER2, METER3, LSTDTEDT, PMPERF, DEX_ROW_ID FROM .SVC00202 WHERE EQUIPID = @EQUIPID AND SRVRECTYPE = @SRVRECTYPE ORDER BY EQUIPID ASC, SRVRECTYPE ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00202SS_4] TO [DYNGRP]
GO
