SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HR2TFR01F_1] (@EMPID_I_RS char(15), @TRANSFERREQUESTDAT_I_RS datetime, @EMPID_I_RE char(15), @TRANSFERREQUESTDAT_I_RE datetime) AS  set nocount on IF @EMPID_I_RS IS NULL BEGIN SELECT TOP 25  EMPID_I, TRANSFERREQUESTDAT_I, DESIREDCOMPANYCODE_I, DESDIVCODE_I, DESDEPTCODE_I, DESPOSCODE_I, DESSUPCODE_I, DESLOCCODE_I, EMPLOYMENTTYPE, DESIREDSHIFTCODE_I, CHANGEBY_I, CHANGEDATE_I, NOTESINDEX_I, DEX_ROW_ID FROM .HR2TFR01 ORDER BY EMPID_I ASC, TRANSFERREQUESTDAT_I ASC END ELSE IF @EMPID_I_RS = @EMPID_I_RE BEGIN SELECT TOP 25  EMPID_I, TRANSFERREQUESTDAT_I, DESIREDCOMPANYCODE_I, DESDIVCODE_I, DESDEPTCODE_I, DESPOSCODE_I, DESSUPCODE_I, DESLOCCODE_I, EMPLOYMENTTYPE, DESIREDSHIFTCODE_I, CHANGEBY_I, CHANGEDATE_I, NOTESINDEX_I, DEX_ROW_ID FROM .HR2TFR01 WHERE EMPID_I = @EMPID_I_RS AND TRANSFERREQUESTDAT_I BETWEEN @TRANSFERREQUESTDAT_I_RS AND @TRANSFERREQUESTDAT_I_RE ORDER BY EMPID_I ASC, TRANSFERREQUESTDAT_I ASC END ELSE BEGIN SELECT TOP 25  EMPID_I, TRANSFERREQUESTDAT_I, DESIREDCOMPANYCODE_I, DESDIVCODE_I, DESDEPTCODE_I, DESPOSCODE_I, DESSUPCODE_I, DESLOCCODE_I, EMPLOYMENTTYPE, DESIREDSHIFTCODE_I, CHANGEBY_I, CHANGEDATE_I, NOTESINDEX_I, DEX_ROW_ID FROM .HR2TFR01 WHERE EMPID_I BETWEEN @EMPID_I_RS AND @EMPID_I_RE AND TRANSFERREQUESTDAT_I BETWEEN @TRANSFERREQUESTDAT_I_RS AND @TRANSFERREQUESTDAT_I_RE ORDER BY EMPID_I ASC, TRANSFERREQUESTDAT_I ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HR2TFR01F_1] TO [DYNGRP]
GO
