SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PC40308SS_2] (@PLANCODE char(15), @JOBTITLE char(7), @TEMPSEAT tinyint, @SEAT int, @STRTDATE datetime) AS  set nocount on SELECT TOP 1  PLANCODE, JOBTITLE, TEMPSEAT, SEAT, SEQNUMBR, DSCRIPTN, STRTDATE, ENDDATE, BUDGETAMT, DEX_ROW_ID FROM .PC40308 WHERE PLANCODE = @PLANCODE AND JOBTITLE = @JOBTITLE AND TEMPSEAT = @TEMPSEAT AND SEAT = @SEAT AND STRTDATE = @STRTDATE ORDER BY PLANCODE ASC, JOBTITLE ASC, TEMPSEAT ASC, SEAT ASC, STRTDATE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PC40308SS_2] TO [DYNGRP]
GO
