SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 Create Procedure [dbo].[SVC_GetContractWIPServiceCost] (  @CONSTS smallint,  @CONTNBR char(11),  @DOCUMENTAMOUNT numeric(19,5) OUTPUT,  @ORGDOCUMENTAMOUNT numeric(19,5) OUTPUT ) AS   select @DOCUMENTAMOUNT = sum(LABSTOTCST)+sum(PARSTOTCST) + sum(MISSTOTCST),  @ORGDOCUMENTAMOUNT = sum(ORIGLABSUBTOTCOST)+sum(ORIGPARSTOTCST) + sum(ORIGMISSTOTCST)  from SVC00200 where SRVRECTYPE = 2 and CONTNBR = @CONTNBR and CONSTS = @CONSTS select @DOCUMENTAMOUNT = isnull(@DOCUMENTAMOUNT,0) select @ORGDOCUMENTAMOUNT = isnull(@ORGDOCUMENTAMOUNT,0) return     
GO
GRANT EXECUTE ON  [dbo].[SVC_GetContractWIPServiceCost] TO [DYNGRP]
GO
