SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRTER062SS_1] (@EMPID_I char(15)) AS  set nocount on SELECT TOP 1  EMPID_I, IDATE_I, OPINION_I, JOBSATISFACTION_I, TRAINING_I, PROMOTION_I, WAGESCALE_I, COMPANYBENIFITS_I, WORKERS_I, ORGANIZE_I, LEADER_I, FEEDBACK_I, CRITICISM_I, CONDITIONS_I, IHOURSWORKED_I, CHNGIMPROVEMNTS_I, NEWJOB_I, CONFIDENTIAL_I, NOTESINDEX_I, DEX_ROW_ID FROM .HRTER062 WHERE EMPID_I = @EMPID_I ORDER BY EMPID_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRTER062SS_1] TO [DYNGRP]
GO
