SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00501SI] (@ITEMNMBR char(31), @ITEMTYPE smallint, @ITEMDESC char(101), @ITMSHNAM char(15), @ITMTRKOP smallint, @LISTPRCE numeric(19,5), @RTRNABLE tinyint, @METERED tinyint, @SVC_Delta_Type smallint, @MODIFDT datetime, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00501 (ITEMNMBR, ITEMTYPE, ITEMDESC, ITMSHNAM, ITMTRKOP, LISTPRCE, RTRNABLE, METERED, SVC_Delta_Type, MODIFDT) VALUES ( @ITEMNMBR, @ITEMTYPE, @ITEMDESC, @ITMSHNAM, @ITMTRKOP, @LISTPRCE, @RTRNABLE, @METERED, @SVC_Delta_Type, @MODIFDT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00501SI] TO [DYNGRP]
GO
