SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR19901L_1] (@USERID_RS char(15), @UPRACTYP_RS smallint, @DEPRTMNT_RS char(7), @JOBTITLE_RS char(7), @PAYROLCD_RS char(7), @USERID_RE char(15), @UPRACTYP_RE smallint, @DEPRTMNT_RE char(7), @JOBTITLE_RE char(7), @PAYROLCD_RE char(7)) AS  set nocount on IF @USERID_RS IS NULL BEGIN SELECT TOP 25  DEPRTMNT, JOBTITLE, PAYROLCD, ACTINDX, UPRACTYP, USERID, DEX_ROW_ID FROM .UPR19901 ORDER BY USERID DESC, UPRACTYP DESC, DEPRTMNT DESC, JOBTITLE DESC, PAYROLCD DESC END ELSE IF @USERID_RS = @USERID_RE BEGIN SELECT TOP 25  DEPRTMNT, JOBTITLE, PAYROLCD, ACTINDX, UPRACTYP, USERID, DEX_ROW_ID FROM .UPR19901 WHERE USERID = @USERID_RS AND UPRACTYP BETWEEN @UPRACTYP_RS AND @UPRACTYP_RE AND DEPRTMNT BETWEEN @DEPRTMNT_RS AND @DEPRTMNT_RE AND JOBTITLE BETWEEN @JOBTITLE_RS AND @JOBTITLE_RE AND PAYROLCD BETWEEN @PAYROLCD_RS AND @PAYROLCD_RE ORDER BY USERID DESC, UPRACTYP DESC, DEPRTMNT DESC, JOBTITLE DESC, PAYROLCD DESC END ELSE BEGIN SELECT TOP 25  DEPRTMNT, JOBTITLE, PAYROLCD, ACTINDX, UPRACTYP, USERID, DEX_ROW_ID FROM .UPR19901 WHERE USERID BETWEEN @USERID_RS AND @USERID_RE AND UPRACTYP BETWEEN @UPRACTYP_RS AND @UPRACTYP_RE AND DEPRTMNT BETWEEN @DEPRTMNT_RS AND @DEPRTMNT_RE AND JOBTITLE BETWEEN @JOBTITLE_RS AND @JOBTITLE_RE AND PAYROLCD BETWEEN @PAYROLCD_RS AND @PAYROLCD_RE ORDER BY USERID DESC, UPRACTYP DESC, DEPRTMNT DESC, JOBTITLE DESC, PAYROLCD DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR19901L_1] TO [DYNGRP]
GO
