SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B2930512L_1] (@BSSI_Lease_Loan_Number_RS char(17), @LNITMSEQ_RS int, @BSSI_Lease_Loan_Number_RE char(17), @LNITMSEQ_RE int) AS /* 12.00.0270.000 */ set nocount on IF @BSSI_Lease_Loan_Number_RS IS NULL BEGIN SELECT TOP 25  BSSI_Lease_Loan_Number, LNITMSEQ, DEDUCTON, BSSI_DeductionPercentage, DEX_ROW_ID FROM .B2930512 ORDER BY BSSI_Lease_Loan_Number DESC, LNITMSEQ DESC END ELSE IF @BSSI_Lease_Loan_Number_RS = @BSSI_Lease_Loan_Number_RE BEGIN SELECT TOP 25  BSSI_Lease_Loan_Number, LNITMSEQ, DEDUCTON, BSSI_DeductionPercentage, DEX_ROW_ID FROM .B2930512 WHERE BSSI_Lease_Loan_Number = @BSSI_Lease_Loan_Number_RS AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY BSSI_Lease_Loan_Number DESC, LNITMSEQ DESC END ELSE BEGIN SELECT TOP 25  BSSI_Lease_Loan_Number, LNITMSEQ, DEDUCTON, BSSI_DeductionPercentage, DEX_ROW_ID FROM .B2930512 WHERE BSSI_Lease_Loan_Number BETWEEN @BSSI_Lease_Loan_Number_RS AND @BSSI_Lease_Loan_Number_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY BSSI_Lease_Loan_Number DESC, LNITMSEQ DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B2930512L_1] TO [DYNGRP]
GO
