SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP40400SD] (@INDEX1 smallint, @DSCRIPTN char(31), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .POP40400 WHERE INDEX1 = @INDEX1 AND DSCRIPTN = @DSCRIPTN AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .POP40400 WHERE INDEX1 = @INDEX1 AND DSCRIPTN = @DSCRIPTN SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP40400SD] TO [DYNGRP]
GO
