SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC06020F_1] (@WOTYPE_RS char(11), @WOTYPE_RE char(11)) AS  set nocount on IF @WOTYPE_RS IS NULL BEGIN SELECT TOP 25  WOTYPE, DSCRIPTN, WOSTAT, ROUTEID, WIPINV, WIPLABOR, SVC_Do_Expense, SVC_Expense_Index, DEX_ROW_ID FROM .SVC06020 ORDER BY WOTYPE ASC END ELSE IF @WOTYPE_RS = @WOTYPE_RE BEGIN SELECT TOP 25  WOTYPE, DSCRIPTN, WOSTAT, ROUTEID, WIPINV, WIPLABOR, SVC_Do_Expense, SVC_Expense_Index, DEX_ROW_ID FROM .SVC06020 WHERE WOTYPE = @WOTYPE_RS ORDER BY WOTYPE ASC END ELSE BEGIN SELECT TOP 25  WOTYPE, DSCRIPTN, WOSTAT, ROUTEID, WIPINV, WIPLABOR, SVC_Do_Expense, SVC_Expense_Index, DEX_ROW_ID FROM .SVC06020 WHERE WOTYPE BETWEEN @WOTYPE_RS AND @WOTYPE_RE ORDER BY WOTYPE ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC06020F_1] TO [DYNGRP]
GO
