SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM50100SS_1] (@USERID char(15), @PRCSSQNC smallint, @Status smallint, @VCHRNMBR char(21), @DOCTYPE smallint) AS  set nocount on SELECT TOP 1  VCHRNMBR, VENDORID, DOCTYPE, DOCDATE, DOCNUMBR, DOCAMNT, CURTRXAM, DISTKNAM, DISCAMNT, DSCDLRAM, BACHNUMB, TRXSORCE, BCHSOURC, DISCDATE, DUEDATE, PORDNMBR, TEN99AMNT, WROFAMNT, DISAMTAV, TRXDSCRN, UN1099AM, BKTPURAM, BKTFRTAM, BKTMSCAM, VOIDED, HOLD, CHEKBKID, DINVPDOF, PPSAMDED, PPSTAXRT, PGRAMSBJ, GSTDSAMT, POSTEDDT, PTDUSRID, MODIFDT, MDFUSRID, PYENTTYP, CARDNAME, PRCHAMNT, TRDISAMT, MSCCHAMT, FRTAMNT, TAXAMNT, TTLPYMTS, CURNCYID, PYMTRMID, SHIPMTHD, TAXSCHID, PCHSCHID, FRTSCHID, MSCSCHID, PSTGDATE, DISAVTKN, CNTRLTYP, NOTEINDX, PRCTDISC, RETNAGAM, VOIDPDATE, ICTRX, Tax_Date, PRCHDATE, CORRCTN, SIMPLIFD, USERID, PRCSSQNC, Status, STR1, DEX_ROW_ID FROM .PM50100 WHERE USERID = @USERID AND PRCSSQNC = @PRCSSQNC AND Status = @Status AND VCHRNMBR = @VCHRNMBR AND DOCTYPE = @DOCTYPE ORDER BY USERID ASC, PRCSSQNC ASC, Status ASC, VCHRNMBR ASC, DOCTYPE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM50100SS_1] TO [DYNGRP]
GO
