SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PC30303SD] (@PLANCODE char(15), @JOBTITLE char(7), @BENEFIT char(7), @CHANGEDATE_I datetime, @SEQ_I int, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .PC30303 WHERE PLANCODE = @PLANCODE AND JOBTITLE = @JOBTITLE AND BENEFIT = @BENEFIT AND CHANGEDATE_I = @CHANGEDATE_I AND SEQ_I = @SEQ_I AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .PC30303 WHERE PLANCODE = @PLANCODE AND JOBTITLE = @JOBTITLE AND BENEFIT = @BENEFIT AND CHANGEDATE_I = @CHANGEDATE_I AND SEQ_I = @SEQ_I SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PC30303SD] TO [DYNGRP]
GO
