SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AF40108L_1] (@REPORTID_RS smallint, @TOTRWNUM_RS smallint, @MBRWNUM_RS smallint, @REPORTID_RE smallint, @TOTRWNUM_RE smallint, @MBRWNUM_RE smallint) AS  set nocount on IF @REPORTID_RS IS NULL BEGIN SELECT TOP 25  REPORTID, TOTRWNUM, MBRWNUM, DEX_ROW_ID FROM .AF40108 ORDER BY REPORTID DESC, TOTRWNUM DESC, MBRWNUM DESC END ELSE IF @REPORTID_RS = @REPORTID_RE BEGIN SELECT TOP 25  REPORTID, TOTRWNUM, MBRWNUM, DEX_ROW_ID FROM .AF40108 WHERE REPORTID = @REPORTID_RS AND TOTRWNUM BETWEEN @TOTRWNUM_RS AND @TOTRWNUM_RE AND MBRWNUM BETWEEN @MBRWNUM_RS AND @MBRWNUM_RE ORDER BY REPORTID DESC, TOTRWNUM DESC, MBRWNUM DESC END ELSE BEGIN SELECT TOP 25  REPORTID, TOTRWNUM, MBRWNUM, DEX_ROW_ID FROM .AF40108 WHERE REPORTID BETWEEN @REPORTID_RS AND @REPORTID_RE AND TOTRWNUM BETWEEN @TOTRWNUM_RS AND @TOTRWNUM_RE AND MBRWNUM BETWEEN @MBRWNUM_RS AND @MBRWNUM_RE ORDER BY REPORTID DESC, TOTRWNUM DESC, MBRWNUM DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AF40108L_1] TO [DYNGRP]
GO
