SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL40402L_3] (@MODULE1_RS smallint, @Reconciliation_Number_RS int, @SQNCLINE_RS numeric(19,5), @MODULE1_RE smallint, @Reconciliation_Number_RE int, @SQNCLINE_RE numeric(19,5)) AS  set nocount on IF @MODULE1_RS IS NULL BEGIN SELECT TOP 25  Reconciliation_Number, SQNCLINE, MODULE1, ACTINDX, DEX_ROW_ID FROM .GL40402 ORDER BY MODULE1 DESC, Reconciliation_Number DESC, SQNCLINE DESC END ELSE IF @MODULE1_RS = @MODULE1_RE BEGIN SELECT TOP 25  Reconciliation_Number, SQNCLINE, MODULE1, ACTINDX, DEX_ROW_ID FROM .GL40402 WHERE MODULE1 = @MODULE1_RS AND Reconciliation_Number BETWEEN @Reconciliation_Number_RS AND @Reconciliation_Number_RE AND SQNCLINE BETWEEN @SQNCLINE_RS AND @SQNCLINE_RE ORDER BY MODULE1 DESC, Reconciliation_Number DESC, SQNCLINE DESC END ELSE BEGIN SELECT TOP 25  Reconciliation_Number, SQNCLINE, MODULE1, ACTINDX, DEX_ROW_ID FROM .GL40402 WHERE MODULE1 BETWEEN @MODULE1_RS AND @MODULE1_RE AND Reconciliation_Number BETWEEN @Reconciliation_Number_RS AND @Reconciliation_Number_RE AND SQNCLINE BETWEEN @SQNCLINE_RS AND @SQNCLINE_RE ORDER BY MODULE1 DESC, Reconciliation_Number DESC, SQNCLINE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL40402L_3] TO [DYNGRP]
GO
