SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00700SS_1] (@EMPLOYID char(15), @STATECD char(3)) AS  set nocount on SELECT TOP 1  EMPLOYID, STATECD, TXFLGSTS, EXMFBLND, EXFBLSPS, EXFORO65, EXMFRSLF, EXMFSPAL, EXMFRSPS, EXFSPO65, PRSNEXPT, DEPNDNTS, ADNLALOW, ESTDEDAL, EXMTAMNT, ADSTWHDG, ESTSTWHD, INACTIVE, NOTEINDX, DEX_ROW_ID FROM .UPR00700 WHERE EMPLOYID = @EMPLOYID AND STATECD = @STATECD ORDER BY EMPLOYID ASC, STATECD ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00700SS_1] TO [DYNGRP]
GO
