SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL00103N_2] (@BS int, @DSTINDX int, @DEX_ROW_ID int, @DSTINDX_RS int, @DSTINDX_RE int) AS  set nocount on IF @DSTINDX_RS IS NULL BEGIN SELECT TOP 25  ACTINDX, PRCNTAGE, DSTINDX, DEX_ROW_ID FROM .GL00103 WHERE ( DSTINDX = @DSTINDX AND DEX_ROW_ID > @DEX_ROW_ID OR DSTINDX > @DSTINDX ) ORDER BY DSTINDX ASC, DEX_ROW_ID ASC END ELSE IF @DSTINDX_RS = @DSTINDX_RE BEGIN SELECT TOP 25  ACTINDX, PRCNTAGE, DSTINDX, DEX_ROW_ID FROM .GL00103 WHERE DSTINDX = @DSTINDX_RS AND ( DSTINDX = @DSTINDX AND DEX_ROW_ID > @DEX_ROW_ID OR DSTINDX > @DSTINDX ) ORDER BY DSTINDX ASC, DEX_ROW_ID ASC END ELSE BEGIN SELECT TOP 25  ACTINDX, PRCNTAGE, DSTINDX, DEX_ROW_ID FROM .GL00103 WHERE DSTINDX BETWEEN @DSTINDX_RS AND @DSTINDX_RE AND ( DSTINDX = @DSTINDX AND DEX_ROW_ID > @DEX_ROW_ID OR DSTINDX > @DSTINDX ) ORDER BY DSTINDX ASC, DEX_ROW_ID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL00103N_2] TO [DYNGRP]
GO
