SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA41600SS_3] (@VENDORID char(15), @LEASECOMPID char(15)) AS  set nocount on SELECT TOP 1  LEASECOMPINDX, LEASECOMPID, VENDORID, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID, DEX_ROW_ID FROM .FA41600 WHERE VENDORID = @VENDORID AND LEASECOMPID = @LEASECOMPID ORDER BY VENDORID ASC, LEASECOMPID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA41600SS_3] TO [DYNGRP]
GO
