SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR00201SI] (@EMPLOYID char(15), @Time_on_Behalf_Code char(15), @DEPRTMNT char(7), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .UPR00201 (EMPLOYID, Time_on_Behalf_Code, DEPRTMNT) VALUES ( @EMPLOYID, @Time_on_Behalf_Code, @DEPRTMNT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR00201SI] TO [DYNGRP]
GO
