SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4640049SS_1] (@LOCNCODE char(11), @BSSI_MeterNumber char(31)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  LOCNCODE, BSSI_MeterNumber, NOTEINDX, DEX_ROW_ID FROM .B4640049 WHERE LOCNCODE = @LOCNCODE AND BSSI_MeterNumber = @BSSI_MeterNumber ORDER BY LOCNCODE ASC, BSSI_MeterNumber ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4640049SS_1] TO [DYNGRP]
GO
