SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_DTA00700SI] (@RPTGRIND smallint, @RTGRSBIN numeric(19,5), @RTPACHIN smallint, @STTACNUM_1 char(5), @STTACNUM_2 char(5), @STTACNUM_3 char(3), @STTACNUM_4 char(3), @EACCNBR_1 char(5), @EACCNBR_2 char(5), @EACCNBR_3 char(3), @EACCNBR_4 char(3), @STRTDATE datetime, @ENDDATE datetime, @STARTGRP char(15), @ENDGROUP char(15), @STRTCODE char(15), @ENDCODE char(15), @PRNTDTLD tinyint, @UNPSTTRX tinyint, @OPEN1 tinyint, @HISTORY tinyint, @STTPSTDT datetime, @ENDPSTDT datetime, @DEX_ROW_ID int OUT) AS /* 14.00.0084.000 */ set nocount on BEGIN INSERT INTO .DTA00700 (RPTGRIND, RTGRSBIN, RTPACHIN, STTACNUM_1, STTACNUM_2, STTACNUM_3, STTACNUM_4, EACCNBR_1, EACCNBR_2, EACCNBR_3, EACCNBR_4, STRTDATE, ENDDATE, STARTGRP, ENDGROUP, STRTCODE, ENDCODE, PRNTDTLD, UNPSTTRX, OPEN1, HISTORY, STTPSTDT, ENDPSTDT) VALUES ( @RPTGRIND, @RTGRSBIN, @RTPACHIN, @STTACNUM_1, @STTACNUM_2, @STTACNUM_3, @STTACNUM_4, @EACCNBR_1, @EACCNBR_2, @EACCNBR_3, @EACCNBR_4, @STRTDATE, @ENDDATE, @STARTGRP, @ENDGROUP, @STRTCODE, @ENDCODE, @PRNTDTLD, @UNPSTTRX, @OPEN1, @HISTORY, @STTPSTDT, @ENDPSTDT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_DTA00700SI] TO [DYNGRP]
GO
