SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA42700SI] (@CALNDRID char(15), @FISCALYEAR smallint, @SLNGYEAR tinyint, @DEPRPCNT numeric(19,5), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .FA42700 (CALNDRID, FISCALYEAR, SLNGYEAR, DEPRPCNT) VALUES ( @CALNDRID, @FISCALYEAR, @SLNGYEAR, @DEPRPCNT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA42700SI] TO [DYNGRP]
GO
