SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100601SS_1] (@BSSI_EBTemplateID char(25)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  BSSI_EBTemplateID, BSSI_Description, BSSI_EBRecog_Methods, BSSI_EBOnQty, BSSI_Recog_Acct_Index1, NOTEINDX, DEX_ROW_ID FROM .B7100601 WHERE BSSI_EBTemplateID = @BSSI_EBTemplateID ORDER BY BSSI_EBTemplateID ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100601SS_1] TO [DYNGRP]
GO
