SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B4610005SS_1] (@BSSI_Category char(31)) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  BSSI_Category, DSCRIPTN, NOTEINDX, DEX_ROW_ID FROM .B4610005 WHERE BSSI_Category = @BSSI_Category ORDER BY BSSI_Category ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B4610005SS_1] TO [DYNGRP]
GO
