SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM30202L_1] (@APTODCTY_RS smallint, @APTODCNM_RS char(21), @APTODCTY_RE smallint, @APTODCNM_RE char(21)) AS  set nocount on IF @APTODCTY_RS IS NULL BEGIN SELECT TOP 25  CUSTNMBR, APTODCNM, APTODCTY, APPTOAMT, APFRDCNM, APFRDCTY, APFRDCDT, TRXSORCE, DISTKNAM, WROFAMNT, DATE1, GLPOSTDT, POSTED, GSTDSAMT, PPSAMDED, TAXDTLID, ORAPTOAM, ORDISTKN, ORDATKN, ORWROFAM, RLGANLOS, DEX_ROW_ID FROM .RM30202 ORDER BY APTODCTY DESC, APTODCNM DESC, DEX_ROW_ID DESC END ELSE IF @APTODCTY_RS = @APTODCTY_RE BEGIN SELECT TOP 25  CUSTNMBR, APTODCNM, APTODCTY, APPTOAMT, APFRDCNM, APFRDCTY, APFRDCDT, TRXSORCE, DISTKNAM, WROFAMNT, DATE1, GLPOSTDT, POSTED, GSTDSAMT, PPSAMDED, TAXDTLID, ORAPTOAM, ORDISTKN, ORDATKN, ORWROFAM, RLGANLOS, DEX_ROW_ID FROM .RM30202 WHERE APTODCTY = @APTODCTY_RS AND APTODCNM BETWEEN @APTODCNM_RS AND @APTODCNM_RE ORDER BY APTODCTY DESC, APTODCNM DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  CUSTNMBR, APTODCNM, APTODCTY, APPTOAMT, APFRDCNM, APFRDCTY, APFRDCDT, TRXSORCE, DISTKNAM, WROFAMNT, DATE1, GLPOSTDT, POSTED, GSTDSAMT, PPSAMDED, TAXDTLID, ORAPTOAM, ORDISTKN, ORDATKN, ORWROFAM, RLGANLOS, DEX_ROW_ID FROM .RM30202 WHERE APTODCTY BETWEEN @APTODCTY_RS AND @APTODCTY_RE AND APTODCNM BETWEEN @APTODCNM_RS AND @APTODCNM_RE ORDER BY APTODCTY DESC, APTODCNM DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM30202L_1] TO [DYNGRP]
GO
