SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_POP40300SI] (@ITEMNMBR char(31), @ORD int, @UOFM char(9), @UNITCOST numeric(19,5), @VENDORID char(15), @ITEMDESC char(101), @NONINVEN smallint, @DECPLCUR smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .POP40300 (ITEMNMBR, ORD, UOFM, UNITCOST, VENDORID, ITEMDESC, NONINVEN, DECPLCUR) VALUES ( @ITEMNMBR, @ORD, @UOFM, @UNITCOST, @VENDORID, @ITEMDESC, @NONINVEN, @DECPLCUR) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_POP40300SI] TO [DYNGRP]
GO
