SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL50101SS_3] (@JRNENTRY int, @INTERID char(5), @SQNCLINE numeric(19,5), @CURNCYID char(15), @ACTINDX int) AS  set nocount on SELECT TOP 1  USERID, BCHSOURC, BACHNUMB, JRNENTRY, SQNCLINE, ACTINDX, OFFINDX, GLLINMSG, GLLINMS2, TRXDATE, ACCTTYPE, DSCRIPTN, CURNCYID, CURRNIDX, FUNCRIDX, INTERID, ACTNUMST, ACTDESCR, CRDTAMNT, DEBITAMT, ORCRDAMT, ORDBTAMT, ORCTRNUM, ORDOCNUM, ORMSTRID, ORMSTRNM, ORTRXTYP, MCTRXSTT, XCHGRATE, DENXRATE, DEX_ROW_ID FROM .GL50101 WHERE JRNENTRY = @JRNENTRY AND INTERID = @INTERID AND SQNCLINE = @SQNCLINE AND CURNCYID = @CURNCYID AND ACTINDX = @ACTINDX ORDER BY JRNENTRY ASC, INTERID ASC, SQNCLINE ASC, CURNCYID ASC, ACTINDX ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL50101SS_3] TO [DYNGRP]
GO
