SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00315N_1] (@BS int, @EQUIPID int, @SCHEDID char(9), @EQUIPID_RS int, @SCHEDID_RS char(9), @EQUIPID_RE int, @SCHEDID_RE char(9)) AS  set nocount on IF @EQUIPID_RS IS NULL BEGIN SELECT TOP 25  EQUIPID, ACTIVE, SCHEDID, DEX_ROW_ID FROM .SVC00315 WHERE ( EQUIPID = @EQUIPID AND SCHEDID > @SCHEDID OR EQUIPID > @EQUIPID ) ORDER BY EQUIPID ASC, SCHEDID ASC END ELSE IF @EQUIPID_RS = @EQUIPID_RE BEGIN SELECT TOP 25  EQUIPID, ACTIVE, SCHEDID, DEX_ROW_ID FROM .SVC00315 WHERE EQUIPID = @EQUIPID_RS AND SCHEDID BETWEEN @SCHEDID_RS AND @SCHEDID_RE AND ( EQUIPID = @EQUIPID AND SCHEDID > @SCHEDID OR EQUIPID > @EQUIPID ) ORDER BY EQUIPID ASC, SCHEDID ASC END ELSE BEGIN SELECT TOP 25  EQUIPID, ACTIVE, SCHEDID, DEX_ROW_ID FROM .SVC00315 WHERE EQUIPID BETWEEN @EQUIPID_RS AND @EQUIPID_RE AND SCHEDID BETWEEN @SCHEDID_RS AND @SCHEDID_RE AND ( EQUIPID = @EQUIPID AND SCHEDID > @SCHEDID OR EQUIPID > @EQUIPID ) ORDER BY EQUIPID ASC, SCHEDID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00315N_1] TO [DYNGRP]
GO
