SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B0530501L_1] (@BSSI_Capital_Call_ID_RS char(25), @LNITMSEQ_RS int, @BSSI_Capital_Call_ID_RE char(25), @LNITMSEQ_RE int) AS /* 12.00.0270.000 */ set nocount on IF @BSSI_Capital_Call_ID_RS IS NULL BEGIN SELECT TOP 25  BSSI_Capital_Call_ID, LNITMSEQ, BSSI_Fee_ID, BSSI_Fee_Amount, CURNCYID, CURRNIDX, DEX_ROW_ID FROM .B0530501 ORDER BY BSSI_Capital_Call_ID DESC, LNITMSEQ DESC END ELSE IF @BSSI_Capital_Call_ID_RS = @BSSI_Capital_Call_ID_RE BEGIN SELECT TOP 25  BSSI_Capital_Call_ID, LNITMSEQ, BSSI_Fee_ID, BSSI_Fee_Amount, CURNCYID, CURRNIDX, DEX_ROW_ID FROM .B0530501 WHERE BSSI_Capital_Call_ID = @BSSI_Capital_Call_ID_RS AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY BSSI_Capital_Call_ID DESC, LNITMSEQ DESC END ELSE BEGIN SELECT TOP 25  BSSI_Capital_Call_ID, LNITMSEQ, BSSI_Fee_ID, BSSI_Fee_Amount, CURNCYID, CURRNIDX, DEX_ROW_ID FROM .B0530501 WHERE BSSI_Capital_Call_ID BETWEEN @BSSI_Capital_Call_ID_RS AND @BSSI_Capital_Call_ID_RE AND LNITMSEQ BETWEEN @LNITMSEQ_RS AND @LNITMSEQ_RE ORDER BY BSSI_Capital_Call_ID DESC, LNITMSEQ DESC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B0530501L_1] TO [DYNGRP]
GO
