SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP30100SS_2] (@TRXSORCE char(13)) AS  set nocount on SELECT TOP 1  TRXSORCE, BCHSOURC, BACHNUMB, BCHCOMNT, CHEKBKID, GLPOSTDT, APPROVL, APPRVLDT, APRVLUSERID, BCHTOTAL, CNTRLTOT, NUMOFTRX, CNTRLTRX, REPRNTNT, USERID, NOTEINDX, TRXMISNG, DEX_ROW_ID FROM .SOP30100 WHERE TRXSORCE = @TRXSORCE ORDER BY TRXSORCE ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP30100SS_2] TO [DYNGRP]
GO
