SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B9000402SI] (@SCHEDULE_NUMBER char(21), @Schedule_Payment_Number smallint, @LNITMSEQ int, @PMNTNMBR char(21), @PYMNTDAT datetime, @PAYMENT_AMOUNT numeric(19,5), @PRINCIPAL_AMOUNT numeric(19,5), @INTEREST_AMOUNT numeric(19,5), @CHRGAMNT numeric(19,5), @CHEKNMBR char(21), @DEX_ROW_ID int OUT) AS /* 12.00.0270.000 */ set nocount on BEGIN INSERT INTO .B9000402 (SCHEDULE_NUMBER, Schedule_Payment_Number, LNITMSEQ, PMNTNMBR, PYMNTDAT, PAYMENT_AMOUNT, PRINCIPAL_AMOUNT, INTEREST_AMOUNT, CHRGAMNT, CHEKNMBR) VALUES ( @SCHEDULE_NUMBER, @Schedule_Payment_Number, @LNITMSEQ, @PMNTNMBR, @PYMNTDAT, @PAYMENT_AMOUNT, @PRINCIPAL_AMOUNT, @INTEREST_AMOUNT, @CHRGAMNT, @CHEKNMBR) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B9000402SI] TO [DYNGRP]
GO
