SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_RM00303SI] (@SALSTERR char(15), @SLTERDSC char(31), @INACTIVE tinyint, @SLPRSNID char(15), @STMGRFNM char(15), @STMGRMNM char(15), @STMGRLNM char(21), @COUNTRY char(61), @COSTTODT numeric(19,5), @TTLCOMTD numeric(19,5), @TTLCOMLY numeric(19,5), @NCOMSLYR numeric(19,5), @COMSLLYR numeric(19,5), @CSTLSTYR numeric(19,5), @COMSLTDT numeric(19,5), @NCOMSLTD numeric(19,5), @KPCALHST tinyint, @KPERHIST tinyint, @NOTEINDX numeric(19,5), @MODIFDT datetime, @CREATDDT datetime, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .RM00303 (SALSTERR, SLTERDSC, INACTIVE, SLPRSNID, STMGRFNM, STMGRMNM, STMGRLNM, COUNTRY, COSTTODT, TTLCOMTD, TTLCOMLY, NCOMSLYR, COMSLLYR, CSTLSTYR, COMSLTDT, NCOMSLTD, KPCALHST, KPERHIST, NOTEINDX, MODIFDT, CREATDDT) VALUES ( @SALSTERR, @SLTERDSC, @INACTIVE, @SLPRSNID, @STMGRFNM, @STMGRMNM, @STMGRLNM, @COUNTRY, @COSTTODT, @TTLCOMTD, @TTLCOMLY, @NCOMSLYR, @COMSLLYR, @CSTLSTYR, @COMSLTDT, @NCOMSLTD, @KPCALHST, @KPERHIST, @NOTEINDX, @MODIFDT, @CREATDDT) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_RM00303SI] TO [DYNGRP]
GO
