SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_GL10002SI] (@BACHNUMB char(15), @JRNENTRY int, @ACTINDX int, @SQNCLINE numeric(19,5), @OFFINDX int, @PSTDAMNT numeric(19,5), @GLLINMSG binary(4), @DSCRIPTN char(31), @GLLINVAL binary(4), @ACCTTYPE smallint, @DECPLACS smallint, @OFFACTYP smallint, @OFFXVAR smallint, @OFFBLCLC smallint, @OFFDECPL smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .GL10002 (BACHNUMB, JRNENTRY, ACTINDX, SQNCLINE, OFFINDX, PSTDAMNT, GLLINMSG, DSCRIPTN, GLLINVAL, ACCTTYPE, DECPLACS, OFFACTYP, OFFXVAR, OFFBLCLC, OFFDECPL) VALUES ( @BACHNUMB, @JRNENTRY, @ACTINDX, @SQNCLINE, @OFFINDX, @PSTDAMNT, @GLLINMSG, @DSCRIPTN, @GLLINVAL, @ACCTTYPE, @DECPLACS, @OFFACTYP, @OFFXVAR, @OFFBLCLC, @OFFDECPL) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_GL10002SI] TO [DYNGRP]
GO
