SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG10000SS_1] (@aaGLWorkHdrID int) AS  set nocount on SELECT TOP 1  aaGLWorkHdrID, JRNENTRY, RCTRXSEQ, GLPOSTDT, aaTRXType, aaHdrErrors, Ledger_ID, DEX_ROW_ID FROM .AAG10000 WHERE aaGLWorkHdrID = @aaGLWorkHdrID ORDER BY aaGLWorkHdrID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG10000SS_1] TO [DYNGRP]
GO
