SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SOP10205L_2] (@PRODTCOD_RS char(1), @LINKCODE_RS char(15), @PRODTCOD_RE char(1), @LINKCODE_RE char(15)) AS  set nocount on IF @PRODTCOD_RS IS NULL BEGIN SELECT TOP 25  PRCBKID, PRODTCOD, LINKCODE, SEQNUMBR, DEX_ROW_ID FROM .SOP10205 ORDER BY PRODTCOD DESC, LINKCODE DESC END ELSE IF @PRODTCOD_RS = @PRODTCOD_RE BEGIN SELECT TOP 25  PRCBKID, PRODTCOD, LINKCODE, SEQNUMBR, DEX_ROW_ID FROM .SOP10205 WHERE PRODTCOD = @PRODTCOD_RS AND LINKCODE BETWEEN @LINKCODE_RS AND @LINKCODE_RE ORDER BY PRODTCOD DESC, LINKCODE DESC END ELSE BEGIN SELECT TOP 25  PRCBKID, PRODTCOD, LINKCODE, SEQNUMBR, DEX_ROW_ID FROM .SOP10205 WHERE PRODTCOD BETWEEN @PRODTCOD_RS AND @PRODTCOD_RE AND LINKCODE BETWEEN @LINKCODE_RS AND @LINKCODE_RE ORDER BY PRODTCOD DESC, LINKCODE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SOP10205L_2] TO [DYNGRP]
GO
