SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC01000SD] (@ITEMNMBR char(31), @SCHEDID char(9), @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .SVC01000 WHERE ITEMNMBR = @ITEMNMBR AND SCHEDID = @SCHEDID AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .SVC01000 WHERE ITEMNMBR = @ITEMNMBR AND SCHEDID = @SCHEDID SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC01000SD] TO [DYNGRP]
GO
