SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AHR2SA01SS_1] (@EMPID_I char(15), @EFFECTIVEDATE_I datetime) AS  set nocount on SELECT TOP 1  EMPID_I, EFFECTIVEDATE_I, WAGE_I, COMPENSATIONPERIOD_I, CHANGEREASON_I, SHFTPREM, ANNUALSALARY_I, PTHOURS_I, NOTESINDEX_I, CHANGEBY_I, CHANGEDATE_I, DEX_ROW_ID FROM .AHR2SA01 WHERE EMPID_I = @EMPID_I AND EFFECTIVEDATE_I = @EFFECTIVEDATE_I ORDER BY EMPID_I ASC, EFFECTIVEDATE_I DESC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AHR2SA01SS_1] TO [DYNGRP]
GO
