SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00980SI] (@SVC_Misc_Address_Code char(15), @DSCRIPTN char(31), @ADDRESS1 char(61), @ADDRESS2 char(61), @CITY char(35), @STATE char(29), @ZIP char(11), @COUNTRY char(61), @SHIPMTHD char(15), @NAME char(31), @ADDRESS3 char(61), @TAXSCHID char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00980 (SVC_Misc_Address_Code, DSCRIPTN, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, COUNTRY, SHIPMTHD, NAME, ADDRESS3, TAXSCHID) VALUES ( @SVC_Misc_Address_Code, @DSCRIPTN, @ADDRESS1, @ADDRESS2, @CITY, @STATE, @ZIP, @COUNTRY, @SHIPMTHD, @NAME, @ADDRESS3, @TAXSCHID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00980SI] TO [DYNGRP]
GO
