SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SY40101SI] (@YEAR1 smallint, @FSTFSCDY datetime, @LSTFSCDY datetime, @NUMOFPER smallint, @HISTORYR tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SY40101 (YEAR1, FSTFSCDY, LSTFSCDY, NUMOFPER, HISTORYR) VALUES ( @YEAR1, @FSTFSCDY, @LSTFSCDY, @NUMOFPER, @HISTORYR) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SY40101SI] TO [DYNGRP]
GO
