SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
 CREATE PROC [dbo].[zDP_AAG02001SI] (@aaTrxDimID int, @aaTrxDimCodeID int, @ACTINDX int, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .AAG02001 (aaTrxDimID, aaTrxDimCodeID, ACTINDX) VALUES ( @aaTrxDimID, @aaTrxDimCodeID, @ACTINDX) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AAG02001SI] TO [DYNGRP]
GO
