SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00202SI] (@SRVRECTYPE smallint, @CALLNBR char(11), @EQPLINE int, @EQUIPID int, @ITEMNMBR char(31), @METER1 int, @METER2 int, @METER3 int, @LSTDTEDT datetime, @PMPERF tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00202 (SRVRECTYPE, CALLNBR, EQPLINE, EQUIPID, ITEMNMBR, METER1, METER2, METER3, LSTDTEDT, PMPERF) VALUES ( @SRVRECTYPE, @CALLNBR, @EQPLINE, @EQUIPID, @ITEMNMBR, @METER1, @METER2, @METER3, @LSTDTEDT, @PMPERF) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00202SI] TO [DYNGRP]
GO
