SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA01002SD] (@PURGEDATE datetime, @PURGETIME datetime, @USERID char(15), @ASSETID char(15), @ASSETIDSUF smallint, @ASSETINDEX int, @RowsAffected int OUT, @RID int = 0, @TN char(99) = 'TN') AS  set nocount on BEGIN IF @RID > 0 DELETE FROM .FA01002 WHERE PURGEDATE = @PURGEDATE AND PURGETIME = @PURGETIME AND USERID = @USERID AND ASSETID = @ASSETID AND ASSETIDSUF = @ASSETIDSUF AND ASSETINDEX = @ASSETINDEX AND ( NOT EXISTS ( SELECT 1 FROM tempdb.dbo.DEX_LOCK WHERE row_id = @RID AND table_path_name = @TN ) ) ELSE DELETE FROM .FA01002 WHERE PURGEDATE = @PURGEDATE AND PURGETIME = @PURGETIME AND USERID = @USERID AND ASSETID = @ASSETID AND ASSETIDSUF = @ASSETIDSUF AND ASSETINDEX = @ASSETINDEX SELECT @RowsAffected = @@rowcount END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA01002SD] TO [DYNGRP]
GO
