SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_EXT01400N_1] (@BS int, @DOCNUMBR char(21), @Extender_Record_ID int, @DOCNUMBR_RS char(21), @Extender_Record_ID_RS int, @DOCNUMBR_RE char(21), @Extender_Record_ID_RE int) AS /* 12.00.0311.000 */ set nocount on IF @DOCNUMBR_RS IS NULL BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 WHERE ( DOCNUMBR = @DOCNUMBR AND Extender_Record_ID > @Extender_Record_ID OR DOCNUMBR > @DOCNUMBR ) ORDER BY DOCNUMBR ASC, Extender_Record_ID ASC END ELSE IF @DOCNUMBR_RS = @DOCNUMBR_RE BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 WHERE DOCNUMBR = @DOCNUMBR_RS AND Extender_Record_ID BETWEEN @Extender_Record_ID_RS AND @Extender_Record_ID_RE AND ( DOCNUMBR = @DOCNUMBR AND Extender_Record_ID > @Extender_Record_ID OR DOCNUMBR > @DOCNUMBR ) ORDER BY DOCNUMBR ASC, Extender_Record_ID ASC END ELSE BEGIN SELECT TOP 25  DOCNUMBR, Extender_Record_ID, DEX_ROW_ID FROM .EXT01400 WHERE DOCNUMBR BETWEEN @DOCNUMBR_RS AND @DOCNUMBR_RE AND Extender_Record_ID BETWEEN @Extender_Record_ID_RS AND @Extender_Record_ID_RE AND ( DOCNUMBR = @DOCNUMBR AND Extender_Record_ID > @Extender_Record_ID OR DOCNUMBR > @DOCNUMBR ) ORDER BY DOCNUMBR ASC, Extender_Record_ID ASC END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_EXT01400N_1] TO [DYNGRP]
GO
