SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_AF10000F_1] (@SEQUENCE1_RS numeric(19,5), @SEQUENCE1_RE numeric(19,5)) AS  set nocount on IF @SEQUENCE1_RS IS NULL BEGIN SELECT TOP 25  SEQUENCE1, PPERADSC, PPERADAM, DEX_ROW_ID FROM .AF10000 ORDER BY SEQUENCE1 ASC END ELSE IF @SEQUENCE1_RS = @SEQUENCE1_RE BEGIN SELECT TOP 25  SEQUENCE1, PPERADSC, PPERADAM, DEX_ROW_ID FROM .AF10000 WHERE SEQUENCE1 = @SEQUENCE1_RS ORDER BY SEQUENCE1 ASC END ELSE BEGIN SELECT TOP 25  SEQUENCE1, PPERADSC, PPERADAM, DEX_ROW_ID FROM .AF10000 WHERE SEQUENCE1 BETWEEN @SEQUENCE1_RS AND @SEQUENCE1_RE ORDER BY SEQUENCE1 ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_AF10000F_1] TO [DYNGRP]
GO
