SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR42301SS_1] (@ASSIGNMENTCODE char(15), @ASSIGNMENTTYPE smallint, @TIMECARDCODE char(7)) AS  set nocount on SELECT TOP 1  ASSIGNMENTCODE, ASSIGNMENTTYPE, TIMECARDCODE, DEX_ROW_ID FROM .UPR42301 WHERE ASSIGNMENTCODE = @ASSIGNMENTCODE AND ASSIGNMENTTYPE = @ASSIGNMENTTYPE AND TIMECARDCODE = @TIMECARDCODE ORDER BY ASSIGNMENTCODE ASC, ASSIGNMENTTYPE ASC, TIMECARDCODE ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR42301SS_1] TO [DYNGRP]
GO
