SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[E1_SC_GetNextEmployeeNumber]
	@EmployeeNumber CHAR(15) = NULL OUTPUT
as
DECLARE
	@AutoAssign TINYINT
	SELECT @AutoAssign = AUTOASGNEMPID from UPR40201
	IF @AutoAssign = convert(tinyint,0)
		SELECT @EmployeeNumber = 'Err'
	ELSE
	BEGIN
		DECLARE @EMPID CHAR(15),
			@EMPLEN int,
			@NEXTEMP CHAR(15)
		SELECT @EMPID = NEXTEMPID from UPR40201 WITH (TABLOCKX HOLDLOCK) WHERE SETUPKEY = 1
		SELECT @EMPLEN = LEN(@EMPID)
		SELECT @NEXTEMP = Convert(varchar(21),(CONVERT(bigint,@EMPID) + 1))
		WHILE LEN(@NEXTEMP) < @EMPLEN
		BEGIN
			SELECT @NEXTEMP = '0' + @NEXTEMP
		END
		UPDATE UPR40201 SET NEXTEMPID = @NEXTEMP WHERE SETUPKEY = 1
		SELECT @EmployeeNumber = @EMPID
	END

GO
GRANT EXECUTE ON  [dbo].[E1_SC_GetNextEmployeeNumber] TO [DYNGRP]
GO
