SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_VAT10200SS_1] (@CLASSID char(15)) AS  set nocount on SELECT TOP 1  CLASSID, CCode, TMCODE, TRANSNATURE, TCC, PRT, RGN, CNTRYORGN, PRCDRRGM, INCTRMS, DEX_ROW_ID FROM .VAT10200 WHERE CLASSID = @CLASSID ORDER BY CLASSID ASC set nocount off  
GO
GRANT EXECUTE ON  [dbo].[zDP_VAT10200SS_1] TO [DYNGRP]
GO
