SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_ME240463SS_2] (@Queue_ID smallint, @CHEKBKID char(15), @BACHNUMB char(15), @USERID char(15), @INDXLONG int, @Category_Name char(51), @MEFIELDNAME char(61), @SEQNUMBR int) AS /* 14.00.0084.000 */ set nocount on SELECT TOP 1  Queue_ID, CHEKBKID, BACHNUMB, USERID, INDXLONG, MECHKID, SEQNUMBR, Category_Name, MEFIELDNAME, Field_Value, DATE1, DEX_ROW_ID FROM .ME240463 WHERE Queue_ID = @Queue_ID AND CHEKBKID = @CHEKBKID AND BACHNUMB = @BACHNUMB AND USERID = @USERID AND INDXLONG = @INDXLONG AND Category_Name = @Category_Name AND MEFIELDNAME = @MEFIELDNAME AND SEQNUMBR = @SEQNUMBR ORDER BY Queue_ID ASC, CHEKBKID ASC, BACHNUMB ASC, USERID ASC, INDXLONG ASC, Category_Name ASC, MEFIELDNAME ASC, SEQNUMBR ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_ME240463SS_2] TO [DYNGRP]
GO
