SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00905SI] (@TECHSTAT char(11), @DSCRIPTN char(31), @Tech_Available tinyint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .SVC00905 (TECHSTAT, DSCRIPTN, Tech_Available) VALUES ( @TECHSTAT, @DSCRIPTN, @Tech_Available) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00905SI] TO [DYNGRP]
GO
