SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00119SI] (@ITEMNMBR char(31), @INCLUDEINCATALOG smallint, @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .IV00119 (ITEMNMBR, INCLUDEINCATALOG) VALUES ( @ITEMNMBR, @INCLUDEINCATALOG) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00119SI] TO [DYNGRP]
GO
