SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_ME123506SS_1] (@CHEKBKID char(15), @CMTrxNum char(21), @CMTrxType smallint) AS  set nocount on SELECT TOP 1  CHEKBKID, CMTrxNum, paidtorcvdfrom, CMTrxType, TRXAMNT, VOIDDATE, ME_Dummy_File_Convert_De, CNTRLNUM, MEVDTXTP, DEX_ROW_ID FROM .ME123506 WHERE CHEKBKID = @CHEKBKID AND CMTrxNum = @CMTrxNum AND CMTrxType = @CMTrxType ORDER BY CHEKBKID ASC, CMTrxNum ASC, CMTrxType ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_ME123506SS_1] TO [DYNGRP]
GO
