SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B0510102SS_1] (@VENDORID char(15), @MJW_Offering_ID char(21), @LNITMSEQ int) AS /* 12.00.0270.000 */ set nocount on SELECT TOP 1  VENDORID, MJW_Offering_ID, LNITMSEQ, MJW_Agency, MJW_Selling_Date, MJW_Who_Letter, MJW_Cleared_Date, NOTEINDX, DEX_ROW_ID FROM .B0510102 WHERE VENDORID = @VENDORID AND MJW_Offering_ID = @MJW_Offering_ID AND LNITMSEQ = @LNITMSEQ ORDER BY VENDORID ASC, MJW_Offering_ID ASC, LNITMSEQ ASC set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B0510102SS_1] TO [DYNGRP]
GO
