SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DO10100SS_1] (@CUSTNMBR char(15), @DOCNUMBR char(21), @SOPTYPE smallint, @RMDTYPAL smallint, @SEQNUMBR int, @LNITMSEQ int) AS  set nocount on SELECT TOP 1  CUSTNMBR, DOCNUMBR, SOPTYPE, RMDTYPAL, SEQNUMBR, LNITMSEQ, PAYMENTSERVICEREF, DATE1, PAYMENTSERVICEOP, TRXAMNT, PAYMENTSERVICESSTATUS, PAYMENTSERVICESSOURCE, doAUTHCODE, ERMSGTXT, ADDRESSRESULT, DEX_ROW_ID FROM .DO10100 WHERE CUSTNMBR = @CUSTNMBR AND DOCNUMBR = @DOCNUMBR AND SOPTYPE = @SOPTYPE AND RMDTYPAL = @RMDTYPAL AND SEQNUMBR = @SEQNUMBR AND LNITMSEQ = @LNITMSEQ ORDER BY CUSTNMBR ASC, DOCNUMBR ASC, SOPTYPE ASC, RMDTYPAL ASC, SEQNUMBR ASC, LNITMSEQ ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DO10100SS_1] TO [DYNGRP]
GO
