SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_FA00300SI] (@ASSETINDEX int, @BOOKINDX int, @TEFRAFLAG smallint, @ITCAMTTAKEN numeric(19,5), @ITCAMTALLOWED numeric(19,5), @ITCRECAPTURE numeric(19,5), @ORGCOSTBASIS numeric(19,5), @SECT179EXPDED numeric(19,5), @ITCCODEREDAMT numeric(19,5), @MISCCOSTADJ numeric(19,5), @NETCOSTBASIS numeric(19,5), @NOTEINDX numeric(19,5), @LASTMNTDDATE datetime, @LASTMNTDTIME datetime, @LASTMNTDUSERID char(15), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .FA00300 (ASSETINDEX, BOOKINDX, TEFRAFLAG, ITCAMTTAKEN, ITCAMTALLOWED, ITCRECAPTURE, ORGCOSTBASIS, SECT179EXPDED, ITCCODEREDAMT, MISCCOSTADJ, NETCOSTBASIS, NOTEINDX, LASTMNTDDATE, LASTMNTDTIME, LASTMNTDUSERID) VALUES ( @ASSETINDEX, @BOOKINDX, @TEFRAFLAG, @ITCAMTTAKEN, @ITCAMTALLOWED, @ITCRECAPTURE, @ORGCOSTBASIS, @SECT179EXPDED, @ITCCODEREDAMT, @MISCCOSTADJ, @NETCOSTBASIS, @NOTEINDX, @LASTMNTDDATE, @LASTMNTDTIME, @LASTMNTDUSERID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_FA00300SI] TO [DYNGRP]
GO
