SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_SVC00101SS_1] (@TECHID char(11), @STRTDATE datetime) AS  set nocount on SELECT TOP 1  TECHID, STRTDATE, STRTTIME, ENDDATE, ENDTME, TECHSTAT, TECHID2, DEX_ROW_ID FROM .SVC00101 WHERE TECHID = @TECHID AND STRTDATE = @STRTDATE ORDER BY TECHID ASC, STRTDATE DESC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_SVC00101SS_1] TO [DYNGRP]
GO
