SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE  PROCEDURE [dbo].[aagGetDispID_UPR_EditList] @iEMPLOYID char(15), @iPYRNTYPE smallint, @iPYRLRTYP smallint, @iTRXNUMBER int, @iSEQNUMBR int, @iACTINDX int, @iDEPRTMNT char(7), @iJOBTITLE char(7), @iPAYROLCD char(7), @iUPRACTYP smallint, @iPYADNMBR int, @oDistID  int = 0 OUTPUT  AS BEGIN  DECLARE @DistID int   SELECT USERID,  EMPLOYID,  PYRNTYPE,  PYRLRTYP,  TRXNUMBER,  SEQNUMBR,  ACTINDX,  AMNTOPST,  DEPRTMNT,  JOBTITLE,  PAYROLCD,  UPRACTYP,  PYADNMBR,  IDENTITY(int, 1,1) AS DisplayDistID  INTO #newtable1   FROM UPR10209  WHERE USERID = system_user and   PYRNTYPE = @iPYRNTYPE  ORDER BY DEX_ROW_ID   SELECT @DistID = DisplayDistID FROM #newtable1   WHERE EMPLOYID = @iEMPLOYID and   PYRNTYPE = @iPYRNTYPE and   PYRLRTYP = @iPYRLRTYP and   TRXNUMBER = @iTRXNUMBER and   SEQNUMBR = @iSEQNUMBR and   ACTINDX = @iACTINDX and   DEPRTMNT = @iDEPRTMNT and   JOBTITLE = @iJOBTITLE and   PAYROLCD = @iPAYROLCD and   UPRACTYP = @iUPRACTYP and   PYADNMBR = @iPYADNMBR   SELECT @oDistID = @DistID END    
GO
GRANT EXECUTE ON  [dbo].[aagGetDispID_UPR_EditList] TO [DYNGRP]
GO
