SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PA00010SI] (@CUSTNMBR char(15), @BANKNAME char(31), @BNKBRNCH char(21), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .PA00010 (CUSTNMBR, BANKNAME, BNKBRNCH) VALUES ( @CUSTNMBR, @BANKNAME, @BNKBRNCH) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PA00010SI] TO [DYNGRP]
GO
