SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_BS466003SI] (@DATE1 datetime, @BSSI_Allocation_ID char(25), @DEX_ROW_ID int OUT) AS /* 12.00.0270.000 */ set nocount on BEGIN INSERT INTO .BS466003 (DATE1, BSSI_Allocation_ID) VALUES ( @DATE1, @BSSI_Allocation_ID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_BS466003SI] TO [DYNGRP]
GO
