SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_B7100160SI] (@MODULE1 smallint, @VNDCLSID char(11), @DEX_ROW_ID int OUT) AS /* 12.00.0270.000 */ set nocount on BEGIN INSERT INTO .B7100160 (MODULE1, VNDCLSID) VALUES ( @MODULE1, @VNDCLSID) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_B7100160SI] TO [DYNGRP]
GO
