SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PA00001N_2] (@BS int, @VENDORID char(15), @VENDORID_RS char(15), @VENDORID_RE char(15)) AS  set nocount on IF @VENDORID_RS IS NULL BEGIN SELECT TOP 25  CUSTNMBR, VENDORID, CURNCYID, RATETPID, CREATDDT, CRUSRID, MODIFDT, DEX_ROW_ID FROM .PA00001 WHERE ( VENDORID > @VENDORID ) ORDER BY VENDORID ASC END ELSE IF @VENDORID_RS = @VENDORID_RE BEGIN SELECT TOP 25  CUSTNMBR, VENDORID, CURNCYID, RATETPID, CREATDDT, CRUSRID, MODIFDT, DEX_ROW_ID FROM .PA00001 WHERE VENDORID = @VENDORID_RS AND ( VENDORID > @VENDORID ) ORDER BY VENDORID ASC END ELSE BEGIN SELECT TOP 25  CUSTNMBR, VENDORID, CURNCYID, RATETPID, CREATDDT, CRUSRID, MODIFDT, DEX_ROW_ID FROM .PA00001 WHERE VENDORID BETWEEN @VENDORID_RS AND @VENDORID_RE AND ( VENDORID > @VENDORID ) ORDER BY VENDORID ASC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PA00001N_2] TO [DYNGRP]
GO
