SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_VAT10002L_1] (@TMCODE_RS char(7), @TMCODE_RE char(7)) AS  set nocount on IF @TMCODE_RS IS NULL BEGIN SELECT TOP 25  TMCODE, TMCODEDESC, NOTEINDX, DEX_ROW_ID FROM .VAT10002 ORDER BY TMCODE DESC END ELSE IF @TMCODE_RS = @TMCODE_RE BEGIN SELECT TOP 25  TMCODE, TMCODEDESC, NOTEINDX, DEX_ROW_ID FROM .VAT10002 WHERE TMCODE = @TMCODE_RS ORDER BY TMCODE DESC END ELSE BEGIN SELECT TOP 25  TMCODE, TMCODEDESC, NOTEINDX, DEX_ROW_ID FROM .VAT10002 WHERE TMCODE BETWEEN @TMCODE_RS AND @TMCODE_RE ORDER BY TMCODE DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_VAT10002L_1] TO [DYNGRP]
GO
