SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_PM40103SI] (@DISTTYPE smallint, @DSNMSHRT char(7), @DSNMLONG char(31), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .PM40103 (DISTTYPE, DSNMSHRT, DSNMLONG) VALUES ( @DISTTYPE, @DSNMSHRT, @DSNMLONG) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_PM40103SI] TO [DYNGRP]
GO
