SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IVC10500SS_1] (@DOCTYPE smallint, @INVCNMBR char(21), @LNITMSEQ int, @TAXDTLID char(15)) AS  set nocount on SELECT TOP 1  DOCTYPE, INVCNMBR, LNITMSEQ, TAXDTLID, ACTINDX, BKOUTTAX, TXABLETX, STAXAMNT, FRTTXAMT, MSCTXAMT, TAXDTSLS, TDTTXSLS, TXDTOTTX, DELETE1, TRXSORCE, DEX_ROW_ID FROM .IVC10500 WHERE DOCTYPE = @DOCTYPE AND INVCNMBR = @INVCNMBR AND LNITMSEQ = @LNITMSEQ AND TAXDTLID = @TAXDTLID ORDER BY DOCTYPE ASC, INVCNMBR ASC, LNITMSEQ ASC, TAXDTLID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IVC10500SS_1] TO [DYNGRP]
GO
