SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_LK000102L_2] (@LK_Link_Date_RS datetime, @LK_Link_No_RS int, @LK_Link_Date_RE datetime, @LK_Link_No_RE int) AS  set nocount on IF @LK_Link_Date_RS IS NULL BEGIN SELECT TOP 25  LK_Link_No, DSCRIPTN, LK_Link_Date, CREATDDT, LSTDTEDT, LK_Link_Balance, USERID, LSTUSRED, DEX_ROW_ID FROM .LK000102 ORDER BY LK_Link_Date DESC, LK_Link_No DESC, DEX_ROW_ID DESC END ELSE IF @LK_Link_Date_RS = @LK_Link_Date_RE BEGIN SELECT TOP 25  LK_Link_No, DSCRIPTN, LK_Link_Date, CREATDDT, LSTDTEDT, LK_Link_Balance, USERID, LSTUSRED, DEX_ROW_ID FROM .LK000102 WHERE LK_Link_Date = @LK_Link_Date_RS AND LK_Link_No BETWEEN @LK_Link_No_RS AND @LK_Link_No_RE ORDER BY LK_Link_Date DESC, LK_Link_No DESC, DEX_ROW_ID DESC END ELSE BEGIN SELECT TOP 25  LK_Link_No, DSCRIPTN, LK_Link_Date, CREATDDT, LSTDTEDT, LK_Link_Balance, USERID, LSTUSRED, DEX_ROW_ID FROM .LK000102 WHERE LK_Link_Date BETWEEN @LK_Link_Date_RS AND @LK_Link_Date_RE AND LK_Link_No BETWEEN @LK_Link_No_RS AND @LK_Link_No_RE ORDER BY LK_Link_Date DESC, LK_Link_No DESC, DEX_ROW_ID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_LK000102L_2] TO [DYNGRP]
GO
