SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_DD10200SI] (@INDXLONG int, @DDLINE char(255), @DEX_ROW_ID int OUT) AS  set nocount on BEGIN INSERT INTO .DD10200 (INDXLONG, DDLINE) VALUES ( @INDXLONG, @DDLINE) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_DD10200SI] TO [DYNGRP]
GO
