SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_HRPBEN05SS_1] (@COMPANYCODE_I char(7)) AS  set nocount on SELECT TOP 1  COMPANYCODE_I, SET12MONTH_I, O12MONTHSTART_I, SCOPEOFPERIOD_I, DAYS_I, HOURSWORKEDPERDAY_I, DEX_ROW_ID FROM .HRPBEN05 WHERE COMPANYCODE_I = @COMPANYCODE_I ORDER BY COMPANYCODE_I ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_HRPBEN05SS_1] TO [DYNGRP]
GO
