SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_UPR10106SS_1] (@RPTNGYR smallint, @EMPLOYID char(15)) AS  set nocount on SELECT TOP 1  RPTNGYR, EMPLOYID, SEQNUMBR, LOCLCODE, LOCLWGES, LCLINTAX, W2PRINTD, TAXTYPE, DEX_ROW_ID FROM .UPR10106 WHERE RPTNGYR = @RPTNGYR AND EMPLOYID = @EMPLOYID ORDER BY RPTNGYR ASC, EMPLOYID ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_UPR10106SS_1] TO [DYNGRP]
GO
