SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_IV00700VL_3] (@TRNSTLOC_RS char(11), @ORDDOCID_RS char(15), @TRNSTLOC_RE char(11), @ORDDOCID_RE char(15)) AS  set nocount on IF @TRNSTLOC_RS IS NULL BEGIN SELECT TOP 25  ORDDOCID, ORDRDATE, PRMDATE, Status, SHIPMTHD, TRXLOCTN, VIALOCN, TRNSTLOC, CUSTNAME, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, COUNTRY, EMPLOYID, NOTEINDX, DEX_ROW_ID FROM .IV00700V ORDER BY TRNSTLOC DESC, ORDDOCID DESC END ELSE IF @TRNSTLOC_RS = @TRNSTLOC_RE BEGIN SELECT TOP 25  ORDDOCID, ORDRDATE, PRMDATE, Status, SHIPMTHD, TRXLOCTN, VIALOCN, TRNSTLOC, CUSTNAME, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, COUNTRY, EMPLOYID, NOTEINDX, DEX_ROW_ID FROM .IV00700V WHERE TRNSTLOC = @TRNSTLOC_RS AND ORDDOCID BETWEEN @ORDDOCID_RS AND @ORDDOCID_RE ORDER BY TRNSTLOC DESC, ORDDOCID DESC END ELSE BEGIN SELECT TOP 25  ORDDOCID, ORDRDATE, PRMDATE, Status, SHIPMTHD, TRXLOCTN, VIALOCN, TRNSTLOC, CUSTNAME, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIPCODE, COUNTRY, EMPLOYID, NOTEINDX, DEX_ROW_ID FROM .IV00700V WHERE TRNSTLOC BETWEEN @TRNSTLOC_RS AND @TRNSTLOC_RE AND ORDDOCID BETWEEN @ORDDOCID_RS AND @ORDDOCID_RE ORDER BY TRNSTLOC DESC, ORDDOCID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_IV00700VL_3] TO [DYNGRP]
GO
