SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_SY30500SI] (@BCHSOURC char(15), @BACHNUMB char(15), @CREATDDT datetime, @TIME1 datetime, @GLPOSTDT datetime, @SERIES smallint, @NUMOFTRX int, @RCTRXSEQ numeric(19,5), @BCHCOMNT char(61), @RVRSBACH tinyint, @USERID char(15), @CHEKBKID char(15), @BCHTOTAL numeric(19,5), @BACHDATE datetime, @MODIFDT datetime, @CURNCYID char(15), @CNTRLTRX int, @CNTRLTOT numeric(19,5), @APPROVL tinyint, @APPRVLDT datetime, @APRVLUSERID char(15), @ORIGIN smallint, @TRXSORCE char(13), @Workflow_Status smallint, @CARDNAME char(15), @DEX_ROW_ID int OUT) AS /* 14.00.0084.000 */ set nocount on BEGIN INSERT INTO .SY30500 (BCHSOURC, BACHNUMB, CREATDDT, TIME1, GLPOSTDT, SERIES, NUMOFTRX, RCTRXSEQ, BCHCOMNT, RVRSBACH, USERID, CHEKBKID, BCHTOTAL, BACHDATE, MODIFDT, CURNCYID, CNTRLTRX, CNTRLTOT, APPROVL, APPRVLDT, APRVLUSERID, ORIGIN, TRXSORCE, Workflow_Status, CARDNAME) VALUES ( @BCHSOURC, @BACHNUMB, @CREATDDT, @TIME1, @GLPOSTDT, @SERIES, @NUMOFTRX, @RCTRXSEQ, @BCHCOMNT, @RVRSBACH, @USERID, @CHEKBKID, @BCHTOTAL, @BACHDATE, @MODIFDT, @CURNCYID, @CNTRLTRX, @CNTRLTOT, @APPROVL, @APPRVLDT, @APRVLUSERID, @ORIGIN, @TRXSORCE, @Workflow_Status, @CARDNAME) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_SY30500SI] TO [DYNGRP]
GO
