SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_CM20203SS_1] (@CHEKBKID char(15), @BCHSOURC char(15), @BACHNUMB char(15)) AS  set nocount on SELECT TOP 1  CHEKBKID, BCHSOURC, BACHNUMB, POSTEDDT, NUMOFTRX, BCHTOTAL, USERID, EFTGenerationTimestamp, EFT_Status, SERIES, DEX_ROW_ID FROM .CM20203 WHERE CHEKBKID = @CHEKBKID AND BCHSOURC = @BCHSOURC AND BACHNUMB = @BACHNUMB ORDER BY CHEKBKID ASC, BCHSOURC ASC, BACHNUMB ASC, DEX_ROW_ID ASC set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_CM20203SS_1] TO [DYNGRP]
GO
