SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[zDP_MS273517SI] (@MSO_Doc_Number char(21), @MSO_Doc_Type smallint, @BACHNUMB char(15), @SEQNUMBR int, @DEX_ROW_ID int OUT) AS /* 12.00.0311.000 */ set nocount on BEGIN INSERT INTO .MS273517 (MSO_Doc_Number, MSO_Doc_Type, BACHNUMB, SEQNUMBR) VALUES ( @MSO_Doc_Number, @MSO_Doc_Type, @BACHNUMB, @SEQNUMBR) SELECT @DEX_ROW_ID = @@IDENTITY END set nocount off 
GO
GRANT EXECUTE ON  [dbo].[zDP_MS273517SI] TO [DYNGRP]
GO
