SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
 CREATE PROC [dbo].[zDP_MC40301L_1] (@RATETPID_RS char(15), @CURNCYID_RS char(15), @EXGTBLID_RS char(15), @RATETPID_RE char(15), @CURNCYID_RE char(15), @EXGTBLID_RE char(15)) AS  set nocount on IF @RATETPID_RS IS NULL BEGIN SELECT TOP 25  CURNCYID, RATETPID, EXGTBLID, DFLTRATE, REALGAIN, REALLOSS, UNRLGAIN, UNRLLOSS, FINOFFST, PUROFFST, SLSOFFST, RNDWTOFF, RNDDIFF, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40301 ORDER BY RATETPID DESC, CURNCYID DESC, EXGTBLID DESC END ELSE IF @RATETPID_RS = @RATETPID_RE BEGIN SELECT TOP 25  CURNCYID, RATETPID, EXGTBLID, DFLTRATE, REALGAIN, REALLOSS, UNRLGAIN, UNRLLOSS, FINOFFST, PUROFFST, SLSOFFST, RNDWTOFF, RNDDIFF, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40301 WHERE RATETPID = @RATETPID_RS AND CURNCYID BETWEEN @CURNCYID_RS AND @CURNCYID_RE AND EXGTBLID BETWEEN @EXGTBLID_RS AND @EXGTBLID_RE ORDER BY RATETPID DESC, CURNCYID DESC, EXGTBLID DESC END ELSE BEGIN SELECT TOP 25  CURNCYID, RATETPID, EXGTBLID, DFLTRATE, REALGAIN, REALLOSS, UNRLGAIN, UNRLLOSS, FINOFFST, PUROFFST, SLSOFFST, RNDWTOFF, RNDDIFF, Base_Exchange_Rate_On, DEX_ROW_ID FROM .MC40301 WHERE RATETPID BETWEEN @RATETPID_RS AND @RATETPID_RE AND CURNCYID BETWEEN @CURNCYID_RS AND @CURNCYID_RE AND EXGTBLID BETWEEN @EXGTBLID_RS AND @EXGTBLID_RE ORDER BY RATETPID DESC, CURNCYID DESC, EXGTBLID DESC END set nocount off    
GO
GRANT EXECUTE ON  [dbo].[zDP_MC40301L_1] TO [DYNGRP]
GO
